"use client";
import { useState } from "react";
import { Bar, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
type Month = {key:string;label:string;businesses:number;revenue:number;subscriptions:number};
export default function DashboardTrend({months}:{months:Month[]}) {
  const [mode,setMode]=useState<"businesses"|"revenue"|"subscriptions">("businesses");
  return <>
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-bold text-slate-900">New businesses & revenue trend</h2><p className="mt-1 text-xs text-slate-500">{months[0]?.key} – {months.at(-1)?.key} · USD · UTC</p></div><div className="flex rounded-lg bg-slate-100 p-1">{(["businesses","revenue","subscriptions"] as const).map(key=><button key={key} onClick={()=>setMode(key)} aria-pressed={mode===key} className={`rounded-md px-2.5 py-1.5 text-[11px] font-semibold capitalize ${mode===key?"bg-blue-600 text-white shadow-sm":"text-slate-500"}`}>{key}</button>)}</div></div>
    <div className="mt-3 flex justify-end gap-4 text-[10px] text-slate-400"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-blue-600"/>{mode==="businesses"?"New businesses":mode==="subscriptions"?"Approved subscriptions":"Revenue"}</span>{mode!=="revenue"&&<span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-blue-300"/>Revenue (USD)</span>}</div>
    <div className="mt-3 h-56 w-full min-w-0"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={months} margin={{top:12,right:4,bottom:0,left:-14}} accessibilityLayer><CartesianGrid stroke="#edf2f7" vertical={false}/><XAxis dataKey="label" axisLine={false} tickLine={false} fontSize={10}/><YAxis yAxisId="left" axisLine={false} tickLine={false} fontSize={10} allowDecimals={mode==="revenue"} width={48}/>{mode!=="revenue"&&<YAxis yAxisId="right" orientation="right" axisLine={false} tickLine={false} fontSize={10} width={45}/>}<Tooltip contentStyle={{borderRadius:12,borderColor:"#e2e8f0",fontSize:12}} formatter={(value,name)=>[name==="Revenue"?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(value)):value,name]}/><Bar yAxisId="left" dataKey={mode} name={mode==="revenue"?"Revenue":mode==="subscriptions"?"Approved subscriptions":"New businesses"} fill="#2563eb" radius={[5,5,0,0]} maxBarSize={38} isAnimationActive={false}/>{mode!=="revenue"&&<Line yAxisId="right" type="monotone" dataKey="revenue" name="Revenue" stroke="#93c5fd" strokeWidth={2} dot={{r:3,fill:"white"}} isAnimationActive={false}/>}</ComposedChart></ResponsiveContainer></div>
    <details className="mt-2 text-[11px] text-slate-500"><summary className="cursor-pointer">View chart data</summary><div className="mt-2 overflow-x-auto"><table className="w-full text-left"><thead><tr><th>Month</th><th>Businesses</th><th>USD revenue</th><th>Subscriptions</th></tr></thead><tbody>{months.map(m=><tr key={m.key}><td>{m.key}</td><td>{m.businesses}</td><td>{m.revenue.toFixed(2)}</td><td>{m.subscriptions}</td></tr>)}</tbody></table></div></details>
  </>;
}
