import type { ReceiptContext } from '@/lib/receipts/receipt-model';
export type Product = {
  id: string; name: string; sku: string | null; barcode: string | null;
  image_url: string | null; variant_image_url: string | null;
  selling_price: number; stock_quantity: number; low_stock_quantity: number;
  category_id: string | null; size: string | null; color: string | null;
  product_type: string | null; variant_group_id: string | null;
  brand: string | null; compare_at_price: number | null; created_at: string; sold: number;
};
export type Category = { id: string; name: string };
export type Customer = { id: string; name: string; phone: string | null; address?: string | null; loyalty_points: number };
export type Branch = { id: string; name: string; is_default: boolean; timezone: string | null };
export type LocationStock = { product_id: string; location_id: string; quantity: number; low_stock_threshold: number };
export type OptionGroup = { id: string; product_id: string; name: string; selection_type: 'single' | 'multiple'; is_required: boolean; min_selections: number; max_selections: number; sort_order: number };
export type ProductOption = { id: string; product_id: string; group_id: string; name: string; price_adjustment: number; is_default: boolean; is_active: boolean; sort_order: number };
export type OptionSnapshot = { id: string; name: string; groupName: string; priceAdjustment: number };
export type CartLine = { key: string; productId: string; quantity: number; optionIds: string[]; unitPrice: number; name: string; variant: string; image: string | null; selectedOptions: OptionSnapshot[] };
export type PaymentMethod = 'cash' | 'cod' | 'deposit' | 'bank_transfer' | 'other' | 'credit' | 'split';
export type Tender = { method: 'cash' | 'bank_transfer' | 'other'; amount: number; reference: string };
export type DiscountType = 'amount' | 'percent';
export type ShippingMethod = 'in_store' | 'pickup' | 'delivery';
export type ShippingCarrier = '' | 'jt' | 'vet' | 'grab' | 'other';
export type ShippingDetails = { method: ShippingMethod; recipientName: string; phone: string; address: string; carrier?: ShippingCarrier; carrierOther?: string };
export type CurrencyQuote = { baseCurrency: string; displayCurrency: string; usdKhrRate: number; enabled: boolean };
export type CartDraft = { branchId: string; customerId: string; lines: CartLine[]; discount: string; deliveryFee: string; points: string; note: string; paymentMethod: PaymentMethod; discountType?: DiscountType; shipping?: ShippingDetails; tenders?: Tender[]; displayCurrency?: string; baseCurrency?: string; createCustomer?: boolean };
export type HeldOrder = { id: string; label: string; version: number; created_at: string; updated_at: string; draft: CartDraft };
export type PosSettings = { currency: string; taxRate: number; pointValue: number; loyaltyEnabled: boolean; spendPerPoint: number; loyaltyMinimumOrder: number; dualCurrencyEnabled?: boolean; usdKhrRate?: number };
export type Workspace = {
  receiptContext?: ReceiptContext;
  checkoutVersion?: number; canCreateCustomer?: boolean; inventoryVersion?: number; inventoryLocationCount?: number;
  businessId: string; businessName: string; userId: string; canConfigure: boolean;
  productMode: string; businessType: string; products: Product[]; categories: Category[];
  customers: Customer[]; branches: Branch[]; stock: LocationStock[]; groups: OptionGroup[];
  options: ProductOption[]; settings: PosSettings; holds: HeldOrder[];
  shift: { id: string; location_id: string } | null; defaultBranchId: string; loadedAt: string;
};
export type CheckoutInput = {
  uiVersion?: number; currencyQuote?: CurrencyQuote; createCustomer?: boolean;
  requestId: string; branchId: string; customerId: string | null;
  items: { productId: string; quantity: number; optionIds: string[]; expectedUnitPrice: number }[];
  paymentMethod: PaymentMethod; amountPaid: number; tenders: Tender[]; paymentsConfirmed: boolean;
  discount: number; discountType?: DiscountType; discountValue?: number; shipping?: ShippingDetails;
  deliveryFee: number; redeemPoints: number; note: string;
  expectedTotal: number; expectedTaxRate: number; holdId: string | null; holdVersion: number | null;
};
export type SaleReceipt = {
  initialStatus?: string; cashierName?: string; timezone?: string; isOrderRecord?: boolean;
  customerId?: string | null; customerCreated?: boolean; currencyQuote?: CurrencyQuote;
  orderId: string; orderNumber: string; createdAt: string; businessName: string;
  customerName: string; branchName: string; currency: string; subtotal: number;
  manualDiscount: number; discount: number; deliveryFee: number; taxRate: number;
  taxAmount: number; total: number; amountPaid: number; change: number; remaining: number;
  discountType?: DiscountType; discountValue?: number; shipping?: ShippingDetails;
  pointsRedeemed: number; pointsEarned: number; note: string; tenders: Tender[];
  lines: { name: string; variant: string | null; quantity: number; unitPrice: number; subtotal: number; options: OptionSnapshot[] }[];
};
export type ActionResult<T> = { success: true; data: T } | { success: false; message: string; uncertain?: boolean };
export type CatalogFilters = { search: string; category: string; brand: string; stock: string; price: string; color: string; size: string; favoritesOnly: boolean; sort: string };
export type ProductGroup = { key: string; name: string; variants: Product[]; image: string | null; category: string; price: number; stock: number; threshold: number; sold: number; createdAt: string; favorite: boolean };
