"use client";
import {useId} from "react";
import {CartesianGrid,Legend,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {ProductRankBars} from "@/components/analytics-charts";
type Props={dailySales:{date:string;revenue:number;profit:number}[];topProducts:{name:string;quantity:number;revenue:number;profit:number}[];expenseCategories:{name:string;amount:number;count:number}[]};
export default function ReportCharts({dailySales,topProducts}:Props){
 const gradient=useId().replaceAll(":","");
 return <div className={`grid items-start gap-5 ${topProducts.length?"xl:grid-cols-2":""}`}><div className="min-w-0 space-y-5"><section className="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-slate-900">Revenue and Profit</h2><p className="mt-1 text-sm text-slate-500">Daily performance for the selected period</p><div className={dailySales.some(d=>d.revenue!==0||d.profit!==0)?"mt-4 h-64":"mt-4 h-20"}>{dailySales.some(d=>d.revenue!==0||d.profit!==0)?<ResponsiveContainer width="100%" height="100%"><LineChart data={dailySales} margin={{top:10,right:12,left:0,bottom:0}}><defs><linearGradient id={gradient} x1="0" y1="0" x2="1" y2="0"><stop offset="0%" stopColor="#f51b62"/><stop offset="100%" stopColor="#7000ed"/></linearGradient></defs><CartesianGrid strokeDasharray="6 8" stroke="#e2e8f0"/><XAxis dataKey="date" tickFormatter={dateLabel} tickLine={false} axisLine={false} fontSize={11} minTickGap={25}/><YAxis tickFormatter={n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",notation:"compact"}).format(n)} tickLine={false} axisLine={false} width={55} fontSize={11}/><Tooltip contentStyle={{border:0,borderRadius:16,background:"#171630",color:"white"}} labelFormatter={v=>dateLabel(String(v))} formatter={(value,name)=>[new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(value)),name]} cursor={{stroke:"#8b5cf6",strokeDasharray:"6 6"}}/><Legend iconType="circle" iconSize={8}/><Line type="monotone" dataKey="revenue" name="Revenue" stroke={`url(#${gradient})`} strokeWidth={3} dot={dailySales.length===1} activeDot={{r:6,fill:"#8b5cf6",stroke:"white",strokeWidth:3}} isAnimationActive={false}/><Line type="monotone" dataKey="profit" name="Gross Profit" stroke="#a8b2c1" strokeWidth={2.5} dot={dailySales.length===1} isAnimationActive={false}/></LineChart></ResponsiveContainer>:<p className="flex h-full items-center justify-center text-sm text-slate-500">No sales in this period.</p>}</div></section></div><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-slate-900">Top-Selling Products</h2><p className="mb-5 mt-1 text-sm text-slate-500">Products ranked by quantity sold</p><div className="max-h-[340px] overflow-y-auto pr-1"><ProductRankBars rows={topProducts.map(p=>({label:p.name,value:p.quantity}))}/></div></section></div>;
}
function dateLabel(value:string){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`));}
