import { createClient } from "@/lib/supabase/branch-server";
import { saveNotificationRoleSettings } from "../notifications/actions";
export default async function AlertRecipients({businessId}: {businessId:string}) {
 const supabase=await createClient();
 const {data:roleSettings,error}=await supabase.from("branch_notification_role_settings").select("notification_type,target_roles").eq("business_id",businessId);
 if(error) return <p role="alert" className="text-red-600">Unable to load alert recipients. Please refresh.</p>;
 const defaults:Record<string,string[]>={new_order:["owner","admin","manager","cashier"],khqr_pending:["owner","admin","manager","cashier"],low_stock:["owner","admin","manager"],purchase_order:["owner","admin","manager"],stock_transfer:["owner","admin","manager"],register_variance:["owner","admin","manager"],credit_overdue:["owner","admin","manager"],scheduled_order:["owner","admin","manager","cashier"]};
 const currentRoles=new Map((roleSettings??[]).map((r:{notification_type:string;target_roles:string[]})=>[r.notification_type,r.target_roles as string[]]));
 const typeLabels:Record<string,string>={new_order:"New online / QR order",khqr_pending:"KHQR pending verification",low_stock:"Low stock",purchase_order:"Purchase order awaiting receipt",stock_transfer:"Stock transfer in transit",register_variance:"Register over / short",credit_overdue:"Overdue customer credit",scheduled_order:"Scheduled order reminder"};

 return <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-semibold">Who receives each alert?</h2><p className="mt-1 text-sm text-slate-500">Owner can control notification visibility by staff role.</p><form action={saveNotificationRoleSettings} className="mt-5 overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="py-3">Alert</th>{["owner","admin","manager","cashier"].map(r=><th key={r} className="px-3 py-3 capitalize">{r}</th>)}</tr></thead><tbody>{Object.entries(typeLabels).map(([type,label])=>{const roles=currentRoles.get(type)??defaults[type]; return <tr key={type} className="border-b last:border-0"><td className="py-3 font-medium">{label}</td>{["owner","admin","manager","cashier"].map(role=><td key={role} className="px-3 py-3"><input type="checkbox" name={`${type}:${role}`} defaultChecked={roles.includes(role)} className="h-4 w-4 rounded border-slate-300"/></td>)}</tr>})}</tbody></table><button className="mt-5 rounded-xl bg-blue-600 px-4 py-2.5 font-semibold text-white hover:bg-blue-700">Save alert roles</button></form></section>;
}
