import { DateFilterScope, DateFilterContent, NavigationDateRange, dateFilterStyles } from "@/components/date-range-filter";
import MobileListCard, { MobileList } from "@/components/mobile-list-card";
import { requirePermission } from '@/lib/auth/require-permission';
import { getBranchContext, getViewingBranchId } from '@/lib/branches/context';
import { createClient } from '@/lib/supabase/server';
import { supabaseAdmin } from '@/lib/supabase/admin';
import NavigationForm from '@/components/navigation-form';
import { staffKpis, staffReportDates, type StaffSale } from '@/lib/analytics/staff-report';
import { BarChart3, ShoppingBag, Package, Users, Trophy, SlidersHorizontal, X } from 'lucide-react';

const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
export default async function StaffReport({searchParams}:{searchParams:Promise<{branch?:string;range?:string;from?:string;to?:string}>}) {
 const business=await requirePermission('reports.view');
 const params=await searchParams;const context=await getBranchContext();
 const branchId=business.role==='owner'?await getViewingBranchId(params.branch):context.ownBranchId;
 const branches=business.role==='owner'?context.branches:context.branches.filter(b=>b.id===branchId);
 let dates;try{dates=staffReportDates(params.range,params.from,params.to);}catch(error){return <p role="alert" className="rounded-xl bg-amber-50 p-5 text-amber-900">{error instanceof Error?error.message:'Invalid date range.'} <a href="/dashboard/staff-report" className="underline">Reset dates</a></p>;}
 let roster=supabaseAdmin.from('business_members').select('user_id,team_name,role,default_location_id').eq('business_id',business.id).eq('is_active',true);
 if(branchId)roster=roster.or(`default_location_id.eq.${branchId},role.eq.owner`);
 // The staff roster does not depend on the sales pages; start it alongside them.
 const rosterResult=roster.then(r=>r);
 const db=await createClient();const orders:StaffSale[]=[];
 for(let offset=0;;offset+=500){
  let query=db.from('orders').select('id,order_number,staff_user_id,staff_name,order_source,status,total,discount,created_at,order_items(quantity),returns(refund_amount,status,return_items(quantity))')
   .eq('business_id',business.id).or('order_source.eq.pos,order_source.eq.manual,order_source.is.null').gte('created_at',dates.start).lte('created_at',dates.end).order('created_at').order('id').range(offset,offset+499);
  if(branchId)query=query.eq('location_id',branchId);
  const {data,error}=await query;if(error)throw new Error('Unable to load staff sales. Apply the staff report migration and retry.');
  orders.push(...(data??[]) as StaffSale[]);if(!data||data.length<500)break;
 }
 const {data:members,error}=await rosterResult;if(error)throw new Error('Unable to load staff.');
 const kpi=staffKpis(orders,(members??[]).map(m=>({userId:m.user_id,name:m.team_name||`${m.role==='owner'?'Owner':'Team member'}`})));
 const leaders=kpi.ranked.filter(r=>r.id!=='unassigned'&&r.orders>0).slice(0,5);
 return <DateFilterScope><main className="space-y-5">
  <header className="flex flex-wrap items-center justify-between gap-4 max-sm:hidden"><div><h1 className="text-3xl font-bold text-slate-950">Staff Report</h1><p className="mt-1 text-sm text-slate-500">Sales performance by staff · Cambodia time (UTC+7)</p></div><span className="rounded-xl bg-blue-50 px-4 py-2 text-sm font-medium text-blue-700" data-i18n-ignore={(branchId) && (true)}>{branchId?branches.find(b=>b.id===branchId)?.name:'All branches'}</span></header>
  <NavigationDateRange path="/dashboard/staff-report" query={{ branch: branchId || "all" }} from={dates.from} to={dates.to} today={staffReportDates('today').to} maxSpanDays={365} />
  <div className={dateFilterStyles.desktop}><NavigationForm className="flex flex-wrap items-end gap-3" maxSpanDays={365}>
    <input type="hidden" name="range" value={params.range||'yesterday'} /><input type="hidden" name="from" value={dates.from} /><input type="hidden" name="to" value={dates.to} />
    <label className="text-xs font-semibold text-slate-500">Branch<select name="branch" defaultValue={branchId||'all'} className="mt-1 block min-w-44 rounded-lg border border-slate-200 p-2 text-sm text-slate-900">{business.role==='owner'&&<option value="all">All branches</option>}{branches.map(b=><option key={b.id} value={b.id} data-i18n-ignore="true">{b.name}</option>)}</select></label>
    <button className="rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white">Apply</button>
  </NavigationForm></div>
  {/* Phones: the filter form is a bottom sheet opened by a floating button (CSS :target). */}
  <a href="#staff-filters" className="fixed bottom-[max(1rem,env(safe-area-inset-bottom))] right-4 z-40 inline-flex min-h-12 items-center gap-2 rounded-full bg-blue-600 px-5 text-sm font-semibold text-white shadow-lg sm:hidden"><SlidersHorizontal size={18}/>Filter</a>
  <div id="staff-filters" className={`${dateFilterStyles.legacy} max-sm:!m-0 max-sm:fixed max-sm:inset-0 max-sm:z-50 max-sm:hidden max-sm:items-end max-sm:bg-slate-950/40 max-sm:target:flex`}>
  <a href="#" aria-label="Close filters" className="absolute inset-0 sm:hidden"/>
  <NavigationForm key={JSON.stringify(params)} reset={{range:'yesterday',from:'',to:''}} maxSpanDays={365} className="flex flex-wrap items-end gap-3 rounded-2xl border border-slate-200 bg-white p-4 max-sm:relative max-sm:grid max-sm:max-h-[90dvh] max-sm:w-full max-sm:grid-cols-[1fr_1fr] max-sm:overflow-y-auto max-sm:rounded-b-none max-sm:rounded-t-3xl max-sm:border-0 max-sm:px-5 max-sm:pb-[max(1.25rem,env(safe-area-inset-bottom))] max-sm:pt-3">
   <div className="col-span-2 sm:hidden"><div className="mx-auto h-1.5 w-12 rounded-full bg-slate-200"/><div className="mt-4 flex items-start justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-900">Filter Staff Report</h2><p className="mt-1 text-sm text-slate-500">Select branch and date range</p></div><a href="#" aria-label="Close filters" className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-slate-100 text-slate-600"><X size={20}/></a></div></div>
   <label className="text-xs font-semibold text-slate-500 max-sm:col-span-2 max-sm:text-sm">Branch<select name="branch" defaultValue={branchId||'all'} className="mt-1 block min-w-44 max-sm:w-full rounded-lg border border-slate-200 p-2 text-sm text-slate-900">{business.role==='owner'&&<option value="all">All branches</option>}{branches.map(b=><option key={b.id} value={b.id} data-i18n-ignore="true">{b.name}</option>)}</select></label>
   <label className="text-xs font-semibold text-slate-500 max-sm:col-span-2 max-sm:text-sm">Period<select name="range" defaultValue={params.range||'yesterday'} className="mt-1 block rounded-lg max-sm:w-full border border-slate-200 p-2 text-sm text-slate-900"><option value="yesterday">Yesterday</option><option value="today">Today</option><option value="7days">7 days</option><option value="30days">30 days</option><option value="custom">Custom dates</option></select></label>
   <label className="min-w-0 text-xs font-semibold text-slate-500 max-sm:text-sm">From<input type="date" name="from" defaultValue={dates.from} className="mt-1 block rounded-lg max-sm:w-full border border-slate-200 p-2 text-sm text-slate-900"/></label>
   <label className="min-w-0 text-xs font-semibold text-slate-500 max-sm:text-sm">To<input type="date" name="to" defaultValue={dates.to} className="mt-1 block rounded-lg max-sm:w-full border border-slate-200 p-2 text-sm text-slate-900"/></label>
   <button className="rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white max-sm:col-span-2 max-sm:mt-2 max-sm:min-h-12 max-sm:rounded-xl max-sm:text-base">Apply</button>
   <button type="reset" className="col-span-2 grid min-h-12 place-items-center rounded-xl bg-slate-100 font-semibold text-slate-600 sm:hidden">Reset</button>
  </NavigationForm>
  </div>
  <DateFilterContent className="space-y-5"><div className="grid gap-4 max-sm:grid-cols-4 max-sm:gap-2 sm:grid-cols-2 xl:grid-cols-4">{[{label:'Sales value',value:money(kpi.sales),icon:BarChart3},{label:'Orders',value:kpi.orders,icon:ShoppingBag},{label:'Average order',value:money(kpi.orders?kpi.sales/kpi.orders:0),icon:Users},{label:'Items sold',value:kpi.units,icon:Package}].map(c=><section key={c.label} className="flex min-w-0 items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5 max-sm:rounded-xl max-sm:p-2"><span className="rounded-xl bg-blue-50 p-3 text-blue-600 max-sm:hidden"><c.icon size={22}/></span><div className="min-w-0"><p className="text-sm text-slate-500 max-sm:text-[10px] max-sm:leading-tight">{c.label}</p><strong className="break-words text-2xl text-slate-950 max-sm:text-xs">{c.value}</strong></div></section>)}</div>
  {kpi.unassigned>0&&<p className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">{kpi.unassigned} older orders have no reliable cashier identity. They appear as Unassigned and are excluded from staff rankings.</p>}
  <div className="grid items-start gap-5 lg:grid-cols-2">
   <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="flex items-center gap-2 text-lg font-bold"><Trophy size={20} className="text-amber-500"/>Top staff</h2><p className="mt-1 text-xs text-slate-500">Ranked by sales value</p><div className="mt-5 space-y-4">{leaders.map((r,i)=><div key={r.id}><div className="mb-1 flex justify-between text-sm"><span><strong className={i===0?'text-amber-600':i===1?'text-slate-500':'text-orange-700'}>#{i+1}</strong> <span data-i18n-ignore="true">{r.name}</span></span><strong>{money(r.sales)}</strong></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-blue-500" style={{width:`${leaders[0]?.sales?Math.max(1,r.sales/leaders[0].sales*100):0}%`}}/></div><p className="mt-1 text-xs text-slate-500">{r.orders} orders · {r.units} items</p></div>)}{!leaders.length&&<p className="py-4 text-sm text-slate-500">No attributed staff sales in this period.</p>}</div></section>
   <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">Top orders</h2><p className="mt-1 text-xs text-slate-500">Highest sales value</p><div className="mt-3 divide-y divide-slate-100">{kpi.topOrders.map(o=><div key={o.id} className="flex justify-between gap-3 py-3"><div><p className="text-sm font-semibold" data-i18n-ignore="true">{o.order_number}</p><p className="text-xs text-slate-500">{o.staff_name||'Unassigned'}</p></div><strong className="text-sm">{money(Number(o.total)*100)}</strong></div>)}{!kpi.topOrders.length&&<p className="py-4 text-sm text-slate-500">No sales in this period.</p>}</div></section>
  </div>
  <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><h2 className="p-5 text-lg font-bold">Staff performance</h2><div className="overflow-x-auto"><MobileList>{kpi.ranked.map(r=><MobileListCard key={r.id} media={<span className="text-lg font-bold text-blue-600" data-i18n-ignore="true">{r.name.trim().slice(0,1).toUpperCase()}</span>} title={<span data-i18n-ignore="true">{r.name}</span>} date={`${r.orders} orders · ${r.units} items`} primary={`Avg. ${money(r.orders?r.sales/r.orders:0)} · Discounts ${money(r.discount)}`} secondary={`Refunds ${money(r.refunds)} · Cancelled ${r.cancelled}`} amount={money(r.sales)} status={{ label: `${r.orders?Math.round(r.completed/r.orders*100):0}% completed`, tone: "green" }} data-i18n-ignore-attributes="title"/>)}</MobileList><table data-phone-layout="custom" className="max-lg:hidden w-full whitespace-nowrap text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{['Staff','Orders','Sales','Avg. order','Items','Discounts','Refunds','Cancelled','Completed'].map(h=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{kpi.ranked.map(r=><tr key={r.id}><td className="px-5 py-4 font-semibold" data-i18n-ignore="true">{r.name}</td>{[r.orders,money(r.sales),money(r.orders?r.sales/r.orders:0),r.units,money(r.discount),money(r.refunds),r.cancelled,`${r.orders?Math.round(r.completed/r.orders*100):0}%`].map((v,i)=><td key={i} className="px-5 py-4">{v}</td>)}</tr>)}</tbody></table></div><p className="border-t border-slate-100 p-4 text-xs leading-5 text-slate-500">POS and manual orders only. Cancelled orders are excluded from sales. Sales use current order totals after returns; refunds are shown separately and are not subtracted twice. Completed is the share of non-cancelled orders marked completed.</p></section>
 </DateFilterContent></main></DateFilterScope>;
}
