'use client';
import {useEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import Link from 'next/link';
import {Activity,ChevronLeft,ChevronRight,Copy,Crown,Eye,EyeOff,Filter,KeyRound,MoreHorizontal,Plus,RefreshCw,Search,ShieldCheck,Trash2,UserCheck,UserMinus,UserRound,Users,X} from 'lucide-react';
import {createTeamUser,loadUsersWorkspace,updateTeamUser} from './users-workspace-actions';
import RolePermissionsEditor from './role-permissions-editor';
import {canManageTeamMember,createIssue,editIssue,filterTeam,TEAM_ROLE_LABELS,TEAM_ROLE_NOTES} from '@/lib/users/team-model';
import type {TeamWorkspace,TeamRow,TeamEditInput,TeamCreateInput} from '@/lib/users/team-model';
import type {EditablePermissionRole,Permission} from '@/lib/auth/permissions';
import type {BusinessRole} from '@/lib/business/types';
import s from './users-workspace.module.css';

function id(){return crypto.randomUUID();}
function password(){const bytes=crypto.getRandomValues(new Uint8Array(20));const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%';return Array.from(bytes,x=>chars[x%chars.length]).join('');}
function date(value:string|null){if(!value)return 'Never signed in';const n=new Date(value);return Number.isNaN(n.getTime())?'Unavailable':n.toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});}
function statusLabel(row:TeamRow){return row.status==='pending'?'Pending setup':row.status==='active'?'Active':'Disabled';}
function Modal({title,children,onClose,locked=false,wide=false}:{title:string;children:ReactNode;onClose:()=>void;locked?:boolean;wide?:boolean}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const before=document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>{ref.current?.close();before?.focus();};},[]);
 return <dialog ref={ref} className={`${s.dialog} ${wide?s.wide:''}`} aria-label={title} onCancel={e=>{e.preventDefault();if(!locked)onClose();}}><div className={s.dialogInner}><header><div><h2>{title}</h2>{title==='Role Permissions'&&<p className={s.permissionSubtitle}>Control access for each role across your workspace.</p>}</div><button type="button" aria-label="Close dialog" className={s.iconButton} disabled={locked} onClick={onClose}><X size={20}/></button></header><div className={s.dialogBody}>{children}</div></div></dialog>;
}
export default function UsersWorkspace({initial}:{initial:TeamWorkspace}){
 const [data,setData]=useState(initial);const [query,setQuery]=useState('');const [tab,setTab]=useState('all');const [role,setRole]=useState('all');const [branch,setBranch]=useState('all');const [sort,setSort]=useState('newest');const [filters,setFilters]=useState(false);const [page,setPage]=useState(1);const [pageSize,setPageSize]=useState(15);const [selected,setSelected]=useState<string[]>([]);
 const [busy,setBusy]=useState('');const busyRef=useRef(false);const [notice,setNotice]=useState<{error:boolean;text:string}|null>(null);const [dialog,setDialog]=useState<'permissions'|'activity'|'view'|'edit'|'disable'|'enable'|'remove'|null>(null);const [target,setTarget]=useState<TeamRow|null>(null);const [dialogError,setDialogError]=useState('');const [confirmation,setConfirmation]=useState('');const [edit,setEdit]=useState<TeamEditInput>({name:'',phone:'',role:'staff',branchId:''});
 const [form,setForm]=useState<TeamCreateInput>({requestId:'',name:'',email:'',phone:'',role:'staff',branchId:initial.branches[0]?.id||'',password:'',sendInvite:false,requirePasswordChange:true});const [showPassword,setShowPassword]=useState(false);const [generated,setGenerated]=useState(true);const [pendingCreate,setPendingCreate]=useState(false);const [createError,setCreateError]=useState('');const [lastTemporaryPassword,setLastTemporaryPassword]=useState('');
 const [menu,setMenu]=useState<string|null>(null);const [menuPosition,setMenuPosition]=useState({top:0,left:0});const menuRef=useRef<HTMLDivElement>(null);const searchRef=useRef<HTMLInputElement>(null);const activityRef=useRef<HTMLElement>(null);
 const key=`tenh:team-request:${initial.businessId}:${initial.actorId}`;
 const assignable=data.assignableRoles;
 useEffect(()=>{let restored=false;try{const saved=JSON.parse(sessionStorage.getItem(key)||'null');if(saved?.requestId){setForm({...saved,password:password()});setPendingCreate(true);setCreateError('A previous create request needs confirmation. Retry the same request; an existing account password will not be changed.');restored=true;}}catch{/* Create handles unavailable storage before submitting. */}if(!restored)setForm(old=>({...old,requestId:id(),password:password()}));},[key]);
 useEffect(()=>{setPage(1);setSelected([]);},[query,tab,role,branch,sort,pageSize]);
 useEffect(()=>{if(!menu)return;const outside=(e:PointerEvent)=>{if(!menuRef.current?.contains(e.target as Node))setMenu(null);};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(null);};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape);};},[menu]);
 const filtered=useMemo(()=>filterTeam(data.rows,query,tab,role,branch,sort),[data.rows,query,tab,role,branch,sort]);const pages=Math.max(1,Math.ceil(filtered.length/pageSize));const currentPage=Math.min(page,pages);const visible=filtered.slice((currentPage-1)*pageSize,currentPage*pageSize);
 const counts={all:data.rows.length,active:data.rows.filter(r=>r.status==='active').length,disabled:data.rows.filter(r=>r.status==='disabled').length,pending:data.rows.filter(r=>r.status==='pending').length};
 const staff=data.rows.filter(r=>r.role!=='owner');const activeStaff=staff.filter(r=>r.status==='active').length;const staffCapacity=Math.max(0,data.seatLimit-data.rows.filter(r=>r.role==='owner'&&r.status==='active').length);const manageable=(r:TeamRow)=>canManageTeamMember(data.actorRole,data.actorId,r);const canEditRow=(r:TeamRow)=>data.canEditUsers&&manageable(r);const canDisableRow=(r:TeamRow)=>data.canDisableUsers&&manageable(r);
 async function refresh(show=true){const result=await loadUsersWorkspace(initial.businessId);if(!result.success){setNotice({error:true,text:result.message});return false;}setData(result.data);setSelected(old=>old.filter(x=>result.data.rows.some(r=>r.id===x)));if(show)setNotice({error:false,text:'Users, seats and activity refreshed.'});return true;}
 async function reload(){if(busyRef.current)return;busyRef.current=true;setBusy('refresh');try{await refresh();}catch{setNotice({error:true,text:'Could not refresh Users. Try again.'});}finally{busyRef.current=false;setBusy('');}}
 function change<K extends keyof TeamCreateInput>(field:K,value:TeamCreateInput[K]){setForm(old=>({...old,[field]:value}));}
 function resetForm(){if(pendingCreate)return;setForm({requestId:id(),name:'',email:'',phone:'',role:assignable[0]||'staff',branchId:data.branches[0]?.id||'',password:password(),sendInvite:false,requirePasswordChange:true});setCreateError('');setShowPassword(false);}
 async function create(){
  if(busyRef.current)return;const invalid=createIssue(form,data.actorRole);if(invalid){setCreateError(invalid);setNotice({error:true,text:invalid});return;}
  const payload={...form,sendInvite:false,requirePasswordChange:true};
  try{const {password:_secret,...safe}=payload;sessionStorage.setItem(key,JSON.stringify(safe));}catch{setCreateError('Enable session storage before creating users, so a lost response can be retried safely.');setNotice({error:true,text:'Enable session storage before creating users, so a lost response can be retried safely.'});return;}
  busyRef.current=true;setBusy('create');setCreateError('');
  try{const result=await createTeamUser(initial.businessId,payload);if(!result.success){setPendingCreate(Boolean(result.uncertain));setCreateError(result.message);setNotice({error:true,text:result.message});if(!result.uncertain){sessionStorage.removeItem(key);setForm(old=>({...old,requestId:id()}));}return;}
   setPendingCreate(false);sessionStorage.removeItem(key);setLastTemporaryPassword(payload.password);setForm(old=>({...old,requestId:id(),name:'',email:'',phone:'',password:password(),sendInvite:false,requirePasswordChange:true}));setShowPassword(false);setNotice({error:false,text:result.message+(result.warning?' '+result.warning:'')});await refresh(false);
  }catch{setPendingCreate(true);setCreateError('The result is unconfirmed. Retry this same request; do not create a second account.');setNotice({error:true,text:'The result is unconfirmed. Retry this same request; do not create a second account.'});}finally{busyRef.current=false;setBusy('');}
 }
 function open(which:typeof dialog,row?:TeamRow){setMenu(null);setNotice(null);setDialogError('');setConfirmation('');setDialog(which);if(row){setTarget(row);setEdit({name:row.name,phone:row.phone,role:row.role==='admin'?'manager':row.role,branchId:row.branchId||data.branches[0]?.id||''});}}
 async function mutation(operation:'edit'|'disable'|'enable'|'remove',row=target){
  if(!row||busyRef.current)return;if(operation==='edit'){const issue=editIssue(edit,data.actorRole);if(issue){setDialogError(issue);setNotice({error:true,text:issue});return;}}
  busyRef.current=true;setBusy(operation);setDialogError('');setMenu(null);
  try{const result=await updateTeamUser(initial.businessId,row.id,row.revision,operation,operation==='edit'?edit:operation==='remove'?{confirmation}:{});if(!result.success){setDialogError(result.message);setNotice({error:true,text:result.message});await refresh(false);return;}setDialog(null);setNotice({error:false,text:result.message});await refresh(false);}catch{setDialogError('Result not confirmed. Refresh Users before retrying.');setNotice({error:true,text:'Result not confirmed. Refresh Users before retrying.'});}finally{busyRef.current=false;setBusy('');}
 }
 async function bulkDisable(){
  const rows=data.rows.filter(r=>selected.includes(r.id)&&canDisableRow(r)&&r.status!=='disabled');if(!rows.length)return;
  if(!window.confirm(`Disable business access for ${rows.length} selected users? Accounts with an open register will be kept active.`))return;
  if(busyRef.current)return;busyRef.current=true;setBusy('bulk');let done=0;const failures:string[]=[];
  try{for(const r of rows){const result=await updateTeamUser(initial.businessId,r.id,r.revision,'disable');if(result.success)done++;else failures.push(`${r.name}: ${result.message}`);}setNotice({error:failures.length>0,text:`${done} users disabled.${failures.length?' '+failures.join(' '):''}`});setSelected([]);await refresh(false);}catch{setNotice({error:true,text:`${done} users disabled before the connection stopped. Refresh to see the remaining results.`});}finally{busyRef.current=false;setBusy('');}
 }
 const toggle=(memberId:string)=>setSelected(old=>old.includes(memberId)?old.filter(x=>x!==memberId):[...old,memberId]);
 const viewRows=visible.filter(canDisableRow);const allChecked=viewRows.length>0&&viewRows.every(r=>selected.includes(r.id));
 return <main onInvalidCapture={event=>{const input=event.target as HTMLInputElement;setNotice({error:true,text:input.validationMessage || "Review the required fields."});}} className={s.workspace}>
  <header className={s.pageHeader}><div className={s.pageHeading}><span className={s.pageIcon}><Users size={24}/></span><div><h1>User &amp; Manage User</h1><p>Create workspace users, assign one branch, and control role permissions.</p></div></div><div className={s.headerButtons}><button className={s.button} onClick={()=>open('activity')}><Activity size={15}/>Activity Log</button>{data.canManageRolePermissions&&<button className={s.button} onClick={()=>open('permissions')}><ShieldCheck size={15}/>Manage Permissions</button>}</div></header>
  <div className={s.metrics}>
   <Metric icon={<UserCheck size={22}/>} tone="green" label="Active Staff" value={`${activeStaff} / ${staffCapacity}`} note={`${Math.max(0,data.seatLimit-data.seatsUsed)} seats available · pending setups use seats`}/>
   <Metric icon={<UserMinus size={22}/>} tone="red" label="Disabled Users" value={String(counts.disabled)} note="Cannot access this business"/>
   <Metric icon={<Users size={22}/>} tone="blue" label="Total Users" value={String(counts.all)} note="Including the business owner"/>
   <Metric icon={<KeyRound size={22}/>} tone="orange" label="Password Setup" value={String(counts.pending)} note="Must change temporary password"/>
  </div>
  {notice&&!dialog&&<div className={`${s.notice} ${notice.error?s.error:s.success}`} role={notice.error?'alert':'status'}><span>{notice.text}</span><button type="button" className={s.iconButton} aria-label="Dismiss message" onClick={()=>setNotice(null)}><X size={16}/></button></div>}
  <div className={s.workspaceGrid}>
   <section className={`${s.card} ${s.createCard}`}><div className={s.sectionHeading}><span className={s.primaryIcon}><Plus size={20}/></span><div><h2>Create New User</h2><p>Create a direct login for this workspace</p></div></div>
    {data.lockReason&&<div className={s.planNotice}>{data.lockReason} {data.actorRole==='owner'&&<Link href="/dashboard/settings/subscription?view=plans">Manage plan →</Link>}</div>}
    {!data.canCreateUsers&&<div className={s.planNotice}>Your role does not have permission to create workspace users.</div>}
    {data.reservedSeats>0&&<p className={s.hint}>{data.reservedSeats} creation request(s) temporarily reserve seats. Unfinished reservations expire after 15 minutes.</p>}
    <form onSubmit={e=>{e.preventDefault();void create();}} className={s.createForm}>
     {createError&&<div className={`${s.notice} ${s.error}`} role="alert">{createError}</div>}
     <fieldset disabled={Boolean(busy)||pendingCreate||!data.canCreate||!data.canCreateUsers}>
      <label className={s.field}>Full name <em>*</em><input aria-label="Full name" value={form.name} onChange={e=>change('name',e.target.value)} required minLength={2} maxLength={120} placeholder="Enter full name" autoComplete="off"/></label>
      <label className={s.field}>Email address <em>*</em><input aria-label="Email address" type="email" value={form.email} onChange={e=>change('email',e.target.value)} required maxLength={254} placeholder="user@example.com" autoComplete="off"/></label>
      <label className={s.field}>Phone number <span className={s.optional}>(optional)</span><input aria-label="Phone number" type="tel" value={form.phone} onChange={e=>change('phone',e.target.value)} maxLength={40} placeholder="e.g. 012 345 678"/></label>
      <label className={s.field}>Password<select aria-label="Password mode" value={generated?'generated':'manual'} onChange={e=>{const next=e.target.value==='generated';setGenerated(next);change('password',next?password():'');}}><option value="generated">Generate temporary password</option><option value="manual">Enter temporary password</option></select></label>
      <div className={s.field}><label htmlFor="team-password">Temporary password <em>*</em></label><div className={s.passwordField}><input id="team-password" aria-label="Temporary password" type={showPassword?'text':'password'} value={form.password} readOnly={generated} autoComplete="new-password" minLength={12} maxLength={128} required onChange={e=>change('password',e.target.value)}/><button type="button" aria-label="Show or hide password" className={s.iconButton} onClick={()=>setShowPassword(!showPassword)}>{showPassword?<EyeOff size={16}/>:<Eye size={16}/>}</button></div>{generated&&<button type="button" className={s.textButton} onClick={()=>change('password',password())}>Generate another password</button>}<small>No confirmation email is sent. Share this temporary password securely; the user must replace it on first sign in.</small></div>
      <label className={s.field}>Role <em>*</em><select aria-label="New user role" value={form.role} onChange={e=>change('role',e.target.value as BusinessRole)} required>{assignable.map(x=><option key={x} value={x}>{TEAM_ROLE_LABELS[x]}</option>)}</select></label>
      <label className={s.field}>Assigned branch <em>*</em><select aria-label="Assigned branch" value={form.branchId} onChange={e=>change('branchId',e.target.value)} required><option value="" disabled>Select branch</option>{data.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><small>This user can fetch and operate only this branch. Owner keeps access to all active branches.</small></label>
      <div className={s.field}><label>Permissions</label><button type="button" className={s.defaults} onClick={()=>open('permissions')}>Manage role permissions <ShieldCheck size={14}/></button><small>{TEAM_ROLE_LABELS[form.role]} currently has {data.effectiveRolePermissions[form.role]?.length ?? 0} enabled permissions.</small></div>
      <div className={s.planNotice}><strong>First-login security:</strong> this account is created directly without email confirmation. Workspace access stays pending until the temporary password is changed.</div>
     </fieldset>
     <div className={s.formActions}><button type="button" className={s.button} disabled={Boolean(busy)||pendingCreate} onClick={resetForm}>Clear</button><button className={s.primary} disabled={Boolean(busy)||!data.canCreateUsers||(!data.canCreate&&!pendingCreate)||!form.requestId}>{busy==='create'?<RefreshCw className={s.spin} size={16}/>:<Plus size={16}/>} {pendingCreate?'Retry same request':'Create User'}</button></div>
     {lastTemporaryPassword&&<div className={s.planNotice}><strong>Copy the temporary password now:</strong><div className={s.passwordField}><input readOnly value={lastTemporaryPassword} aria-label="Last created temporary password"/><button type="button" className={s.iconButton} aria-label="Copy temporary password" onClick={()=>void navigator.clipboard.writeText(lastTemporaryPassword).catch(()=>setNotice({error:true,text:'Could not copy the password. Select and copy it manually.'}))}><Copy size={15}/></button></div><small>This is kept only in this open page and is not sent by email.</small></div>}{pendingCreate&&<p className={s.hint}>The form is locked to the original request to prevent duplicates. Refresh User &amp; Manage User or retry. The temporary password is not stored in session storage.</p>}
    </form>
   </section>
   <div className={s.rightColumn}>
    <section className={`${s.card} ${s.tableCard}`}>
     <div className={s.toolbar}><div className={s.tabs} role="tablist" aria-label="User status">{(['all','active','disabled','pending'] as const).map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?s.activeTab:''} onClick={()=>setTab(t)}>{t==='all'?'All Users':t==='pending'?'Pending':t[0].toUpperCase()+t.slice(1)} <span>({counts[t]})</span></button>)}</div><div className={s.tools}><div className={s.search}><Search size={15}/><input ref={searchRef} aria-label="Search users" placeholder="Search users, email, or role…" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className={s.button} onClick={()=>setFilters(!filters)} aria-expanded={filters}><Filter size={14}/>Filter</button><button className={s.iconButton} onClick={()=>void reload()} disabled={Boolean(busy)} aria-label="Refresh users"><RefreshCw size={15} className={busy==='refresh'?s.spin:''}/></button></div></div>
     {filters&&<div className={s.filterBar}><label>Role<select aria-label="Filter by role" value={role} onChange={e=>setRole(e.target.value)}><option value="all">All roles</option>{Object.entries(TEAM_ROLE_LABELS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Branch<select aria-label="Filter by branch" value={branch} onChange={e=>setBranch(e.target.value)}><option value="all">All branches</option><option value="owner">Owner · all branches</option>{data.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Sort<select aria-label="Sort users" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="name">Name A–Z</option><option value="lastActive">Last signed in</option></select></label><button className={s.textButton} onClick={()=>{setRole('all');setBranch('all');setSort('newest');setQuery('');}}>Reset filters</button></div>}
     {selected.length>0&&<div className={s.selectionBar}><strong>{selected.length} selected</strong><button className={s.textButton} disabled={Boolean(busy)} onClick={()=>void bulkDisable()}>Disable selected</button><button className={s.textButton} onClick={()=>setSelected([])}>Clear selection</button></div>}
     <div className={s.tableScroll}><table><thead><tr><th><input type="checkbox" aria-label="Select manageable users on this page" checked={allChecked} disabled={!viewRows.length||Boolean(busy)} onChange={()=>setSelected(old=>allChecked?old.filter(x=>!viewRows.some(r=>r.id===x)):Array.from(new Set([...old,...viewRows.map(r=>r.id)])))}/></th><th>User</th><th>Role</th><th>Branch</th><th>Status</th><th>Last signed in</th><th>Created</th><th><span className={s.srOnly}>Actions</span></th></tr></thead><tbody>{visible.map(r=><tr key={r.id} data-selected={selected.includes(r.id)}><td><input type="checkbox" aria-label={`Select ${r.name}`} checked={selected.includes(r.id)} disabled={!canDisableRow(r)||Boolean(busy)} onChange={()=>toggle(r.id)}/></td><td><button className={s.userCell} onClick={()=>open('view',r)}><span className={s.avatar} data-role={r.role}>{r.name.trim().slice(0,1).toUpperCase()}</span><span><strong>{r.name}{r.role==='owner'&&<Crown size={13} className={s.ownerCrown}/>}</strong><small>{r.email}</small></span></button></td><td><span className={s.roleBadge} data-role={r.role}>{TEAM_ROLE_LABELS[r.role]||r.role}</span></td><td className={s.branchText}>{r.role==='owner'?'All branches':data.branches.find(b=>b.id===r.branchId)?.name||'Unassigned'}{r.role!=='owner'&&<small>Assigned branch only</small>}</td><td><span className={s.status} data-status={r.status}><i/>{statusLabel(r)}</span></td><td className={s.dateCell}>{date(r.lastActive)}</td><td className={s.dateCell}>{date(r.createdAt)}</td><td><div className={s.menuRoot} ref={menu===r.id?menuRef:undefined}><button className={s.moreButton} aria-label={`Actions for ${r.name}`} aria-expanded={menu===r.id} onClick={e=>{const box=e.currentTarget.getBoundingClientRect();setMenuPosition({top:Math.max(8,Math.min(window.innerHeight-236,box.bottom+5)),left:Math.max(8,box.right-185)});setMenu(menu===r.id?null:r.id);}} disabled={Boolean(busy)}><MoreHorizontal size={17}/></button>{menu===r.id&&<div className={s.menu} style={menuPosition}><button onClick={()=>open('view',r)}><Eye size={14}/>View details</button>{canEditRow(r)&&<button onClick={()=>open('edit',r)}><UserRound size={14}/>Edit user</button>}{canDisableRow(r)&&<><button onClick={()=>open(r.status==='disabled'?'enable':'disable',r)}><UserMinus size={14}/>{r.status==='disabled'?'Enable access':'Disable access'}</button>{data.actorRole==='owner'&&<button className={s.danger} onClick={()=>open('remove',r)}><Trash2 size={14}/>Delete user</button>}</>}</div>}</div></td></tr>)}</tbody></table></div>
     {!filtered.length&&<div className={s.empty}><Users size={30}/><h3>No matching users</h3><p>Try another search or clear the filters.</p><button className={s.button} onClick={()=>{setQuery('');setTab('all');setRole('all');setBranch('all');}}>Clear filters</button></div>}
     <footer className={s.tableFooter}><span>{filtered.length?`${(currentPage-1)*pageSize+1}–${Math.min(currentPage*pageSize,filtered.length)}`:'0'} of {filtered.length} users</span><div><button className={s.iconButton} aria-label="Previous page" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={16}/></button><strong>{currentPage} / {pages}</strong><button className={s.iconButton} aria-label="Next page" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}><ChevronRight size={16}/></button><select aria-label="Users per page" value={pageSize} onChange={e=>setPageSize(Number(e.target.value))}>{[10,15,25,50].map(n=><option key={n} value={n}>{n} / page</option>)}</select></div></footer>
    </section>
    <div className={s.bottomGrid}><section className={s.card}><div className={s.sectionHeading}><div><h2>Role Overview</h2><p>Understand each role’s permissions</p></div>{data.canManageRolePermissions&&<button className={s.button} onClick={()=>open('permissions')}><ShieldCheck size={14}/>Manage permissions</button>}</div><div className={s.roleList}>{(['owner','manager','staff','cashier'] as BusinessRole[]).map(r=><button key={r} className={s.roleItem} onClick={()=>{setRole(r);setFilters(true);setTab('all');}}><span className={s.roleSquare} data-role={r}>{r==='owner'?<Crown size={17}/>:<ShieldCheck size={17}/>}</span><span><strong>{TEAM_ROLE_LABELS[r]}</strong><small>{TEAM_ROLE_NOTES[r]}</small></span><small>{data.rows.filter(x=>x.role===r).length} users</small></button>)}</div>{data.rows.some(r=>r.role==='admin')&&<p className={s.hint}>Existing admin accounts keep their legacy permissions; only the owner can manage them.</p>}</section><section className={s.card} ref={activityRef}><div className={s.sectionHeading}><div><h2>Recent Activity</h2><p>Recorded team-management events</p></div><button className={s.textButton} onClick={()=>open('activity')}>View all</button></div><ActivityList rows={data.activities.slice(0,5)}/></section></div>
   </div>
  </div>
  {dialog&&<Modal title={dialog==='permissions'?'Role Permissions':dialog==='activity'?'Team Activity Log':dialog==='view'?'User details':dialog==='edit'?'Edit user':dialog==='remove'?'Delete user?':dialog==='enable'?'Enable business access?':'Disable business access?'} onClose={()=>setDialog(null)} locked={Boolean(busy)} wide={dialog==='permissions'||dialog==='activity'}>
   {notice&&<div className={`${s.notice} ${notice.error?s.error:s.success}`} role={notice.error?'alert':'status'}><span>{notice.text}</span><button type="button" className={s.iconButton} aria-label="Dismiss message" onClick={()=>setNotice(null)}><X size={16}/></button></div>}
   {dialogError&&<p className={s.error} role="alert">{dialogError}</p>}
   {dialog==='permissions'&&<RolePermissionsEditor onMemberChange={(memberId,revision)=>setData(current=>({...current,rows:current.rows.map(row=>row.id===memberId?{...row,revision}:row)}))} users={data.rows} businessId={data.businessId} actorRole={data.actorRole} matrix={data.effectiveRolePermissions} onChange={(changedRole:EditablePermissionRole,next:Permission[])=>setData(current=>({...current,effectiveRolePermissions:{...current.effectiveRolePermissions,[changedRole]:next}}))}/>}
   {dialog==='activity'&&<ActivityList rows={data.activities}/>}
   {dialog==='view'&&target&&<div className={s.detail}><span className={s.avatar} data-role={target.role}>{target.name[0]}</span><h3>{target.name}</h3><dl><dt>Email</dt><dd>{target.email}</dd><dt>Phone</dt><dd>{target.phone||'Not provided'}</dd><dt>Role</dt><dd>{TEAM_ROLE_LABELS[target.role]}</dd><dt>Status</dt><dd>{statusLabel(target)}</dd><dt>Assigned branch</dt><dd>{target.role==='owner'?'All branches':data.branches.find(b=>b.id===target.branchId)?.name||'Unassigned'}</dd><dt>Last signed in</dt><dd>{date(target.lastActive)}</dd><dt>Created</dt><dd>{date(target.createdAt)}</dd></dl><p className={s.hint}>Last signed in is an account sign-in timestamp, not an online-presence indicator.</p>{canEditRow(target)&&<button className={s.primary} onClick={()=>open('edit',target)}>Edit user</button>}</div>}
   {dialog==='edit'&&target&&<form className={s.editForm} onSubmit={e=>{e.preventDefault();void mutation('edit');}}><fieldset disabled={Boolean(busy)}><label className={s.field}>Full name<input required minLength={2} maxLength={120} value={edit.name} onChange={e=>setEdit(x=>({...x,name:e.target.value}))}/></label><label className={s.field}>Login email<input readOnly value={target.email}/><small>Email changes are managed by the account owner, not silently replaced here.</small></label><label className={s.field}>Phone<input type="tel" value={edit.phone} maxLength={40} onChange={e=>setEdit(x=>({...x,phone:e.target.value}))}/></label><label className={s.field}>Role<select value={edit.role} onChange={e=>setEdit(x=>({...x,role:e.target.value as BusinessRole}))}>{assignable.map(r=><option key={r} value={r}>{TEAM_ROLE_LABELS[r]}</option>)}</select></label><label className={s.field}>Assigned branch<select value={edit.branchId} onChange={e=>setEdit(x=>({...x,branchId:e.target.value}))}><option value="" disabled>Choose branch</option>{data.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><p className={s.hint}>This user can fetch and operate only the assigned branch. Close their register before changing role or branch.</p></fieldset><div className={s.formActions}><button className={s.button} type="button" disabled={Boolean(busy)} onClick={()=>setDialog(null)}>Cancel</button><button className={s.primary} disabled={Boolean(busy)}>{busy?'Saving…':'Save changes'}</button></div></form>}
   {['disable','enable','remove'].includes(dialog)&&target&&<div className={s.stack}><p><strong>{target.name}</strong> · {target.email}</p><p>{dialog==='remove'?'This permanently deletes the login account and user profile. Existing business records are kept; record ownership is transferred to the business Owner. Accounts belonging to another business cannot be deleted here.':dialog==='enable'?'Access is restored only within the current plan allowance. A user still awaiting password setup remains pending.':'This user will lose access to this business. Existing sales and account history are kept.'}</p>{dialog==='remove'&&<label className={s.field}>Type DELETE to confirm<input aria-label="Deletion confirmation" value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off"/></label>}<div className={s.formActions}><button className={s.button} disabled={Boolean(busy)} onClick={()=>setDialog(null)}>Cancel</button><button className={dialog==='enable'?s.primary:s.dangerButton} disabled={Boolean(busy)||(dialog==='remove'&&confirmation!=='DELETE')} onClick={()=>void mutation(dialog as 'disable'|'enable'|'remove')}>{busy?'Saving…':dialog==='remove'?'Delete user':dialog==='enable'?'Enable access':'Disable access'}</button></div></div>}
  </Modal>}
 </main>;
}
function Metric({icon,tone,label,value,note}:{icon:ReactNode;tone:string;label:string;value:string;note:string}){return <section className={s.metric}><span data-tone={tone} className={s.metricIcon}>{icon}</span><div><p>{label}</p><strong>{value}</strong><small>{note}</small></div></section>;}
function ActivityList({rows}:{rows:TeamWorkspace['activities']}){return <div className={s.activityList}>{rows.length?rows.map(a=><div key={a.id} className={s.activityItem}><span data-action={a.action}><Activity size={15}/></span><div><strong>{a.description}</strong><small>{a.actor} · {date(a.createdAt)}</small></div></div>):<div className={s.emptySmall}><Activity size={24}/><p>No recorded team activity yet.</p></div>}</div>;}
