import Link from "next/link";
import { AlertTriangle, Boxes, CupSoda, Package, Shirt, ShoppingBag } from "lucide-react";
import { getCurrentBusiness } from "@/lib/business/get-current-business";
import { createClient } from "@/lib/supabase/server";

type Stock={id:string;name:string;stock_quantity:number;low_stock_quantity:number;cost_price:number;size:string|null;color:string|null;variant_group_id:string|null};
type Order={id:string;total:number;status:string};
type Line={product_name:string|null;quantity:number;variant_label:string|null;selected_options:any;orders:{status:string;business_id:string}|{status:string;business_id:string}[]|null};
export default async function DashboardPage(){const business=await getCurrentBusiness(); const s=await createClient(); const today=new Date(); today.setHours(0,0,0,0); const [{data:sf},{data:stocks},{data:orders},{data:lines}]=await Promise.all([
 s.from("business_storefronts").select("business_type,currency").eq("business_id",business.id).maybeSingle(),
 s.from("products").select("id,name,stock_quantity,low_stock_quantity,cost_price,size,color,variant_group_id").eq("business_id",business.id).eq("is_active",true),
 s.from("orders").select("id,total,status").eq("business_id",business.id).eq("status","completed").gte("created_at",today.toISOString()),
 s.from("order_items").select("product_name,quantity,variant_label,selected_options,orders!inner(status,business_id)").eq("orders.business_id",business.id).eq("orders.status","completed").limit(1000)
 ]); const stock=(stocks??[]) as Stock[], sales=(orders??[]) as Order[], li=(lines??[]) as unknown as Line[]; const low=stock.filter(p=>Number(p.stock_quantity)<=Number(p.low_stock_quantity)); const valuation=stock.reduce((a,p)=>a+Number(p.stock_quantity)*Number(p.cost_price),0); const revenue=sales.reduce((a,o)=>a+Number(o.total),0); const type=sf?.business_type??"general"; const currency=sf?.currency??"USD";
 const topProducts=countBy(li,l=>l.product_name||"Product"); const topSizes=countBy(li,l=>extractSize(l)); const topColors=countBy(li,l=>extractColor(l)); const toppings=countBy(li,l=>extractOptionValues(l,"topping"));
 return <main><div className="mb-7"><h1 className="text-3xl font-bold text-slate-900">{dashboardTitle(type)}</h1><p className="mt-1 text-slate-500">{business.name} · {formatType(type)}</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card title="Today's sales" value={money(revenue,currency)} icon={ShoppingBag}/><Card title="Completed orders" value={sales.length} icon={Package}/><Link href="/dashboard/low-stock" className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex justify-between"><div><p className="text-sm text-amber-700">Low stock</p><p className="mt-2 text-3xl font-bold text-amber-900">{low.length}</p></div><AlertTriangle className="text-amber-600"/></div></Link><Card title="Inventory value" value={money(valuation,currency)} icon={Boxes}/></div>
 <div className="mt-6 grid gap-6 xl:grid-cols-3"><Insight title={type==="milk_tea"?"Popular drinks":"Best sellers"} rows={topProducts.slice(0,6)}/>{type==="milk_tea"?<Insight title="Popular toppings" rows={toppings.slice(0,6)} icon={CupSoda}/>:type==="shoes"||type==="fashion"?<Insight title="Best sizes" rows={topSizes.slice(0,6)} icon={Shirt}/>:<Insight title="Stock alerts" rows={low.slice(0,6).map(p=>({label:p.name,value:p.stock_quantity}))}/>} {type==="shoes"||type==="fashion"?<Insight title="Popular colours" rows={topColors.slice(0,6)}/>:<Insight title="Quick actions" rows={[{label:"New sale",value:"POS"},{label:"Receive stock",value:"PO"},{label:"Print labels",value:"Barcode"}]}/>}</div></main>}
function countBy(lines:Line[],pick:(l:Line)=>string|string[]|null){const m=new Map<string,number>(); for(const l of lines){const vals=pick(l); for(const v of (Array.isArray(vals)?vals:[vals]).filter(Boolean) as string[])m.set(v,(m.get(v)||0)+Number(l.quantity||0));} return [...m].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value)}
function extractSize(l:Line){const x=(l.variant_label||"").match(/(?:Size|EU)\s*([^·/]+)/i); return x?.[1]?.trim()||null} function extractColor(l:Line){const v=(l.variant_label||"").split(/[·/]/)[0]?.trim(); return v||null} function extractOptionValues(l:Line,key:string){return Array.isArray(l.selected_options)?l.selected_options.filter((o:any)=>String(o.groupName||"").toLowerCase().includes(key)).map((o:any)=>String(o.name||"")).filter(Boolean):[]}
function dashboardTitle(t:string){if(t==="milk_tea")return "Milk Tea Dashboard"; if(t==="shoes")return "Shoes Dashboard"; if(t==="fashion")return "Fashion Dashboard"; return "Business Dashboard"} function formatType(t:string){return t.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())} function money(v:number,c:string){try{return new Intl.NumberFormat("en-US",{style:"currency",currency:c}).format(v)}catch{return `$${v.toFixed(2)}`}}
function Card({title,value,icon:Icon}:{title:string;value:string|number;icon:any}){return <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><div><p className="text-sm text-slate-500">{title}</p><p className="mt-2 text-2xl font-bold">{value}</p></div><Icon className="text-blue-600"/></div></div>}
function Insight({title,rows,icon:Icon=Package}:{title:string;rows:{label:string;value:number|string}[];icon?:any}){return <section className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-2"><Icon size={18} className="text-blue-600"/><h2 className="font-semibold">{title}</h2></div><div className="mt-4 space-y-3">{rows.length?rows.map((r,i)=><div key={`${r.label}-${i}`} className="flex items-center justify-between gap-3"><span className="truncate text-sm text-slate-700">{r.label}</span><span className="rounded-lg bg-slate-100 px-2 py-1 text-xs font-bold">{r.value}</span></div>):<p className="text-sm text-slate-400">No data yet</p>}</div></section>}
