import { Medal } from "lucide-react";
const colors=["#12658b","#f5c64f","#2db7d7","#ef4760","#6bc6a4","#8b5cf6","#f97316","#64748b"];
export function DonutBreakdown({rows,currency="USD",count=false}:{rows:{label:string;value:number}[];currency?:string;count?:boolean}){
 const data=rows.filter(r=>Number.isFinite(r.value)&&r.value>0);const total=data.reduce((n,r)=>n+r.value,0);let angle=0;
 const format=(n:number)=>count?new Intl.NumberFormat("en-US").format(n):new Intl.NumberFormat("en-US",{style:"currency",currency,maximumFractionDigits:2}).format(n);
 const stops=data.map((r,i)=>{const start=angle;angle+=r.value/total*360;return `${colors[i%colors.length]} ${start}deg ${angle}deg`;}).join(",");
 return <div className="grid items-center gap-5 py-3 sm:grid-cols-[160px_minmax(0,1fr)]"><div role="img" aria-label={`Total ${format(total)}. ${data.map(r=>`${r.label}: ${format(r.value)}`).join('. ')}`} className="mx-auto flex h-40 w-40 items-center justify-center rounded-full" style={{background:total?`conic-gradient(${stops})`:"#e2e8f0"}}><div className="flex h-28 w-28 flex-col items-center justify-center rounded-full bg-white px-2 text-center dark:bg-slate-900"><strong className="max-w-full break-all text-base text-slate-900 dark:text-white">{format(total)}</strong><span className="mt-1 text-xs text-slate-500">{count?"Orders":"Total"}</span></div></div><div className="space-y-3">{data.length?data.map((r,i)=><div key={`${r.label}-${i}`} className="flex items-center gap-2 text-xs" title={`${r.label}: ${format(r.value)} (${(r.value/total*100).toFixed(1)}%)`}><span className="h-2.5 w-2.5 shrink-0 rounded-full" style={{background:colors[i%colors.length]}}/><span className="min-w-0 flex-1 text-slate-600 dark:text-slate-300">{r.label}</span><span className="text-slate-400">{(r.value/total*100).toFixed(1)}%</span><strong className="text-right text-slate-900 dark:text-white">{format(r.value)}</strong></div>):<p className="text-sm text-slate-500">No sales in this period.</p>}</div></div>;
}
export function ProductRankBars({rows}:{rows:{label:string;value:number}[]}){
 const ranked=[...rows].filter(r=>r.value>0).sort((a,b)=>b.value-a.value).slice(0,10);const max=ranked[0]?.value||1;
 return <div className="space-y-4">{ranked.length?ranked.map((r,i)=><div key={`${r.label}-${i}`} className="flex items-center gap-3"><span className="flex w-7 shrink-0 justify-center" aria-label={i<3?`${['Gold','Silver','Bronze'][i]} medal, rank ${i+1}`:`Rank ${i+1}`}>{i<3?<Medal size={26} strokeWidth={1.8} color={["#b78200","#748397","#a66536"][i]} fill={["#ffe08a","#e2e8f0","#e6b994"][i]}/>:<span className="text-xs font-semibold text-slate-400">{i+1}</span>}</span><div className="min-w-0 flex-1"><p className="mb-1.5 truncate text-xs font-semibold text-slate-700 dark:text-slate-200" title={r.label}>{r.label}</p><div className="flex items-center gap-2"><div className="h-6 min-w-0 flex-1 rounded bg-slate-50 dark:bg-slate-800"><div role="img" aria-label={`${r.label}: ${r.value} sold`} className="h-full rounded-sm shadow-sm" style={{width:`${r.value/max*100}%`,background:colors[i%colors.length]}}/></div><strong className="w-12 text-right text-xs text-slate-700 dark:text-slate-200">{r.value}</strong></div></div></div>):<p className="py-8 text-center text-sm text-slate-500">No product sales in this period.</p>}</div>;
}
