import {Ionicons} from '@expo/vector-icons';
import React, {useRef,useState} from 'react';
import {Modal,Pressable,ScrollView,Switch,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {api,type Scope} from './client';
import {ActionArea,Button,Card,Field,Label,styles,useTheme} from './ui';
export function CategoryForm({category,scope,online,close,saved}:{category?:{id:string;name:string;description?:unknown;is_online?:unknown};scope:Scope;online:boolean;close:()=>void;saved:()=>void}){
 const theme=useTheme(),[name,setName]=useState(category?.name||''),[description,setDescription]=useState(String(category?.description||'')),[isOnline,setOnline]=useState(category?.is_online===true),[busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false);
 async function save(){if(lock.current||!online)return;if(name.trim().length<2||name.trim().length>50){setError('Enter a category name of 2–50 characters.');return;}lock.current=true;setBusy(true);setError('');try{await api('account-categories',scope,{action:category?'edit':'create',id:category?.id,name:name.trim(),description,isOnline});saved();}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 return <Modal visible animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>{if(!busy)close();}}><ActionArea><SafeAreaView style={{flex:1,backgroundColor:theme.background}}>
  <ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled"><View style={[styles.row,{gap:14,marginBottom:12}]}><Pressable accessibilityRole="button" accessibilityLabel="Cancel editing category" disabled={busy} onPress={close} style={{padding:12,borderRadius:26,backgroundColor:theme.panel}}><Ionicons name="arrow-back" size={24} color={theme.text}/></Pressable><View style={{flex:1,gap:4}}><Label large>{category?'Edit category':'Add category'}</Label><Label muted>{category?'Update your category details':'Create a category for your products'}</Label></View></View>
  <Card><Field label="Name *" placeholder="Enter category name" value={name} onChangeText={setName} editable={!busy} maxLength={50}/><Label muted>This name will be shown to your customers.</Label><View style={{height:4}}/><Field label="Description" placeholder="Category description" value={description} onChangeText={setDescription} editable={!busy} maxLength={200} multiline style={{minHeight:88,textAlignVertical:'top'}}/><Label muted>A short description about this category (optional).</Label>
   <View style={{borderTopWidth:1,borderColor:theme.border,paddingTop:20,marginTop:8}}><View style={[styles.row,{padding:14,borderRadius:16,backgroundColor:theme.dark?'#17332d':'#eff8f4'}]}><Ionicons name="storefront-outline" size={26} color="#178963"/><View style={{flex:1,gap:4}}><Label>Show on Online Store</Label><Label muted>Make this category visible to customers on your online store.</Label></View><Switch accessibilityLabel="Show on Online Store" trackColor={{true:'#138568'}} value={isOnline} onValueChange={setOnline} disabled={busy}/></View></View>
  </Card>{!category&&<Label muted>Applies to the current branch.</Label>}{!!error&&<Label>{error}</Label>}
  </ScrollView><View style={{padding:18,gap:10,borderTopWidth:1,borderColor:theme.border,backgroundColor:theme.panel}}><Button title="Save" busy={busy} disabled={!online||!name.trim()} onPress={()=>void save()}/><Button title="Cancel" secondary disabled={busy} onPress={close}/></View>
 </SafeAreaView></ActionArea></Modal>;
}
