import {compareVariants} from './variant-selection';
import {useInfiniteScroll} from './infinite-scroll';
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Image, Linking, Modal, Pressable, ScrollView, Switch, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import * as Crypto from 'expo-crypto';
import { Ionicons } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import { api, apiUrl, ApiError, deviceStorage, money, type Scope, type Workspace } from './client';
import { FloatingAdd, DetailRow, Metric, SectionTitle, Badge, ProductPhoto, Button, Card, Field, Label, styles, useTheme } from './ui';
import { ChoiceChip, LayoutPicker, SelectMenu } from './list-controls';
import {useViewPreference} from './view-preference';
import { matchingVariants } from './variant-selection';
import { groupProducts } from './product-groups';
import { ProductPanel } from './product-panel';
import { clearCache, useData, useInfiniteData } from './data';
import { UploadProgress, Shimmer } from './loading';

type Product = { id:string; variant_group_id?:string|null; name:string; sku:string; barcode:string|null; description:string|null; category_id:string|null; image_url:string|null; cost_price:number; selling_price:number; low_stock_quantity:number; stock_quantity:number; product_type:string; size:string|null; color:string|null; is_active:boolean; is_pos:boolean; is_online:boolean; updated_at:string|null; items?:{component_product_id:string;name?:string;quantity:number;selected_options?:{id?:string;optionId?:string}[]}[] };
type Variant={sku:string;barcode:string;price:string;cost:string;lowStock:string;size:string;color:string};
type Line={productId:string;name:string;quantity:string;cost:string;optionIds:string[];imageUrl?:string|null;variant?:string};
type Group={name:string;required:boolean;options:{name:string;price:string}[]};
type ImageAsset={uri:string;name:string;type:string};
type Pending={requestId:string;operation:string;input:Record<string,unknown>;image:ImageAsset|null};
const blankRow=():Variant=>({sku:'',barcode:'',price:'0',cost:'0',lowStock:'5',size:'',color:''});
export function appendSizeRun(rows: Variant[], sizes: string[]): Variant[] {
 const base=rows[0]||blankRow();
 const kept=rows.length===1&&!base.size.trim()?[]:rows;
 const added=[...new Set(sizes)].filter(size=>!kept.some(row=>row.size===size&&row.color===base.color)).map(size=>({...base,size,sku:base.sku?`${base.sku}-${size}`:'',barcode:''}));
 if(kept.length+added.length>40)throw new Error('A product can have up to 40 variants.');
 return [...kept,...added];
}
export function Toggle({label,value,change,disabled=false}:{label:string;value:boolean;change:(value:boolean)=>void;disabled?:boolean}) {
  return <View style={[styles.row,{justifyContent:'space-between'}]}><View style={{flex:1}}><Label>{label}</Label></View><Switch accessibilityLabel={label} value={value} onValueChange={change} disabled={disabled}/></View>;
}

export function Management({workspace,online,feature,search=''}:{search?:string;workspace:Workspace;online:boolean;feature:'Products'|'Bundles'|'Online Store'}) {
 const theme=useTheme();const scope={userId:workspace.userId,businessId:workspace.business.id,branchId:workspace.branchId};
 const [query,setQuery]=useState(''),[selected,setSelected]=useState<Product|null>(null),[form,setForm]=useState<string|null>(null);
 const [family,setFamily]=useState<Product[]>([]),[category,setCategory]=useState('');
 const {value:columns,change:setColumns,error:viewError}=useViewPreference(scope,feature);
 const categoryOptions=useData<{categories:{id:string;name:string}[];mode:string}>('catalog-options',scope,online&&feature!=='Online Store');
 useEffect(()=>{const timer=setTimeout(()=>{setQuery(search);},300);return()=>clearTimeout(timer);},[search]);
 const {data,loading,error,refresh,more}=useInfiniteData<{rows:Product[];total:number;currency:string}>(`catalog?grouped=true&category=${category}&bundles=${feature==='Bundles'}&search=${encodeURIComponent(query)}`,scope,online&&feature!=='Online Store');
 const scrolling=useInfiniteScroll(more);
 const productFamilies=useMemo(()=>groupProducts(data?.rows??[]),[data?.rows]);
 const details=useData<Product>(`catalog-detail?id=${selected?.id||''}`,scope,online&&!!selected&&!form);
 const detail=details.data||selected;
 if(feature==='Online Store')return <ManagementForm operation="storefront-save" scope={scope} online={online} workspace={workspace} close={()=>{}} saved={()=>clearCache()} embedded/>;
 return <View style={{flex:1}}><ScrollView {...scrolling} contentContainerStyle={[styles.page,{paddingBottom:92}]} keyboardShouldPersistTaps="handled">
  {viewError&&<Label>{viewError}</Label>}
  <View style={[styles.row,{justifyContent:'space-between'}]}><View style={{flex:1,minWidth:0}}><SelectMenu label="Category" value={category} options={[{value:'',label:'All categories'},...(categoryOptions.data?.categories??[]).map(row=>({value:row.id,label:row.name}))]} change={value=>{setCategory(value);}}/></View><LayoutPicker value={columns} change={value=>{setColumns(value);}}/></View>{data&&<View style={{alignItems:'flex-end'}}><Badge title={`${data.total} ${feature==='Bundles'?'bundles':'products'}`}/></View>}
  {loading&&!data&&<Shimmer rows={3}/>}{error&&<Card><Label>{error}</Label><Button title="Retry" onPress={refresh} disabled={!online}/></Card>}
  <View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}>{productFamilies.map(rows=>{const product=rows[0],stock=rows.reduce((sum,row)=>sum+Number(row.stock_quantity),0);if(columns===1)return <Pressable key={product.variant_group_id||product.id} accessibilityRole="button" onPress={()=>rows.length>1?setFamily(rows):setSelected(product)} style={{width:'100%',flexDirection:'row',alignItems:'center',gap:12,padding:12,borderRadius:14,backgroundColor:theme.panel,borderWidth:1,borderColor:theme.border}}><ProductPhoto uri={product.image_url} size={52}/><View style={{flex:1}}><Label>{product.name}</Label><Label muted>{rows.length>1?`${rows.length} variants`:product.sku}</Label></View><View style={{alignItems:'flex-end'}}><Label>{money(Math.min(...rows.map(row=>row.selling_price)),data?.currency)}</Label><Label muted>{`${stock} in stock`}</Label></View></Pressable>;return <Pressable key={product.variant_group_id||product.id} accessibilityRole="button" onPress={()=>rows.length>1?setFamily(rows):setSelected(product)} style={({pressed})=>({width:columns===1?'100%':columns===2?'48%':'31%',padding:10,gap:8,borderRadius:18,borderWidth:1,borderColor:theme.border,backgroundColor:theme.panel,opacity:pressed?0.7:1})}><ProductPhoto uri={product.image_url} fill/><Label>{product.name}</Label><Label muted>{rows.length>1?`${rows.length} variants`:product.sku}</Label><Label>{money(Math.min(...rows.map(row=>row.selling_price)),data?.currency)}</Label><Badge title={rows.some(row=>row.is_active)?`${stock} in stock`:'Inactive'} positive={rows.some(row=>row.is_active)&&stock>0}/></Pressable>})}</View>

  {data?.rows.length===0&&<Card><Label>No records yet</Label></Card>}
  {loading&&data&&<ActivityIndicator color={theme.text}/>}
  <ProductPanel visible={(!!selected||family.length>0)&&!form} title={selected?.name||family[0]?.name||"Product"} close={()=>{setSelected(null);setFamily([]);}}>
    {!selected&&<>{[...family].sort(compareVariants).map(row=><Pressable key={row.id} accessibilityRole="button" onPress={()=>{setSelected(row);}}><Card><View style={styles.row}><ProductPhoto uri={row.image_url} size={64}/><View style={{flex:1}}><Label>{[row.size,row.color].filter(Boolean).join(' · ')||row.name}</Label><Label muted>{row.sku}</Label><Label>{`${money(row.selling_price,data?.currency)} · ${row.stock_quantity} in stock`}</Label></View></View></Card></Pressable>)}</>}
    {selected&&<>
    <SectionTitle title={detail?.name||selected.name} icon={feature==='Bundles'?'layers-outline':'pricetag-outline'}/><View style={{maxWidth:320,width:'100%',alignSelf:'center'}}><ProductPhoto uri={detail?.image_url} fill/></View>
    {details.loading&&!details.data&&<Shimmer rows={2}/>}{details.error&&<Card><Label>{details.error}</Label><Button title="Retry" secondary disabled={!online} onPress={details.refresh}/></Card>}
    <View style={{flexDirection:'row',gap:12,flexWrap:'wrap'}}><Metric label="Selling price" value={money(Number(detail?.selling_price),data?.currency)} icon="pricetag-outline"/><Metric label="In stock" value={String(detail?.stock_quantity??0)} icon="cube-outline"/></View>
    <Card><SectionTitle title="Product details" icon="information-circle-outline"/><DetailRow label="SKU" value={detail?.sku}/><DetailRow label="Barcode" value={detail?.barcode}/><DetailRow label="Variant" value={[detail?.size,detail?.color].filter(Boolean).join(' · ')||'—'}/><DetailRow label="Status" value={detail?.is_active?'Active':'Inactive'}/><Label muted>{detail?.description||'No description'}</Label></Card>
    <Card><SectionTitle title="Visibility" icon="eye-outline"/><DetailRow label="Show on POS" value={detail?.is_pos?'Enabled':'Disabled'}/><DetailRow label="Show on Online Store" value={detail?.is_online?'Enabled':'Disabled'}/></Card>
    {!!detail?.items?.length&&<Card><SectionTitle title="Bundle items" icon="layers-outline"/>{detail.items.map(item=><DetailRow key={item.component_product_id} label={item.name||item.component_product_id} value={`${item.quantity} ${theme.t('units')}`}/>)}</Card>}
    <SectionTitle title="Actions" icon="options-outline"/>
    {workspace.permissions.includes('products.update')&&<Button title="Edit" disabled={!online} onPress={()=>setForm(selected.product_type==='bundle'?'bundle-edit':'product-edit')}/>}
    {selected.product_type==='bundle'&&<>
      {workspace.permissions.includes('products.stock_adjust')&&<Button title="Pack / unpack" secondary disabled={!online} onPress={()=>setForm('bundle-pack')}/>}
      {workspace.permissions.includes('products.update')&&<Button title="Display settings" secondary disabled={!online} onPress={()=>setForm('bundle-toggle')}/>}
      {workspace.permissions.includes('products.disable')&&<Button title="Delete bundle" secondary disabled={!online} onPress={()=>setForm('bundle-delete')}/>}
    </>}{family.length>0&&<Button title="Back to variants" secondary onPress={()=>setSelected(null)}/>}
  </>}</ProductPanel>
  {form&&<ManagementForm initialOptions={categoryOptions.data} operation={form} id={selected?.id} scope={scope} online={online} workspace={workspace} close={()=>setForm(null)} saved={()=>{setForm(null);setSelected(null);setFamily([]);clearCache();refresh();}}/>}
 </ScrollView>{workspace.permissions.includes('products.create')&&<FloatingAdd label={feature==='Bundles'?'New bundle':'Add product'} disabled={!online} onPress={()=>{setSelected(null);setForm(feature==='Bundles'?'bundle-create':'product-create');}}/>}</View>;
}

export function ManagementForm({operation,id,scope,online,workspace,close,saved,embedded=false,initialOptions}:{initialOptions?:{categories:{id:string;name:string}[];mode:string};operation:string;id?:string;scope:Scope;online:boolean;workspace?:Workspace;close:()=>void;saved:()=>void;embedded?:boolean}) {
 const theme=useTheme();const key=`tenh-manage-${scope.userId}-${scope.businessId}-${scope.branchId}-${operation}-${id||'new'}`;
 const [values,setValues]=useState<Record<string,string>>({name:'',sku:'',price:'0',cost:'0',lowStock:'5',description:'',categoryId:'',type:'standard',note:'',phone:'',address:'',quantity:'1',action:'pos'});
 const [productMode,setProductMode]=useState('');
 const [flags,setFlags]=useState({showPos:true,showOnline:true,active:true,published:false,acceptOrders:false,removeImage:false,enabled:true});
 const [variants,setVariants]=useState<Variant[]>([blankRow()]),[lines,setLines]=useState<Line[]>([]),[groups,setGroups]=useState<Group[]>([]);
 const [categories,setCategories]=useState<{id:string;name:string}[]>([]),[suppliers,setSuppliers]=useState<{id:string;name:string}[]>([]),[chooseCategory,setChooseCategory]=useState(false);
 const [image,setImage]=useState<ImageAsset|null>(null),[imageUrl,setImageUrl]=useState<string|null>(null),[pending,setPending]=useState<Pending|null>(null);
 const [draftReady,setDraftReady]=useState(false);
 const [busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[picker,setPicker]=useState(false),[reload,setReload]=useState(0);
 const [progress,setProgress]=useState<number|null>(null);
 const working=useRef(false);const isProduct=operation.startsWith('product-'),isBundle=operation==='bundle-create'||operation==='bundle-edit',isDraft=operation==='purchase-create'||operation==='transfer-save';
 const [needsSetup,setNeedsSetup]=useState(false);
 const canSave=operation!=='storefront-save'||!workspace||workspace.permissions.includes('storefront.update');
 const locked=busy||!!pending||!canSave||!draftReady||((!!id||operation==='storefront-save')&&!ready);
 const set=(name:string,value:string)=>setValues(v=>({...v,[name]:value}));
 function restore(request:Pending){
  setValues(v=>({...v,quantity:String(request.input.quantity??1),...Object.fromEntries(Object.entries(request.input).filter((entry):entry is [string,string]=>typeof entry[1]==='string'))}));
  setFlags(v=>({...v,...Object.fromEntries(Object.entries(request.input).filter(([,value])=>typeof value==='boolean'))}));
  if(Array.isArray(request.input.variants))setVariants(request.input.variants as Variant[]);
  if(Array.isArray(request.input.groups))setGroups(request.input.groups as Group[]);
  if(Array.isArray(request.input.items))setLines((request.input.items as {productId:string;quantity:number;cost:number;optionIds:string[]}[]).map(i=>({...i,name:i.productId,quantity:String(i.quantity),cost:String(i.cost||0)})));
  setImage(request.image);
 }
 useEffect(()=>{let active=true;
  void (async()=>{
   const stored=await deviceStorage.getItem(key);if(!active)return;setReady(false);if(stored){setPending(JSON.parse(stored));restore(JSON.parse(stored));}setDraftReady(true);
   if(!online){if(stored)restore(JSON.parse(stored));setReady(!!stored);return;}
   if(isProduct||isBundle){const options=initialOptions ?? await api<{categories:{id:string;name:string}[];mode:string}>('catalog-options',scope);if(!active)return;setCategories(options.categories);setProductMode(options.mode);setValues(v=>({...v,type:options.mode==='variant'||options.mode==='configurable'?options.mode:v.type}));}
   if(operation==='purchase-create'){const options=await api<{suppliers:{id:string;name:string}[]}>('draft-options',scope);if(active)setSuppliers(options.suppliers);}
   if(id&&(isProduct||isBundle||operation.startsWith('bundle-'))){const p=await api<Product>(`catalog-detail?id=${id}`,scope);if(!active)return;setValues(v=>({...v,name:p.name,sku:p.sku||'',barcode:p.barcode||'',price:String(p.selling_price),cost:String(p.cost_price),lowStock:String(p.low_stock_quantity),description:p.description||'',categoryId:p.category_id||'',size:p.size||'',color:p.color||'',expected:p.updated_at||''}));setFlags(v=>({...v,showPos:p.is_pos!==false,showOnline:p.is_online,active:p.is_active,enabled:p.is_pos!==false}));setImageUrl(p.image_url);setLines((p.items||[]).map(i=>({productId:i.component_product_id,name:i.name||i.component_product_id,quantity:String(i.quantity),cost:'0',optionIds:(i.selected_options||[]).map(o=>o.id||o.optionId||'').filter(Boolean)})));}
   if(operation==='storefront-save'){const store=await api<{configured?:boolean;display_name:string;description:string;phone:string;address:string;is_published:boolean;accept_online_orders:boolean;updated_at:string}>('storefront',scope);if(!active)return;if(!store)throw new Error('Set up your Online Store on the website first.');if(store.configured===false){setNeedsSetup(true);return;}setValues(v=>({...v,name:store.display_name||'',description:store.description||'',phone:store.phone||'',address:store.address||'',expected:store.updated_at||''}));setFlags(v=>({...v,published:store.is_published,acceptOrders:store.accept_online_orders}));}
   if(operation==='transfer-save'&&id){const transfer=await api<{updated_at:string;destination_location_id:string;note:string;items:{product_id:string;quantity:number}[]}>(`transfer-detail?id=${id}`,scope);if(!active)return;setValues(v=>({...v,expected:transfer.updated_at||'',destinationId:transfer.destination_location_id,note:transfer.note||''}));setLines(transfer.items.map(i=>({productId:i.product_id,name:i.product_id,quantity:String(i.quantity),cost:'0',optionIds:[]})));}
   if(active&&stored)restore(JSON.parse(stored));
   if(active)setReady(true);
  })().catch(e=>{if(active)setError(e.message);});return()=>{active=false;};
 // Scope changes remount the workspace; the durable key identifies the whole form.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[key,online,reload]);
 async function pickImage(){try{const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:0.9,allowsMultipleSelection:false});if(!result.canceled){const a=result.assets[0];if((a.fileSize||0)>5*1024*1024)throw new Error('Choose an image smaller than 5 MB.');setImage({uri:a.uri,name:a.fileName||'product.jpg',type:a.mimeType||'image/jpeg'});setFlags(v=>({...v,removeImage:false}));}}catch(e){setError((e as Error).message);}}
 async function finish(result:{success:boolean;rolledBack?:boolean;message?:string}){
  if(result.success){await deviceStorage.removeItem(key);setPending(null);clearCache();saved();if(embedded){setReload(v=>v+1);theme.alert(theme.t('Saved'));}return;}
  if(result.rolledBack){await deviceStorage.removeItem(key);setPending(null);throw new Error(result.message||'Save failed. Review the form.');}
  throw new Error(result.message||'Save not confirmed. Keep this request and check again.');
 }
 async function submit(){if(working.current||!online||!ready)return;working.current=true;setBusy(true);setError('');setProgress(null);try{
  let request=pending;
  if(request){const status=await api<{data:{success:boolean;rolledBack?:boolean;message?:string}|null}>(`management-status?id=${request.requestId}`,scope);if(status.data){await finish(status.data);return;}}
  if(!request){
   const input:Record<string,unknown>={...values,...flags,id,expected:values.expected||null,quantity:Number(values.quantity),variants,groups,items:lines.map(l=>({productId:l.productId,quantity:Number(l.quantity),cost:Number(l.cost),optionIds:l.optionIds}))};
   request={requestId:Crypto.randomUUID(),operation,input,image};await deviceStorage.setItem(key,JSON.stringify(request));setPending(request);
  }
  const form=new FormData();form.append('requestId',request.requestId);form.append('input',JSON.stringify(request.input));if(request.image)form.append('image',request.image as unknown as Blob);
  const result=await api<{success:boolean;rolledBack?:boolean;message?:string}>(operation,scope,form,undefined,request.image?setProgress:undefined);await finish(result);
 }catch(e){if(e instanceof ApiError&&e.uncertain===false){await deviceStorage.removeItem(key);setPending(null);}setError((e as Error).message);}finally{working.current=false;setBusy(false);}}
 const field=(name:string,label:string,numeric=false)=><Field key={name} label={label} value={values[name]||''} editable={!locked} onChangeText={value=>set(name,value)} keyboardType={numeric?'decimal-pad':'default'} maxLength={name==='description'?500:160}/>;
 if(needsSetup)return <View style={styles.page}><Card><SectionTitle title="Set up Online Store" icon="storefront-outline"/><Label muted>Your online store has not been set up yet. Complete the initial setup on the website, then return here.</Label><Button title="Set up on website" onPress={()=>void Linking.openURL(`${apiUrl}/dashboard/online-store`).catch(()=>theme.alert('Unable to open website'))}/><Button title="Check again" secondary disabled={!online} onPress={()=>{setNeedsSetup(false);setReload(v=>v+1);}}/></Card></View>;
 const content=picker?<ProductChooser operation={operation} visible={picker} configure={isBundle} scope={scope} online={online} close={()=>setPicker(false)} selected={lines.map(l=>l.productId)} choose={(p,options)=>{setLines(v=>v.some(line=>line.productId===p.id)?v:[...v,{productId:p.id,name:p.name,quantity:'1',cost:String(p.cost_price),optionIds:options,imageUrl:p.image_url,variant:[p.size,p.color].filter(Boolean).join(' / ')}]);setPicker(false);}}/>:<ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled">{operation==='storefront-save'&&<Card><Label>Quick store settings</Label><Label muted>Use the website for full storefront design and setup.</Label><Button title="Full setup on website" secondary onPress={()=>void Linking.openURL(`${apiUrl}/dashboard/online-store`).catch(()=>theme.alert('Unable to open website'))}/></Card>}
  {!embedded&&<Label large>{operation==='product-create'?'Add product':operation==='product-edit'?'Edit product':operation==='bundle-create'?'New bundle':operation==='bundle-edit'?'Edit bundle':operation==='bundle-pack'?'Pack / unpack':operation==='bundle-delete'?'Delete bundle':operation==='bundle-toggle'?'Display settings':operation==='purchase-create'?'New purchase order':operation==='transfer-save'?'New stock transfer':'Online Store'}</Label>}
  {busy&&(image||pending?.image)&&<UploadProgress progress={progress}/>}
  {!ready&&(!!id||operation==='storefront-save')&&<Shimmer rows={4}/>}{error&&<Card><Label>{error}</Label>{!ready&&<Button title="Retry" onPress={()=>setReload(v=>v+1)}/>}</Card>}
  {pending&&<Card><Label>Unconfirmed save</Label><Label muted>Check this request before making another change.</Label></Card>}
  {operation==='product-create'&&values.type==='variant'&&<Card><Label>Quick size run</Label><Label muted>Copies the first variant colour and prices. Check each SKU before saving.</Label><View style={[styles.row,{flexWrap:'wrap'}]}>{[{name:'XS–XXL',sizes:['XS','S','M','L','XL','XXL']},{name:'36–45',sizes:Array.from({length:10},(_,i)=>String(i+36))}].map(run=><Button key={run.name} title={run.name} secondary disabled={locked} onPress={()=>{try{setVariants(appendSizeRun(variants,run.sizes));}catch(e){theme.alert('Size run',(e as Error).message);}}}/>)}</View></Card>}
  {operation==='bundle-delete'&&<Card><Label>{values.name}</Label><Label>Delete this bundle from this branch? Bundles with stock or transaction history cannot be deleted.</Label></Card>}
  {(isProduct||isBundle||operation==='storefront-save')&&<Card><SectionTitle title={operation==='storefront-save'?'Store identity':'Basic information'} icon={operation==='storefront-save'?'storefront-outline':'pricetag-outline'}/>{field('name','Name *')}{field('description','Description')}</Card>}
  {operation==='product-create'&&productMode==='standard'&&<Card><Label>Product type</Label>{['standard','variant'].map(type=><Button key={type} title={type==='variant'?'Variants':'Standard product'} secondary={values.type!==type} disabled={locked} onPress={()=>{set('type',type);if(type==='standard')setVariants(v=>v.slice(0,1));}}/>)}</Card>}
  {(isProduct||isBundle)&&<>
   <Card><SectionTitle title="Category" icon="grid-outline"/><Button title={categories.find(c=>c.id===values.categoryId)?.name||'No category'} secondary disabled={locked} onPress={()=>setChooseCategory(true)}/></Card>
   <Card><SectionTitle title="Product photo" icon="image-outline"/>{(image?.uri||imageUrl)&&!flags.removeImage&&<Image source={{uri:image?.uri||imageUrl!}} style={{height:180}} resizeMode="contain"/>}<Button title="Choose image" secondary disabled={locked} onPress={()=>void pickImage()}/><Toggle label="Remove image" value={flags.removeImage} disabled={locked} change={value=>{setFlags(v=>({...v,removeImage:value}));if(value)setImage(null);}}/></Card>
   <Card><Toggle label="Show on POS" value={flags.showPos} disabled={locked||operation==='bundle-edit'} change={showPos=>setFlags(v=>({...v,showPos}))}/><Toggle label="Show on Online Store" value={flags.showOnline} disabled={locked||operation==='bundle-edit'} change={showOnline=>setFlags(v=>({...v,showOnline}))}/>{operation==='product-edit'&&<Toggle label="Active" value={flags.active} disabled={locked} change={active=>setFlags(v=>({...v,active}))}/>}</Card>
  </>}
  {operation==='product-create'&&<><Label>{values.type==='variant'?'Variants':values.type==='configurable'?'Configurable product':'Standard product'}</Label>{variants.map((row,index)=><Card key={index}>{(values.type==='variant'?['sku','barcode','size','color','cost','price','lowStock']:['sku','barcode','cost','price','lowStock']).map(k=><Field key={k} label={{sku:'SKU *',barcode:'Barcode',size:'Size *',color:'Colour *',cost:'Cost price',price:'Selling price',lowStock:'Low-stock quantity'}[k]||k} value={row[k as keyof Variant]} editable={!locked} keyboardType={['cost','price','lowStock'].includes(k)?'decimal-pad':'default'} onChangeText={value=>setVariants(v=>v.map((r,i)=>i===index?{...r,[k]:value}:r))}/>)}{values.type==='variant'&&<View style={[styles.row,{flexWrap:'wrap'}]}>{['XS','S','M','L','XL','XXL','36','37','38','39','40','41','42','43'].map(size=><ChoiceChip key={size} title={size} selected={row.size===size} disabled={locked} onPress={()=>setVariants(rows=>rows.map((item,i)=>i===index?{...item,size}:item))}/>)}</View>}{variants.length>1&&<Button title="Remove variant" secondary disabled={locked} onPress={()=>setVariants(v=>v.filter((_,i)=>i!==index))}/>}</Card>)}{values.type==='variant'&&variants.length<40&&<Button title="Add variant" secondary disabled={locked} onPress={()=>setVariants(v=>[...v,blankRow()])}/>}<Label muted>New products start with zero stock. Add stock through Inventory or purchase receiving.</Label></>}
  {operation==='product-create'&&values.type==='configurable'&&<><Label large>Option groups</Label>{groups.map((group,index)=><Card key={index}><Field label="Group name" value={group.name} editable={!locked} onChangeText={name=>setGroups(g=>g.map((v,i)=>i===index?{...v,name}:v))}/><Toggle label="Required" value={group.required} disabled={locked} change={required=>setGroups(g=>g.map((v,i)=>i===index?{...v,required}:v))}/>{group.options.map((option,n)=><View key={n}><Field label="Option name" value={option.name} editable={!locked} onChangeText={name=>setGroups(g=>g.map((v,i)=>i===index?{...v,options:v.options.map((o,j)=>j===n?{...o,name}:o)}:v))}/><Field label="Extra price" value={option.price} keyboardType="decimal-pad" editable={!locked} onChangeText={price=>setGroups(g=>g.map((v,i)=>i===index?{...v,options:v.options.map((o,j)=>j===n?{...o,price}:o)}:v))}/></View>)}<Button title="Add option" secondary disabled={locked||group.options.length>=30} onPress={()=>setGroups(g=>g.map((v,i)=>i===index?{...v,options:[...v.options,{name:'',price:'0'}]}:v))}/><Button title="Remove group" secondary disabled={locked} onPress={()=>setGroups(g=>g.filter((_,i)=>i!==index))}/></Card>)}<Button title="Add option group" disabled={locked||groups.length>=12} secondary onPress={()=>setGroups(g=>[...g,{name:'',required:false,options:[{name:'',price:'0'}]}])}/></>}
  {(operation==='product-edit'||isBundle)&&<Card>{field('sku','SKU *')}{field('price','Selling price',true)}{operation==='product-edit'&&<>{field('barcode','Barcode')}{field('cost','Cost price',true)}{field('lowStock','Low-stock quantity',true)}{field('size','Size')}{field('color','Colour')}</>}</Card>}
  {operation==='purchase-create'&&<Card><SectionTitle title="Supplier Information" icon="bus-outline"/><Label muted>Select the supplier and expected delivery date.</Label><Label>Supplier *</Label><SelectMenu label="Select supplier" value={values.supplierId||''} options={suppliers.map(s=>({value:s.id,label:s.name}))} disabled={locked} change={value=>set('supplierId',value)}/>{field('expectedDate','Expected date (YYYY-MM-DD)')}</Card>}
  {operation==='transfer-save'&&<Card><SectionTitle title="Branch Information" icon="swap-horizontal-outline"/><DetailRow label="From" value={workspace?.branches.find(b=>b.id===scope.branchId)?.name}/><Label>Destination branch *</Label><SelectMenu label="Select destination" value={values.destinationId||''} options={(workspace?.branches||[]).filter(b=>b.id!==scope.branchId).map(b=>({value:b.id,label:b.name}))} disabled={locked} change={value=>set('destinationId',value)}/></Card>}
  {(isBundle||isDraft)&&<><Card><SectionTitle title="Items" icon="cube-outline"/><Label muted>Add products and exact variants.</Label><Button title="＋ Choose product / variant" secondary disabled={locked||lines.length>=100} onPress={()=>setPicker(true)}/>{lines.map((line,index)=><View key={line.productId} style={{gap:10,paddingVertical:12,borderBottomWidth:1,borderColor:theme.border}}><View style={styles.row}><ProductPhoto uri={line.imageUrl} size={46} fit="contain"/><View style={{flex:1,gap:3}}><Label>{line.name}</Label>{!!line.variant&&<Label muted>{line.variant}</Label>}</View><Pressable accessibilityRole="button" accessibilityLabel="Remove item" disabled={locked} onPress={()=>setLines(v=>v.filter((_,i)=>i!==index))} style={{padding:10}}><Ionicons name="trash-outline" size={21} color={theme.muted}/></Pressable></View><View style={[styles.row,{alignItems:'flex-end'}]}><View style={{flex:1}}><Field label="Quantity" value={line.quantity} editable={!locked} keyboardType="number-pad" onChangeText={quantity=>setLines(v=>v.map((l,i)=>i===index?{...l,quantity}:l))}/></View>{operation==='purchase-create'&&<><View style={{flex:1}}><Field label="Unit cost" value={line.cost} keyboardType="decimal-pad" editable={!locked} onChangeText={cost=>setLines(v=>v.map((l,i)=>i===index?{...l,cost}:l))}/></View><View style={{flex:1,paddingBottom:12}}><Label muted>Total</Label><Label>{(Number(line.quantity||0)*Number(line.cost||0)).toFixed(2)}</Label></View></>}</View></View>)}{operation==='purchase-create'&&<DetailRow label="Estimated total" value={lines.reduce((total,line)=>total+(Number(line.quantity)||0)*(Number(line.cost)||0),0).toFixed(2)}/>}</Card><Card><SectionTitle title="Note" icon="document-text-outline"/><Label muted>Additional notes (optional).</Label><Field label="Note" placeholder="Write a note…" value={values.note||''} multiline maxLength={500} editable={!locked} onChangeText={value=>set('note',value)}/><Label muted>{`${(values.note||'').length} / 500`}</Label></Card></>}
  {operation==='bundle-pack'&&<Card>{field('quantity','Quantity',true)}<Label muted>Positive quantity packs sets. Negative quantity unpacks sets and restores components.</Label></Card>}
  {operation==='bundle-toggle'&&<Card><Button title="Show on POS" secondary={values.action!=='pos'} disabled={locked} onPress={()=>{set('action','pos');setFlags(v=>({...v,enabled:v.showPos}));}}/><Button title="Show on Online Store" secondary={values.action!=='online'} disabled={locked} onPress={()=>{set('action','online');setFlags(v=>({...v,enabled:v.showOnline}));}}/><Toggle label="Enabled" value={flags.enabled} disabled={locked} change={enabled=>setFlags(v=>({...v,enabled}))}/></Card>}
  {operation==='storefront-save'&&<><Card><SectionTitle title="Store contact" icon="call-outline"/><Label muted>Applies to every branch.</Label>{field('phone','Store phone')}{field('address','Store address')}</Card><Card><SectionTitle title="Store availability" icon="globe-outline"/><Badge title={flags.published?'Published':'Unpublished'} positive={flags.published}/><Toggle label="Publish storefront" value={flags.published} disabled={locked} change={published=>setFlags(v=>({...v,published}))}/><Toggle label="Accept online orders" value={flags.acceptOrders} disabled={locked} change={acceptOrders=>setFlags(v=>({...v,acceptOrders}))}/></Card></>}
  <View style={{flexDirection:isDraft?'row':'column',gap:10}}><View style={{flex:1}}><Button title={pending?'Check / retry save':operation==='bundle-delete'?'Delete bundle':operation==='purchase-create'?'Save Purchase Order':operation==='transfer-save'?'Save Stock Transfer':'Save'} busy={busy} disabled={!online||!ready||!canSave} onPress={()=>theme.alert(theme.t('Confirm'),theme.t(operation==='bundle-delete'?'Delete this bundle?':'Save these details?'),[{text:theme.t('Cancel'),style:'cancel'},{text:theme.t(operation==='bundle-delete'?'Delete':'Save'),style:operation==='bundle-delete'?'destructive':'default',onPress:()=>void submit()}])}/></View>
  {!embedded&&<View style={{flex:isDraft?1:undefined}}><Button title={isDraft?'Cancel':'Close'} secondary disabled={busy} onPress={close}/></View>}</View>
  <Modal visible={chooseCategory} animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>setChooseCategory(false)}><SafeAreaView style={{flex:1,backgroundColor:theme.background}}><ScrollView contentContainerStyle={styles.page}><Label large>Category</Label>{[{id:'',name:'No category'},...categories].map(c=><Button key={c.id} title={c.name} secondary onPress={()=>{set('categoryId',c.id);setChooseCategory(false);}}/>)}<Button title="Close" onPress={()=>setChooseCategory(false)}/></ScrollView></SafeAreaView></Modal>
 </ScrollView>;
 return embedded?content:<Modal visible animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>{if(!busy){if(picker)setPicker(false);else close();}}}><SafeAreaView style={{flex:1,backgroundColor:theme.background}}>{content}</SafeAreaView></Modal>;
}

function ProductChooser({visible,scope,online,selected,choose,close,configure,operation}:{visible:boolean;scope:Scope;online:boolean;selected:string[];choose:(product:Product,optionIds:string[])=>void;close:()=>void;configure:boolean;operation:string}){
 const [family,setFamily]=useState<Product[]>([]),[color,setColor]=useState<string|null>(null),[size,setSize]=useState<string|null>(null),[variant,setVariant]=useState<Product|null>(null);
 const [searchOpen,setSearchOpen]=useState(false);
 const theme=useTheme();const[search,setSearch]=useState(''),[query,setQuery]=useState('');
 type Config=Product&{groups:{id:string;name:string;selection_type:string;is_required:boolean;min_selections:number;max_selections:number}[];options:{id:string;group_id:string;name:string;price_adjustment:number}[]};
 const [config,setConfig]=useState<Config|null>(null),[optionIds,setOptionIds]=useState<string[]>([]),[configError,setConfigError]=useState(''),[configBusy,setConfigBusy]=useState(false);
 useEffect(()=>{const timer=setTimeout(()=>{setQuery(search);},300);return()=>clearTimeout(timer);},[search]);
 const endpoint=operation==='purchase-create'?'purchase-products':operation==='transfer-save'?'transfer-products':'catalog';
 const {data,loading,error,refresh,more}=useInfiniteData<{rows:Product[];total:number;currency:string}>(`${endpoint}?grouped=true&components=true&search=${encodeURIComponent(query)}`,scope,online&&visible);
 const scrolling=useInfiniteScroll(()=>{if(!family.length&&!config)more();});
 async function select(p:Product){if(configBusy)return;if(!configure||p.product_type!=='configurable'){choose(p,[]);return;}setConfigBusy(true);setConfigError('');try{setConfig(await api<Config>(`catalog-detail?id=${p.id}`,scope));setOptionIds([]);}catch(e){setConfigError((e as Error).message);}finally{setConfigBusy(false);}}
 const valid=config?.groups.every(g=>{const count=config.options.filter(o=>o.group_id===g.id&&optionIds.includes(o.id)).length;return count>=Math.max(g.is_required?1:0,g.min_selections||0)&&count<=(g.selection_type==='single'?1:g.max_selections||config.options.length);});
 return <SafeAreaView style={{flex:1,backgroundColor:theme.background}}><ScrollView {...scrolling} contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled">
 <View style={[styles.row,{justifyContent:'space-between'}]}><Label large>Choose product / variant</Label><Pressable accessibilityRole="button" accessibilityLabel="Search products" onPress={()=>setSearchOpen(value=>!value)} style={{padding:10,minHeight:44}}><Ionicons name="search-outline" size={23} color={theme.text}/></Pressable></View>
 {config?<><Label>{config.name}</Label>{config.groups.map(g=><Card key={g.id}><Label>{g.name}</Label>{config.options.filter(o=>o.group_id===g.id).map(o=><Button key={o.id} title={o.name+' · +'+money(o.price_adjustment)} secondary={!optionIds.includes(o.id)} onPress={()=>setOptionIds(ids=>ids.includes(o.id)?ids.filter(id=>id!==o.id):[...ids.filter(id=>g.selection_type!=='single'||!config.options.some(other=>other.id===id&&other.group_id===g.id)),o.id])}/>)}</Card>)}<Button title="Add item" disabled={!valid} onPress={()=>{choose(config,optionIds);setConfig(null);}}/><Button title="Back" secondary onPress={()=>setConfig(null)}/></>
 :family.length>0?<><Label large>{family[0]?.name}</Label>
  <View style={{alignItems:'center'}}><ProductPhoto uri={variant?.image_url||family.find(row=>(row.color||'')===color)?.image_url||family[0]?.image_url} size={128}/></View>
  <Label>Colour</Label><View style={[styles.row,{flexWrap:'wrap'}]}>{[...new Set(family.map(row=>row.color||''))].map(value=><ChoiceChip key={value} title={value||'No colour'} selected={color===value} disabled={!family.some(row=>(row.color||'')===value&&!selected.includes(row.id))} onPress={()=>{setColor(value);setSize(null);setVariant(null);}}/>)}</View>
  <Label>Size</Label><View style={[styles.row,{flexWrap:'wrap'}]}>{[...new Set(family.map(row=>row.size||''))].map(value=><ChoiceChip key={value} title={value||'One size'} selected={size===value} disabled={color===null||!matchingVariants(family,color,value).some(row=>!selected.includes(row.id))} onPress={()=>{setSize(value);const matches=matchingVariants(family,color,value);setVariant(matches.length===1?matches[0]:null);}}/>)}</View>
  {color!==null&&size!==null&&matchingVariants(family,color,size).length>1&&<><Label>Choose SKU</Label>{matchingVariants(family,color,size).map(row=><ChoiceChip key={row.id} title={row.sku} selected={variant?.id===row.id} disabled={selected.includes(row.id)} onPress={()=>setVariant(row)}/>)}</>}
  <Button title="Add item" disabled={!variant||configBusy||!!variant&&selected.includes(variant.id)} onPress={()=>{if(variant){setFamily([]);void select(variant);}}}/>
<Button title="Back to products" secondary onPress={()=>setFamily([])}/></> :<>{searchOpen&&<Field label="Search name, SKU or barcode" value={search} onChangeText={setSearch}/>}{loading&&!data&&<Shimmer rows={4}/>}{configBusy&&<ActivityIndicator/>}{(error||configError)&&<Card><Label>{error||configError}</Label><Button title="Retry" secondary disabled={!online} onPress={refresh}/></Card>}{!loading&&!error&&data?.rows.length===0&&<Label>No matching products in this branch.</Label>}{groupProducts(data?.rows??[]).map(rows=><Pressable key={rows[0].variant_group_id||rows[0].id} accessibilityRole="button" disabled={rows.every(row=>selected.includes(row.id))||configBusy} onPress={()=>{if(rows.length>1){setFamily(rows);setColor(null);setSize(null);setVariant(null);}else void select(rows[0]);}} style={{padding:12,borderWidth:1,borderColor:theme.border,borderRadius:14,backgroundColor:theme.panel,flexDirection:'row',alignItems:'center',gap:12,opacity:rows.every(row=>selected.includes(row.id))?0.4:1}}><ProductPhoto uri={rows[0].image_url} size={48}/><View style={{flex:1}}><Label>{rows[0].name}</Label><Label muted>{rows.length>1?`${rows.length} variants`:rows[0].sku}</Label></View><Label muted>{money(Math.min(...rows.map(row=>row.cost_price)),data?.currency)}</Label></Pressable>)}{loading&&data&&<ActivityIndicator color={theme.text}/>}</>}

 <Button title="Close" secondary onPress={()=>{setConfig(null);close();}}/></ScrollView></SafeAreaView>;
}
