import React from 'react';
import {Shimmer} from './loading';
import { View,Text } from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import { money, type Scope } from './client';
import { useData } from './data';
import { Badge,Button, Card, DetailRow, Label, SectionTitle,styles,useTheme } from './ui';

export type RegisterDetailData={status:string;openingCash:number;closingCash:number|null;variance:number|null;openedAt:string;closedAt:string|null;openingNote:string|null;closingNote:string|null;summary:{cash:number;noncash:number;incoming:number;outgoing:number;refunds:number;expected:number};orderCount:number;movements:{id:string;type:string;amount:number;reason:string}[];currency:string};
export function RegisterDetail({id,scope,online,onCloseShift}:{id:string;scope:Scope;online:boolean;onCloseShift:()=>void}){
 const theme=useTheme();
 const {data,error,loading,refresh}=useData<RegisterDetailData>(`register-detail?id=${id}`,scope,online);
 return <View style={{gap:14}}>{loading&&!data&&<Shimmer rows={4}/>}{error&&<Card><Label>{error}</Label><Button title="Retry" disabled={!online} onPress={refresh}/></Card>}{data&&<>
  <View style={[styles.row,{justifyContent:'space-between'}]}><View style={{flex:1}}><Label muted>View your register session</Label></View><Badge title={data.status==='open'?'Open':'Closed'} positive={data.status==='open'}/></View>
  <View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{([['Expected cash',money(data.summary.expected,data.currency),'cash-outline','#275de8'],['Transactions',String(data.orderCount),'receipt-outline','#7656d5'],['Variance',data.variance===null?'Not counted':money(data.variance,data.currency),'stats-chart-outline','#178963']] as const).map(([title,value,icon,color])=><View key={title} style={{flex:1,minWidth:95,padding:12,borderRadius:16,borderWidth:1,borderColor:theme.border,backgroundColor:theme.dark?theme.panel:`${color}0c`,gap:8}}><Ionicons name={icon} size={22} color={color}/><Label muted>{title}</Label><Text style={{fontSize:18,fontWeight:'700',color:theme.text}}>{value}</Text></View>)}</View>
  <Card><SectionTitle title="Shift summary" icon="cash-outline"/><Label muted>Key details from your register session</Label>{([['Opened',new Date(data.openedAt).toLocaleString()],...(data.closedAt?[['Closed',new Date(data.closedAt).toLocaleString()]]:[]),['Orders counted',String(data.orderCount)],['Opening cash',money(data.openingCash,data.currency)],['Cash payments',money(data.summary.cash,data.currency)],['Non-cash payments',money(data.summary.noncash,data.currency)],['Cash added',money(data.summary.incoming,data.currency)],['Cash removed',money(data.summary.outgoing,data.currency)],['Refunds included in cash removed',money(data.summary.refunds,data.currency)]]).map(([label,value])=><View key={label} style={{paddingVertical:8,borderBottomWidth:1,borderColor:theme.border}}><DetailRow label={label} value={value}/></View>)}<View style={{backgroundColor:theme.background,padding:15,borderRadius:14}}><DetailRow label="Expected cash" value={money(data.summary.expected,data.currency)}/></View>{data.status==='closed'&&<><DetailRow label="Counted closing cash" value={data.closingCash===null?'—':money(data.closingCash,data.currency)}/><DetailRow label="Variance" value={data.variance===null?'—':money(data.variance,data.currency)}/></>}{data.openingNote&&<DetailRow label="Opening note" value={data.openingNote}/>}{data.closingNote&&<DetailRow label="Closing note" value={data.closingNote}/>}</Card>
  <Card><SectionTitle title="Recent cash movements" icon="swap-horizontal-outline"/>{data.movements.length?data.movements.map(row=><View key={row.id} style={{paddingVertical:9,borderBottomWidth:1,borderColor:theme.border}}><DetailRow label={`${row.type==='cash_in'?'Cash in':'Cash out'} · ${row.reason}`} value={money(row.amount,data.currency)}/></View>):<View style={{alignItems:'center',paddingVertical:20,gap:12}}><Ionicons name="receipt-outline" size={38} color={theme.muted}/><Label>No cash movements yet</Label><Label muted>Cash in/out activity will appear here.</Label></View>}</Card>
  {data.status==='open'&&<Button title="Close register" disabled={!online||loading||!!error} onPress={onCloseShift}/>}
 </>}</View>;
}
