"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Headphones, Plus, Bug, X } from "lucide-react";
import { toast } from "sonner";
import { createBugReport,updateBugStatus } from "./actions";
type Report={id:string;title:string;description:string;page_path:string;priority:string;status:string;created_at:string;business_id:string|null;reporter?:string};
const field="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100";
export default function SupportClient({reports,businesses,loadError}:{reports:Report[];businesses:{id:string;name:string}[];loadError:boolean}) {
  const dialog = useRef<HTMLDialogElement>(null);
  const router=useRouter();const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[updating,setUpdating]=useState(""),[error,setError]=useState(""),[filter,setFilter]=useState("all");
  useEffect(()=>{if(open)dialog.current?.showModal();},[open]);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setError("");try{const result=await createBugReport({ok:false,message:""},new FormData(event.currentTarget));if(result.ok){toast.success(result.message);setOpen(false);router.refresh();}else setError(result.message);}catch{setError("Unable to save. Please try again.");}finally{setBusy(false);}}
  async function change(id:string,status:string){setUpdating(id);try{const result=await updateBugStatus(id,status);if(result.ok){toast.success(result.message);router.refresh();}else toast.error(result.message);}catch{toast.error("Unable to update report.");}finally{setUpdating("");}}
  return <main className="space-y-6 pb-8"><header className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-3"><Headphones className="text-blue-600"/><h1 className="text-3xl font-bold">Support</h1></div><p className="mt-2 text-sm text-slate-500">Report bugs and track fixes for the platform.</p></div><button onClick={()=>{setError("");setOpen(true);}} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white"><Plus size={17}/>Report a bug</button></header>
    {loadError&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">Support data could not be loaded. Refresh to try again.</p>}
    <section className="rounded-2xl border border-slate-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5"><div><h2 className="font-bold">Bug reports</h2><p className="mt-1 text-xs text-slate-500">Latest 100 reports</p></div><select aria-label="Filter report status" value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-lg border border-slate-200 p-2 text-sm"><option value="all">All statuses</option><option value="open">Open</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option></select></div>
      {reports.filter(r=>filter==="all"||r.status===filter).map(r=><details key={r.id} className="border-b border-slate-100 p-5 last:border-0"><summary className="cursor-pointer"><span className="ml-2 font-semibold">{r.title}</span><span className="ml-3 rounded-full bg-slate-100 px-2 py-1 text-xs capitalize text-slate-600">{r.status.replaceAll("_"," ")}</span>{r.priority==="urgent"&&<span className="ml-2 text-xs font-bold text-red-600">Urgent</span>}</summary><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_220px]"><div><p className="whitespace-pre-wrap text-sm leading-6 text-slate-600">{r.description}</p><p className="mt-3 text-xs text-slate-400">{r.reporter} · {r.page_path||"No page specified"} · {businesses.find(b=>b.id===r.business_id)?.name||"Platform"} · {r.created_at.slice(0,10)}</p></div><label className="text-sm font-semibold">Status<select value={r.status} disabled={Boolean(updating)} onChange={e=>void change(r.id,e.target.value)} className={field}><option value="open">Open</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option></select></label></div></details>)}
      {!loadError&&!reports.some(r=>filter==="all"||r.status===filter)&&<div className="p-12 text-center text-slate-500"><Bug className="mx-auto mb-3"/><p>No reports in this view.</p></div>}
    </section>
    {open&&<dialog ref={dialog} aria-modal="true" aria-labelledby="report-title" onCancel={e=>{e.preventDefault();if(!busy)setOpen(false);}} className="fixed inset-0 z-[80] m-0 flex h-full max-h-none w-full max-w-none items-center justify-center bg-slate-950/40 p-4"><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6 shadow-xl"><div className="mb-5 flex items-center justify-between"><h2 id="report-title" className="text-xl font-bold">Report a bug</h2><button disabled={busy} onClick={()=>setOpen(false)} aria-label="Close report form" className="rounded-lg p-2"><X size={20}/></button></div><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-semibold">Title *<input autoFocus required minLength={3} maxLength={160} name="title" className={field}/></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Business<select name="businessId" className={field}><option value="">Platform / all businesses</option>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="text-sm font-semibold">Priority<select name="priority" defaultValue="normal" className={field}><option value="low">Low</option><option value="normal">Normal</option><option value="urgent">Urgent</option></select></label></div><label className="block text-sm font-semibold">Page path<input name="pagePath" maxLength={500} placeholder="/dashboard/orders" className={field}/></label><label className="block text-sm font-semibold">What happened? *<textarea required minLength={10} maxLength={6000} name="description" rows={5} placeholder="Steps to reproduce, expected result and actual result…" className={field}/></label><p className="text-xs text-slate-500">Do not include passwords, API keys or payment details.</p>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-blue-600 p-3 text-sm font-bold text-white disabled:opacity-60">{busy?"Saving…":"Save report"}</button></form></div></dialog>}
  </main>;
}
