"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ChevronLeft, Printer, Search, Truck } from "lucide-react";
import { code39Bars } from "@/lib/barcode/code39";
type Order={id:string;order_number:string;total:number;payment_method:string;payment_status:string|null;guest_name:string|null;guest_phone:string|null;guest_address:string|null;fulfillment_type:string|null;created_at:string;customers:any;order_items:Array<{quantity:number}>};
export default function ShippingLabelsClient({businessName,businessPhone,businessAddress,orders,settings}:{businessName:string;businessPhone:string;businessAddress:string;orders:Order[];settings:any}){
 const [q,setQ]=useState(""); const [selected,setSelected]=useState<string[]>([]); const size=settings.shipping_label_size??"100x150";
 const filtered=useMemo(()=>orders.filter(o=>`${o.order_number} ${o.guest_name??""} ${o.guest_phone??""} ${o.guest_address??""}`.toLowerCase().includes(q.toLowerCase())),[orders,q]); const chosen=orders.filter(o=>selected.includes(o.id));
 function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);}
 return <main className="mx-auto max-w-[1600px] space-y-5 pb-10"><div><Link href="/dashboard/settings/receipts" className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600"><ChevronLeft size={16}/>Print Customization</Link><h1 className="mt-3 flex items-center gap-3 text-3xl font-bold"><Truck/>Shipping Labels</h1><p className="mt-1 text-slate-500">Print labels only for delivery orders in this business.</p></div><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_430px]"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search order, customer, phone or address" className="w-full rounded-xl border py-2.5 pl-10 pr-3"/></div><div className="mt-4 divide-y">{filtered.length?filtered.map(o=>{const c=Array.isArray(o.customers)?o.customers[0]:o.customers; const name=o.guest_name||c?.name||"Customer"; const phone=o.guest_phone||c?.phone||""; const address=o.guest_address||c?.address||"";return <label key={o.id} className="flex items-start gap-3 py-3"><input type="checkbox" className="mt-1" checked={selected.includes(o.id)} onChange={()=>toggle(o.id)}/><div className="min-w-0 flex-1"><p className="font-semibold">{o.order_number} · {name}</p><p className="text-xs text-slate-500">{phone}</p><p className="truncate text-xs text-slate-500">{address||"No delivery address"}</p></div><span className="font-bold">${Number(o.total).toFixed(2)}</span></label>}):<div className="py-12 text-center text-slate-500">No delivery orders found.</div>}</div></section><aside className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">Print preview</h2><p className="text-xs text-slate-500">{chosen.length} selected · {size} mm</p><div id="shipping-label-print-area" className="mt-4 max-h-[560px] space-y-3 overflow-auto">{chosen.map(o=><ShippingLabel key={o.id} order={o} businessName={businessName} businessPhone={businessPhone} businessAddress={businessAddress} size={size} settings={settings}/>)}</div><button onClick={()=>window.print()} disabled={!chosen.length} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white disabled:opacity-40"><Printer size={18}/>Print {chosen.length} shipping label{chosen.length===1?"":"s"}</button></aside></div><style jsx global>{`@media print{body *{visibility:hidden!important}#shipping-label-print-area,#shipping-label-print-area *{visibility:visible!important}#shipping-label-print-area{position:absolute;left:0;top:0;display:block;max-height:none!important;overflow:visible!important}.shipping-label{break-after:page;margin:0!important}}`}</style></main>
}
function ShippingLabel({order,businessName,businessPhone,businessAddress,size,settings}:{order:Order;businessName:string;businessPhone:string;businessAddress:string;size:string;settings:any}){const c=Array.isArray(order.customers)?order.customers[0]:order.customers; const name=order.guest_name||c?.name||"Customer"; const phone=order.guest_phone||c?.phone||""; const address=order.guest_address||c?.address||""; const qty=(order.order_items??[]).reduce((s,i)=>s+Number(i.quantity||0),0); const data=code39Bars(order.order_number.replace(/[^A-Za-z0-9 .\-\$\/%+]/g,"-").slice(0,32)); const [w,h]=size.split("x").map(Number);return <article className="shipping-label border-2 border-black bg-white p-5 text-black" style={{width:`${w}mm`,minHeight:`${h}mm`}}>{settings.shipping_show_sender!==false&&<div><p className="text-[9px] font-bold uppercase">From</p><p className="text-base font-black">{businessName}</p><p className="text-[10px]">{businessAddress}</p>{businessPhone&&<p className="text-[10px]">{businessPhone}</p>}</div>}<div className="my-4 border-t-2 border-black"/><p className="text-[9px] font-bold uppercase">Ship to</p><p className="text-xl font-black">{name}</p>{settings.shipping_show_phone!==false&&phone&&<p className="text-sm font-semibold">{phone}</p>}<p className="mt-1 text-sm leading-5">{address||"Delivery address missing"}</p><div className="my-4 border-t-2 border-black"/><div className="grid grid-cols-2 gap-3 text-xs">{settings.shipping_show_order_number!==false&&<div><span className="text-slate-500">Order</span><p className="font-bold">{order.order_number}</p></div>}{settings.shipping_show_item_count!==false&&<div><span className="text-slate-500">Items</span><p className="font-bold">{qty}</p></div>}{settings.shipping_show_cod!==false&&<><div><span className="text-slate-500">Payment</span><p className="font-bold">{order.payment_method.toUpperCase()}</p></div><div><span className="text-slate-500">Amount</span><p className="font-bold">${Number(order.total).toFixed(2)}</p></div></>}</div>{settings.shipping_show_barcode!==false&&<div className="mt-6"><svg viewBox={`0 0 ${data.width} 44`} className="h-14 w-full" preserveAspectRatio="none">{data.bars.map((b,i)=><rect key={i} x={b.x} y="0" width={b.width} height="44" fill="black"/>)}</svg><p className="text-center text-[10px] tracking-[.2em]">{data.text}</p></div>}</article>}
