"use client";
import Link from "next/link";
import { useState } from "react";
import { Barcode, Box, Check, ChevronLeft, PackageCheck, Printer, QrCode, ReceiptText, Save, Truck } from "lucide-react";
import { saveBarcodeLabelSettings, saveReceiptSettings, saveShippingLabelSettings } from "./actions";

type Settings=Record<string,any>;
export default function PrintCustomizationClient({business,settings,storefront}:{business:{name:string;slug:string;storeUrl:string};settings:Settings;storefront:{display_name:string;logo_url:string|null;phone:string|null;address:string|null}}){
 const [tab,setTab]=useState<"receipt"|"shipping"|"barcode">("receipt");
 const [paper,setPaper]=useState(settings.paper_size); const [header,setHeader]=useState(settings.header_text??""); const [footer,setFooter]=useState(settings.footer_text??""); const [returnPolicy,setReturnPolicy]=useState(settings.return_policy??""); const [qrLabel,setQrLabel]=useState(settings.store_qr_label??"Order online");
 const [shipSize,setShipSize]=useState(settings.shipping_label_size); const [labelSize,setLabelSize]=useState(settings.barcode_label_size);
 const tabs=[{id:"receipt",label:"Receipt",icon:ReceiptText},{id:"shipping",label:"Shipping Label",icon:Truck},{id:"barcode",label:"Barcode & Product Label",icon:Barcode}] as const;
 return <main className="mx-auto max-w-[1600px] space-y-5 px-1 pb-10">
  <div><Link href="/dashboard/settings" className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600"><ChevronLeft size={16}/>Back to settings</Link><h1 className="mt-3 text-3xl font-bold text-slate-950 dark:text-white">Print Customization</h1><p className="mt-1 text-slate-500">Customize receipts, shipping labels and barcode/product labels for {business.name}.</p></div>
  <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_430px]">
   <section className="space-y-4">
    <div className="grid grid-cols-3 overflow-hidden rounded-2xl border bg-white p-2 shadow-sm dark:border-slate-800 dark:bg-slate-900">{tabs.map(t=>{const I=t.icon;return <button key={t.id} type="button" onClick={()=>setTab(t.id)} className={`flex items-center justify-center gap-2 rounded-xl px-3 py-3 text-sm font-semibold ${tab===t.id?"bg-blue-600 text-white":"text-slate-600 hover:bg-slate-50 dark:text-slate-300 dark:hover:bg-slate-800"}`}><I size={18}/>{t.label}</button>})}</div>
    {tab==="receipt"&&<form action={saveReceiptSettings} className="space-y-4">
      <Card icon={<Printer size={20}/>} title="Receipt format" sub="Choose the base format for printed receipts."><div className="grid gap-4 md:grid-cols-3"><Field label="Paper width"><div className="grid grid-cols-2 gap-2"><Choice active={paper==="58mm"} onClick={()=>setPaper("58mm")}>58 mm</Choice><Choice active={paper==="80mm"} onClick={()=>setPaper("80mm")}>80 mm</Choice></div><input type="hidden" name="paperSize" value={paper}/></Field><Field label="Receipt template"><select name="receiptTemplate" defaultValue={settings.receipt_template} className={input}><option value="classic">Classic</option><option value="compact">Compact</option><option value="minimal">Minimal</option></select></Field><Field label="Store QR label"><input name="storeQrLabel" value={qrLabel} onChange={e=>setQrLabel(e.target.value)} className={input}/></Field></div></Card>
      <Card icon={<Box size={20}/>} title="Branding & text" sub="Use your storefront logo and customize receipt text."><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-dashed p-4"><p className="text-sm font-semibold">Store logo</p><div className="mt-3 flex items-center gap-3">{storefront.logo_url?<img src={storefront.logo_url} alt="Store logo" className="h-14 w-14 rounded-xl object-cover"/>:<div className="grid h-14 w-14 place-items-center rounded-xl bg-blue-50 text-blue-600"><Box/></div>}<Link href="/dashboard/online-store" className="text-sm font-semibold text-blue-600">Change in Storefront</Link></div></div><Field label="Header text"><textarea name="headerText" value={header} onChange={e=>setHeader(e.target.value)} rows={3} className={input}/></Field><Field label="Footer text"><textarea name="footerText" value={footer} onChange={e=>setFooter(e.target.value)} rows={3} className={input}/></Field><Field label="Return policy (optional)"><textarea name="returnPolicy" value={returnPolicy} onChange={e=>setReturnPolicy(e.target.value)} rows={3} className={input}/></Field><Field label="Website"><input name="websiteUrl" defaultValue={settings.website_url??business.storeUrl} className={input}/></Field></div></Card>
      <Card icon={<Check size={20}/>} title="Visible sections" sub="Select which information is printed."><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{[["showLogo","Logo",settings.show_logo],["showAddress","Store address",settings.show_address],["showPhone","Business phone",settings.show_phone],["showCashier","Cashier",settings.show_cashier],["showCustomer","Customer",settings.show_customer],["showDiscount","Discount",settings.show_discount],["showPayment","Payment details",settings.show_payment],["showLoyalty","Loyalty points",settings.show_loyalty],["showStoreQr","Online-store QR",settings.show_store_qr],["showOrderNumber","Order number",settings.show_order_number],["showFulfillment","Fulfillment",settings.show_fulfillment],["showNotes","Notes",settings.show_notes],["showInvoiceBarcode","Invoice barcode",settings.show_invoice_barcode]].map(([n,l,c])=><label key={String(n)} className="flex items-center gap-2 rounded-xl border p-3 text-sm"><input name={String(n)} type="checkbox" defaultChecked={Boolean(c)} className="accent-blue-600"/><span>{String(l)}</span></label>)}</div></Card>
      <Card icon={<ReceiptText size={20}/>} title="Layout & formatting" sub="Fine-tune printed receipt spacing."><div className="grid gap-4 md:grid-cols-4"><Field label="Font size"><select name="fontSize" defaultValue={settings.font_size} className={input}><option value="small">Small</option><option value="medium">Medium</option><option value="large">Large</option></select></Field><Field label="Density"><select name="density" defaultValue={settings.density} className={input}><option value="compact">Compact</option><option value="comfortable">Comfortable</option></select></Field><Field label="Alignment"><select name="receiptAlignment" defaultValue={settings.receipt_alignment} className={input}><option value="center">Center header</option><option value="left">Left header</option></select></Field><Field label="Copies"><input type="number" name="receiptCopies" defaultValue={settings.receipt_copies} min={1} max={5} className={input}/></Field></div></Card>
      <button className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white"><Save size={18}/>Save Receipt Settings</button>
    </form>}
    {tab==="shipping"&&<form action={saveShippingLabelSettings} className="space-y-4"><Card icon={<Truck size={20}/>} title="Shipping label" sub="Configure labels for delivery orders. Only orders from this business can be printed."><div className="grid gap-4 md:grid-cols-2"><Field label="Label size"><select name="shippingLabelSize" value={shipSize} onChange={e=>setShipSize(e.target.value)} className={input}><option value="100x150">100 × 150 mm / 4×6</option><option value="80x50">80 × 50 mm</option><option value="100x100">100 × 100 mm</option></select></Field><div className="grid gap-2 sm:grid-cols-2">{[["shippingShowSender","Sender details",settings.shipping_show_sender],["shippingShowPhone","Customer phone",settings.shipping_show_phone],["shippingShowOrderNumber","Order number",settings.shipping_show_order_number],["shippingShowCod","COD / amount",settings.shipping_show_cod],["shippingShowItemCount","Item count",settings.shipping_show_item_count],["shippingShowBarcode","Order barcode",settings.shipping_show_barcode]].map(([n,l,c])=><label key={String(n)} className="flex items-center gap-2 rounded-xl border p-3 text-sm"><input name={String(n)} type="checkbox" defaultChecked={Boolean(c)} className="accent-blue-600"/>{String(l)}</label>)}</div></div></Card><div className="flex flex-wrap gap-3"><button className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white"><Save size={18}/>Save Shipping Label</button><Link href="/dashboard/shipping-labels" className="inline-flex items-center gap-2 rounded-xl border bg-white px-5 py-3 font-semibold"><PackageCheck size={18}/>Open Shipping Label Printer</Link></div></form>}
    {tab==="barcode"&&<form action={saveBarcodeLabelSettings} className="space-y-4"><Card icon={<Barcode size={20}/>} title="Barcode & product labels" sub="Configure product labels. Barcodes use the product barcode first, then SKU as a fallback."><div className="grid gap-4 md:grid-cols-2"><Field label="Label size"><select name="barcodeLabelSize" value={labelSize} onChange={e=>setLabelSize(e.target.value)} className={input}><option value="40x20">40 × 20 mm</option><option value="40x30">40 × 30 mm</option><option value="50x30">50 × 30 mm</option><option value="60x40">60 × 40 mm</option><option value="80x50">80 × 50 mm</option></select></Field><div className="grid gap-2 sm:grid-cols-2">{[["barcodeShowName","Product name",settings.barcode_show_name],["barcodeShowPrice","Price",settings.barcode_show_price],["barcodeShowSku","SKU / barcode text",settings.barcode_show_sku],["barcodeShowVariant","Size / color",settings.barcode_show_variant]].map(([n,l,c])=><label key={String(n)} className="flex items-center gap-2 rounded-xl border p-3 text-sm"><input name={String(n)} type="checkbox" defaultChecked={Boolean(c)} className="accent-blue-600"/>{String(l)}</label>)}</div></div></Card><div className="flex flex-wrap gap-3"><button className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white"><Save size={18}/>Save Label Settings</button><Link href="/dashboard/barcodes" className="inline-flex items-center gap-2 rounded-xl border bg-white px-5 py-3 font-semibold"><Barcode size={18}/>Open Barcode Printer</Link></div></form>}
   </section>
   <aside className="xl:sticky xl:top-6 xl:self-start"><div className="rounded-2xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><QrCode size={20}/></div><div><h2 className="font-bold">Live preview</h2><p className="text-xs text-slate-500">Preview updates as you change the main settings.</p></div></div>{tab==="receipt"?<ReceiptPreview business={business} store={storefront} paper={paper} header={header} footer={footer} qrLabel={qrLabel} returnPolicy={returnPolicy}/>:tab==="shipping"?<ShippingPreview business={business} store={storefront} size={shipSize}/>:<BarcodePreview size={labelSize}/>}</div></aside>
  </div>
 </main>;
}
const input="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100 dark:border-slate-700 dark:bg-slate-950";
function Card({icon,title,sub,children}:{icon:React.ReactNode;title:string;sub:string;children:React.ReactNode}){return <section className="rounded-2xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="mb-4 flex gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600">{icon}</div><div><h2 className="font-bold">{title}</h2><p className="text-sm text-slate-500">{sub}</p></div></div>{children}</section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-sm font-semibold">{label}</span>{children}</label>}
function Choice({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button type="button" onClick={onClick} className={`rounded-xl border px-3 py-2.5 text-sm font-semibold ${active?"border-blue-600 bg-blue-50 text-blue-700":"border-slate-200"}`}>{children}</button>}
function ReceiptPreview({business,store,paper,header,footer,qrLabel,returnPolicy}:{business:any;store:any;paper:string;header:string;footer:string;qrLabel:string;returnPolicy:string}){return <div className={`mx-auto mt-5 bg-white p-5 text-black shadow-xl ${paper==="58mm"?"max-w-[270px]":"max-w-[340px]"}`}><div className="text-center">{store.logo_url&&<img src={store.logo_url} alt="Logo" className="mx-auto mb-2 h-10 w-10 rounded-lg object-cover"/>}<p className="text-lg font-black">{store.display_name||business.name}</p>{header&&<p className="whitespace-pre-line text-[10px]">{header}</p>}<p className="text-[10px]">{store.address||"Business address"}</p><p className="text-[10px]">{store.phone||"Business phone"}</p></div><hr className="my-3 border-dashed"/><div className="flex justify-between text-[10px]"><b>Order #10028</b><span>Today</span></div><div className="mt-3 space-y-2 text-[10px]"><div className="flex justify-between"><span>1 × Product A</span><b>$8.50</b></div><div className="flex justify-between"><span>2 × Product B</span><b>$10.00</b></div></div><hr className="my-3 border-dashed"/><div className="space-y-1 text-[10px]"><div className="flex justify-between"><span>Subtotal</span><span>$18.50</span></div><div className="flex justify-between text-sm font-black"><span>Total</span><span>$18.50</span></div></div><hr className="my-3 border-dashed"/><div className="text-center text-[9px]"><div className="mx-auto grid h-16 w-16 grid-cols-5 gap-[2px] bg-white p-1">{Array.from({length:25}).map((_,i)=><span key={i} className={`${[0,1,4,5,6,8,10,12,14,16,18,20,21,22,24].includes(i)?"bg-black":"bg-white"}`}/>)}</div><b>{qrLabel}</b><p className="break-all">{business.storeUrl}</p>{footer&&<p className="mt-2 whitespace-pre-line">{footer}</p>}{returnPolicy&&<p className="mt-1 whitespace-pre-line">{returnPolicy}</p>}</div></div>}
function ShippingPreview({business,store,size}:{business:any;store:any;size:string}){return <div className="mx-auto mt-5 max-w-[340px] rounded border-2 border-slate-900 bg-white p-5 text-black shadow-xl"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase">From</p><p className="font-black">{store.display_name||business.name}</p><p className="text-[10px]">{store.address||"Business address"}</p></div><span className="rounded border px-2 py-1 text-[10px] font-bold">{size} mm</span></div><hr className="my-4 border-black"/><p className="text-[10px] font-bold uppercase">Ship to</p><p className="text-lg font-black">Sok Kim</p><p className="text-sm">+855 12 345 678</p><p className="mt-1 text-sm">123 Example Street, Phnom Penh, Cambodia</p><hr className="my-4 border-black"/><div className="grid grid-cols-2 gap-2 text-xs"><div><span className="text-slate-500">Order</span><p className="font-bold">#10028</p></div><div><span className="text-slate-500">Items</span><p className="font-bold">3</p></div><div><span className="text-slate-500">Payment</span><p className="font-bold">COD</p></div><div><span className="text-slate-500">Amount</span><p className="font-bold">$18.50</p></div></div><div className="mt-5 h-14 bg-[repeating-linear-gradient(90deg,#000_0,#000_2px,transparent_2px,transparent_4px,#000_4px,#000_5px,transparent_5px,transparent_8px)]"/><p className="mt-1 text-center text-xs tracking-[.25em]">10028</p></div>}
function BarcodePreview({size}:{size:string}){return <div className="mx-auto mt-8 w-fit border bg-white p-3 text-center text-black shadow-xl" style={{width:`${size.split("x")[0]}mm`,minHeight:`${size.split("x")[1]}mm`}}><p className="truncate text-[10px] font-bold">Sample Product</p><p className="text-[8px]">Black / Size 42</p><div className="mt-2 h-10 bg-[repeating-linear-gradient(90deg,#000_0,#000_2px,transparent_2px,transparent_4px,#000_4px,#000_5px,transparent_5px,transparent_8px)]"/><p className="text-[8px] tracking-wider">SKU-10028</p><p className="text-[11px] font-black">$18.50</p></div>}
