import Link from "next/link";
import { Building2, Search, ArrowUpRight, ChevronLeft, ChevronRight, Users, CheckCircle2, Clock3, PauseCircle } from "lucide-react";
import { requireSuperAdmin } from "@/lib/auth/require-super-admin";
import { expireDueBusinesses } from "@/lib/subscriptions/expire-businesses";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { readAllRows } from "@/lib/supabase/read-all-rows";
import { getSubscriptionPlanLabel } from "@/lib/subscriptions/plans";
import { businessListStatus, selectBusinessPage, type BusinessListRow, type BusinessStatus } from "@/lib/super-admin/business-list";

const statuses: Record<BusinessStatus, { label: string; color: string }> = {
  active: { label: "Active", color: "bg-emerald-50 text-emerald-700" },
  expired: { label: "Expired", color: "bg-rose-50 text-rose-700" },
  suspended: { label: "Suspended", color: "bg-amber-50 text-amber-800" },
  inactive: { label: "Inactive", color: "bg-slate-100 text-slate-600" },
};
function date(value: string | null) {
  return value && Number.isFinite(Date.parse(value)) ? new Intl.DateTimeFormat("en-GB", { day:"numeric",month:"short",year:"numeric",timeZone:"UTC" }).format(new Date(value)) : "Not set";
}
function Badge({ status }: { status: BusinessStatus }) { const item=statuses[status]; return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ${item.color}`}><span className="h-1.5 w-1.5 rounded-full bg-current"/>{item.label}</span>; }
function Avatar({ name }: { name: string }) { return <span aria-hidden className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-sm font-bold text-blue-700">{name.trim().slice(0,2).toUpperCase()}</span>; }

export default async function BusinessesPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  await requireSuperAdmin();
  await expireDueBusinesses();
  const params=await searchParams;
  const value=(key:string)=>typeof params[key]==="string"?params[key] as string:"";
  const search=value("search").trim().slice(0,160);
  const status=Object.hasOwn(statuses,value("status"))||["restricted","trial_ending"].includes(value("status"))?value("status"):"all";
  const sort=["name","expiry"].includes(value("sort"))?value("sort"):"newest";
  const result=await readAllRows<BusinessListRow>((from,to)=>supabaseAdmin.from("businesses").select("id,name,business_code,slug,owner_id,product_mode,is_active,disabled_reason,subscription_plan_key,subscription_user_limit,subscription_branch_limit,subscription_expires_at,max_staff,created_at,subscription_status,trial_expires_at").order("created_at",{ascending:false}).order("id").range(from,to));
  if(result.error)return <main role="alert" className="rounded-2xl border border-red-200 bg-white p-6">Unable to load businesses. Refresh to try again.</main>;
  const all=result.data??[];
  const now=new Date().getTime();
  const list=selectBusinessPage(all,{search,status,sort,page:Number(value("page")||1)},now);
  const ids=[...new Set(list.rows.map(b=>b.owner_id).filter((id):id is string=>Boolean(id)))];
  const owners=ids.length?await supabaseAdmin.from("profiles").select("id,full_name,email").in("id",ids):{data:[],error:null};
  const ownerMap=new Map((owners.data??[]).map(o=>[o.id,o]));
  const count=(s:BusinessStatus)=>all.filter(b=>businessListStatus(b,now)===s).length;
  function href(patch:Record<string,string>) { const query=new URLSearchParams({search,status,sort,...patch});for(const [key,val]of [...query])if(!val||val==="all"||val==="newest")query.delete(key);return `/super-admin/businesses?${query.toString()}`; }
  return <main className="space-y-5 pb-8">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Workspace directory</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Customer Businesses</h1><p className="mt-2 text-sm text-slate-500">Manage accounts, review subscriptions and open business details.</p></div><span className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-600"><Building2 size={15}/>{all.length} businesses</span></header>
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">
      {[{label:"All businesses",value:all.length,status:"all",icon:Building2,color:"text-blue-600 bg-blue-50"},{label:"Active",value:count("active"),status:"active",icon:CheckCircle2,color:"text-emerald-600 bg-emerald-50"},{label:"Expired",value:count("expired"),status:"expired",icon:Clock3,color:"text-rose-600 bg-rose-50"},{label:"Suspended",value:count("suspended"),status:"suspended",icon:PauseCircle,color:"text-amber-600 bg-amber-50"}].map(({label,value,icon:Icon,color,status:s})=><Link key={s} href={href({status:s,page:"1"})} aria-current={status===s?"page":undefined} className={`flex items-center gap-3 rounded-2xl border bg-white p-4 transition hover:border-blue-300 sm:p-5 ${status===s?"border-blue-300 ring-1 ring-blue-100":"border-slate-200"}`}><span className={`rounded-xl p-2.5 ${color}`}><Icon size={21}/></span><span><span className="block text-2xl font-bold tracking-tight text-slate-950">{value}</span><span className="text-xs font-medium text-slate-500">{label}</span></span></Link>)}
    </section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white">
      <form method="GET" className="flex flex-wrap items-center gap-3 border-b border-slate-100 p-4"><label className="relative min-w-0 flex-[1_1_260px]"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><span className="sr-only">Search businesses</span><input name="search" defaultValue={search} maxLength={160} placeholder="Search name, business code or store URL…" className="h-10 w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 pr-3 text-sm outline-none focus:border-blue-500 focus:bg-white"/></label><select aria-label="Business status" name="status" defaultValue={status} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="all">All statuses</option><option value="restricted">Inactive / suspended</option><option value="trial_ending">Trials ending soon</option>{Object.entries(statuses).map(([key,item])=><option key={key} value={key}>{item.label}</option>)}</select><select aria-label="Sort businesses" name="sort" defaultValue={sort} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="newest">Newest first</option><option value="name">Name A–Z</option><option value="expiry">Expiry date</option></select><button className="h-10 rounded-xl bg-blue-600 px-4 text-sm font-semibold text-white">Apply</button>{(search||status!=="all"||sort!=="newest")&&<Link href="/super-admin/businesses" className="px-2 text-sm font-semibold text-slate-500 hover:text-slate-900">Reset</Link>}</form>
      {owners.error&&<p role="alert" className="border-b border-amber-100 bg-amber-50 px-5 py-3 text-sm text-amber-800">Owner details could not be loaded. Business records are still available.</p>}
      {list.rows.length ? <>
        <div className="hidden md:block"><table className="w-full table-fixed text-left"><thead className="border-b border-slate-100 bg-slate-50/70 text-[11px] font-semibold uppercase tracking-wide text-slate-400"><tr><th className="w-[29%] px-5 py-3">Business</th><th className="w-[24%] px-4 py-3">Owner</th><th className="w-[25%] px-4 py-3">Subscription</th><th className="w-[15%] px-3 py-3">Status</th><th className="w-[7%] px-2 py-3"><span className="sr-only">View details</span></th></tr></thead><tbody className="divide-y divide-slate-100">{list.rows.map(b=>{const owner=b.owner_id?ownerMap.get(b.owner_id):null;return <tr key={b.id} className="group hover:bg-slate-50/70"><td className="px-5 py-5"><div className="flex items-center gap-3"><Avatar name={b.name}/><div className="min-w-0"><Link href={`/super-admin/businesses/${b.id}`} className="block break-words text-sm font-bold text-slate-900 hover:text-blue-600">{b.name}</Link><p className="mt-1 break-words text-xs text-slate-400">{b.business_code||b.slug}</p></div></div></td><td className="px-4 py-5"><p className="break-words text-sm font-medium text-slate-700">{owner?.full_name||"Owner"}</p><p className="mt-1 break-all text-xs text-slate-400">{owner?.email||(owners.error?"Unavailable":"No email")}</p></td><td className="px-4 py-5"><p className="text-sm font-semibold text-slate-800">{b.subscription_plan_key?getSubscriptionPlanLabel(b.subscription_plan_key):"Legacy plan"}</p><p className="mt-1 text-xs text-slate-500">{b.subscription_user_limit??b.max_staff+1} users · {b.subscription_branch_limit??1} branches</p><p className="mt-1 text-[11px] text-slate-400">Expires {date(b.subscription_expires_at)}</p></td><td className="px-3 py-5"><Badge status={businessListStatus(b,now)}/></td><td className="px-2 py-5"><Link href={`/super-admin/businesses/${b.id}`} aria-label={`View ${b.name}`} className="inline-flex rounded-xl border border-slate-200 p-2 text-slate-500 transition hover:border-blue-300 hover:bg-blue-50 hover:text-blue-600"><ArrowUpRight size={17}/></Link></td></tr>;})}</tbody></table></div>
        <div className="divide-y divide-slate-100 md:hidden">{list.rows.map(b=>{const owner=b.owner_id?ownerMap.get(b.owner_id):null;return <Link key={b.id} href={`/super-admin/businesses/${b.id}`} className="block p-4 hover:bg-slate-50"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><Avatar name={b.name}/><span className="min-w-0"><span className="block break-words font-bold">{b.name}</span><span className="mt-1 block text-xs text-slate-400">{b.business_code||b.slug}</span></span></div><Badge status={businessListStatus(b,now)}/></div><p className="mt-4 flex items-center gap-2 text-xs text-slate-500"><Users size={14}/><span className="break-all">{owner?.full_name||owner?.email||"Owner details unavailable"}</span></p><div className="mt-3 flex justify-between gap-3 text-xs"><span className="font-semibold text-slate-700">{b.subscription_plan_key?getSubscriptionPlanLabel(b.subscription_plan_key):"Legacy plan"}</span><span className="text-slate-400">Expires {date(b.subscription_expires_at)}</span></div></Link>;})}</div>
      </> : <div className="px-5 py-16 text-center"><Search className="mx-auto mb-4 text-slate-300" size={32}/><h2 className="font-bold text-slate-800">No businesses found</h2><p className="mt-2 text-sm text-slate-500">Try another search or reset your filters.</p><Link href="/super-admin/businesses" className="mt-4 inline-block text-sm font-semibold text-blue-600">Reset filters</Link></div>}
      <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 px-5 py-4"><p className="text-xs text-slate-500">{list.total?`${(list.page-1)*20+1}–${Math.min(list.page*20,list.total)}`:"0"} of {list.total} businesses</p><nav aria-label="Business pages" className="flex items-center gap-3">{list.page>1?<Link aria-label="Previous page" href={href({page:String(list.page-1)})} className="rounded-lg border border-slate-200 p-2"><ChevronLeft size={15}/></Link>:<span aria-disabled="true" className="rounded-lg border border-slate-100 p-2 text-slate-300"><ChevronLeft size={15}/></span>}<span className="text-xs font-medium text-slate-500">Page {list.page} of {list.pages}</span>{list.page<list.pages?<Link aria-label="Next page" href={href({page:String(list.page+1)})} className="rounded-lg border border-slate-200 p-2"><ChevronRight size={15}/></Link>:<span aria-disabled="true" className="rounded-lg border border-slate-100 p-2 text-slate-300"><ChevronRight size={15}/></span>}</nav></footer>
    </section>
  </main>;
}
