import type { SaleReceipt, ShippingDetails } from '../../pos/pos-workspace-types';
export type DetailItem={id:string;product_id:string|null;product_name:string|null;quantity:number;unit_price:number;subtotal:number;variant_label:string|null;selected_options:Array<{id?:string;name?:string;groupName?:string;priceAdjustment?:number}>|null;products:{name:string;sku:string|null;image_url:string|null}|Array<{name:string;sku:string|null;image_url:string|null}>|null};
export type DetailCustomer={id:string;name:string;phone:string|null;address:string|null;email?:string|null;loyalty_points:number};
export type DetailedOrder={id:string;order_number:string;business_id:string;customer_id:string|null;location_id:string|null;owner_id:string;subtotal:number;discount:number;delivery_fee:number;total:number;amount_paid:number;change_amount:number;remaining_balance:number;payment_method:string;payment_status:string|null;payment_reference:string|null;status:string;order_source:string;online_status:string|null;fulfillment_type:string|null;guest_name:string|null;guest_phone:string|null;guest_address:string|null;customer_note:string|null;created_at:string;updated_at:string|null;archived_at?:string|null;pos_checkout:{receipt?:SaleReceipt;createdBy?:string;method?:string;shipping?:ShippingDetails}|null;customers:DetailCustomer|DetailCustomer[]|null;order_items:DetailItem[]};
export function one<T>(value:T|T[]|null):T|null{return Array.isArray(value)?value[0] || null:value;}
export function numeric(value:unknown){const n=Number(value);return Number.isFinite(n)?n:0;}
export function paymentName(order:DetailedOrder){const method=order.pos_checkout?.method || order.payment_method;const labels:Record<string,string>={cash:'Cash',cod:'Cash on delivery (COD)',deposit:'Cash deposit',bank_transfer:'Bank transfer',other:'Other payment',credit:'Customer credit',split:'Split payment',khqr:'KHQR'};return labels[method] || method.replaceAll('_',' ');}
export function orderType(order:DetailedOrder){const v=order.pos_checkout?.receipt?.shipping?.method || order.pos_checkout?.shipping?.method || order.fulfillment_type;return v==='delivery'?'Delivery':v==='pickup'?'Pickup':v==='dine_in'?'Dine-in':'In-store';}
export function titleCase(v:string){return v.replaceAll('_',' ').replace(/\b[a-z]/g,c=>c.toUpperCase());}
export function recordReceipt(order:DetailedOrder,businessName:string,currency:string,branchName:string):SaleReceipt {
 const original=order.pos_checkout?.receipt;
 if(original?.orderId===order.id && Array.isArray(original.lines)) return original;
 const customer=one(order.customers);
 return {isOrderRecord:true,orderId:order.id,orderNumber:order.order_number,createdAt:order.created_at,businessName,branchName,customerName:order.guest_name || customer?.name || 'Walk-in customer',currency,
  subtotal:numeric(order.subtotal),manualDiscount:numeric(order.discount),discount:numeric(order.discount),deliveryFee:numeric(order.delivery_fee),taxRate:0,taxAmount:0,total:numeric(order.total),amountPaid:numeric(order.amount_paid),change:numeric(order.change_amount),remaining:numeric(order.remaining_balance),pointsRedeemed:0,pointsEarned:0,note:order.customer_note || '',tenders:[],
  shipping:{method:order.fulfillment_type==='delivery'?'delivery':order.fulfillment_type==='pickup'?'pickup':'in_store',recipientName:order.guest_name || customer?.name || '',phone:order.guest_phone || customer?.phone || '',address:order.guest_address || customer?.address || ''},
  lines:(order.order_items || []).map(i=>({name:i.product_name || one(i.products)?.name || 'Product',variant:i.variant_label,quantity:numeric(i.quantity),unitPrice:numeric(i.unit_price),subtotal:numeric(i.subtotal),options:(i.selected_options || []).map(o=>({id:o.id || '',name:o.name || '',groupName:o.groupName || '',priceAdjustment:numeric(o.priceAdjustment)}))}))};
}
