"use client";
import { useMemo, useState } from "react";
import { Printer, Search } from "lucide-react";
import { code39Bars } from "@/lib/barcode/code39";
type Product={id:string;name:string;sku:string|null;barcode:string|null;selling_price:number;size:string|null;color:string|null};
export default function BarcodeLabelsClient({products}:{products:Product[]}){
 const [q,setQ]=useState(""); const [selected,setSelected]=useState<string[]>([]); const [labelSize,setLabelSize]=useState("40x30");
 const filtered=useMemo(()=>products.filter(p=>`${p.name} ${p.sku??""} ${p.barcode??""}`.toLowerCase().includes(q.toLowerCase())),[products,q]);
 function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);}
 const chosen=products.filter(p=>selected.includes(p.id));
 return <main><div className="mb-6"><h1 className="text-3xl font-bold">Barcode & Label Printing</h1><p className="mt-1 text-slate-500">Print scan-ready Code 39 labels for products and exact variants.</p></div>
 <div className="grid gap-6 xl:grid-cols-[1fr_420px]"><section className="rounded-2xl border bg-white p-5"><div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search product, SKU or barcode" className="w-full rounded-xl border py-2.5 pl-10 pr-3"/></div><div className="mt-4 divide-y">{filtered.map(p=><label key={p.id} className="flex items-center gap-3 py-3"><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>toggle(p.id)}/><div className="min-w-0 flex-1"><p className="font-semibold">{p.name}</p><p className="text-xs text-slate-500">{[p.color,p.size&&`Size ${p.size}`,p.sku].filter(Boolean).join(" · ")}</p></div><span className="text-sm font-bold">${Number(p.selling_price).toFixed(2)}</span></label>)}</div></section>
 <aside className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Label preview</h2><select value={labelSize} onChange={e=>setLabelSize(e.target.value)} className="rounded-lg border px-2 py-1"><option value="40x30">40×30 mm</option><option value="50x30">50×30 mm</option><option value="40x20">40×20 mm</option></select></div><div id="barcode-print-area" className="mt-4 grid gap-3">{chosen.map(p=><BarcodeLabel key={p.id} p={p} size={labelSize}/>)}</div><button onClick={()=>window.print()} disabled={!chosen.length} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white disabled:opacity-40"><Printer size={18}/>Print {chosen.length} label{chosen.length===1?"":"s"}</button></aside></div>
 <style jsx global>{`@media print{body *{visibility:hidden!important}#barcode-print-area,#barcode-print-area *{visibility:visible!important}#barcode-print-area{position:absolute;left:0;top:0;display:block}.barcode-label{break-inside:avoid;margin:0 0 2mm 0}}`}</style></main>
}
function BarcodeLabel({p,size}:{p:Product;size:string}){const value=p.barcode||p.sku||p.id.slice(0,12);const data=code39Bars(value);const [w,h]=size.split("x").map(Number);return <div className="barcode-label border bg-white p-2 text-center" style={{width:`${w}mm`,minHeight:`${h}mm`}}><div className="truncate text-[10px] font-bold">{p.name}</div><div className="text-[8px]">{[p.color,p.size].filter(Boolean).join(" / ")}</div><svg viewBox={`0 0 ${data.width} 44`} className="mt-1 h-8 w-full" preserveAspectRatio="none">{data.bars.map((b,i)=><rect key={i} x={b.x} y="0" width={b.width} height="44" fill="black"/>)}</svg><div className="text-[8px] tracking-wider">{data.text}</div><div className="text-[10px] font-bold">${Number(p.selling_price).toFixed(2)}</div></div>}
