"use client";
import { useRef, useState, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, ChartNoAxesColumnIncreasing, CircleDollarSign, Receipt, Search, Trash2, ChevronLeft, ChevronRight } from "lucide-react";
import { createExpense, deleteExpense } from "./actions";
import { CATEGORIES, categoryName, categoryTotals, money, sum, type Expense, type Branch } from "./expense-model";
const input="w-full min-w-0 rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100";
const panel="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm";
export default function ExpensesClient({expenses,branches,today,defaultBranchId}:{expenses:Expense[];branches:Branch[];today:string;defaultBranchId:string}) {
 const router=useRouter(); const form=useRef<HTMLFormElement>(null);
 const [branch,setBranch]=useState(defaultBranchId);const [from,setFrom]=useState(today.slice(0,7)+"-01");const [to,setTo]=useState(today);const [query,setQuery]=useState("");const [category,setCategory]=useState("");const [page,setPage]=useState(1);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
 const branchRows=expenses.filter(e=>!branch || (branch==="unassigned"?!e.location_id:e.location_id===branch));
 const period=branchRows.filter(e=>(!from||e.expense_date>=from)&&(!to||e.expense_date<=to));
 const filtered=period.filter(e=>(!category||categoryName(e.category)===category)&&[e.description,e.payee,e.reference,categoryName(e.category)].some(v=>v?.toLowerCase().includes(query.toLowerCase())));
 const pages=Math.max(1,Math.ceil(filtered.length/10));const current=Math.min(page,pages);const rows=filtered.slice((current-1)*10,current*10);const chart=categoryTotals(period);const total=sum(period);let angle=0;const stops=chart.map(c=>{const start=angle;angle+=total?c.value/total*360:0;return `${c.color} ${start}deg ${angle}deg`;}).join(",");
 const active=branches.filter(b=>b.is_active);const categoryOptions=Array.from(new Set([...CATEGORIES,...expenses.map(e=>categoryName(e.category))]));
 async function save(data:FormData){if(busy)return;setBusy(true);setError("");setMessage("");try{await createExpense(data);form.current?.reset();setMessage("Expense saved.");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Unable to save expense.");}finally{setBusy(false);}}
 async function remove(expense:Expense){if(busy||!window.confirm(`Delete ${expense.description} (${money(Number(expense.amount))})?`))return;setBusy(true);setError("");try{const data=new FormData();data.set("expenseId",expense.id);await deleteExpense(data);setMessage("Expense deleted.");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Unable to delete expense.");}finally{setBusy(false);}}
 function resetPage(){setPage(1);}
 return <main className="space-y-5 text-slate-900">
  <header className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-bold tracking-tight">Expenses</h1><p className="mt-1 text-sm text-slate-500">Record and track business expenses</p></div><div className="flex flex-wrap items-end gap-3"><label className="text-xs font-semibold text-slate-500">Choose Branch<select aria-label="Filter expenses by branch" value={branch} onChange={e=>{setBranch(e.target.value);resetPage();}} className={`${input} mt-1`}><option value="">All branches</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}{!b.is_active?" (inactive)":""}</option>)}<option value="unassigned">Unassigned</option></select></label></div></header>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Today's Expenses" value={money(sum(branchRows.filter(e=>e.expense_date===today)))} detail="Recorded today" icon={<CalendarDays/>} color="bg-blue-50 text-blue-600"/><Metric title="This Month" value={money(sum(branchRows.filter(e=>e.expense_date.startsWith(today.slice(0,7)))))} detail="Current calendar month" icon={<ChartNoAxesColumnIncreasing/>} color="bg-emerald-50 text-emerald-600"/><Metric title="Total Expenses" value={money(sum(branchRows))} detail="Across all time" icon={<CircleDollarSign/>} color="bg-violet-50 text-violet-600"/><Metric title="Selected Period" value={money(total)} detail={`${period.length} expense records`} icon={<Receipt/>} color="bg-orange-50 text-orange-600"/></div>
  {(message||error)&&<p role={error?"alert":"status"} className={`rounded-xl p-3 text-sm ${error?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{error||message}</p>}
  <div className="grid items-start gap-5 xl:grid-cols-[360px_minmax(0,1fr)] 2xl:grid-cols-[400px_minmax(0,1fr)]">
   <section className={panel}><Heading icon={<Receipt size={21}/>} title="Add Expense" text="Record a new business expense"/><form ref={form} action={save} className="mt-5 grid grid-cols-2 gap-4">
    <Field title="Branch" required wide><select name="locationId" required defaultValue={defaultBranchId} className={input}><option value="" disabled>Choose branch</option>{active.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field>
    {!active.length&&<p className="col-span-2 text-sm text-amber-700">Activate a branch in Branch Settings before recording expenses.</p>}
    <Field title="Category" required wide><select name="category" required defaultValue="" className={input}><option value="" disabled>Select category</option>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></Field>
    <Field title="Description" required wide><input name="description" required maxLength={500} placeholder="e.g. Office supplies, Monthly rent" className={input}/></Field>
    <Field title="Amount ($)" required><input name="amount" type="number" min="0.01" max="999999999.99" step="0.01" required placeholder="0.00" className={input}/></Field>
    <Field title="Expense Date" required><input name="expenseDate" type="date" required defaultValue={today} className={input}/></Field>
    <Field title="Payment Method"><select name="paymentMethod" defaultValue="cash" className={input}><option value="cash">Cash</option><option value="bank_transfer">Bank Transfer</option><option value="card">Card</option><option value="other">Other</option></select></Field>
    <Field title="Vendor"><input name="payee" maxLength={200} placeholder="Who was paid?" className={input}/></Field>
    <Field title="Reference / Receipt No." wide><input name="reference" maxLength={200} placeholder="e.g. INV-001" className={input}/></Field>
    <Field title="Upload Receipt (optional)" wide><input name="receipt" type="file" accept="image/jpeg,image/png,application/pdf" className={`${input} border-dashed bg-slate-50 py-5`} onChange={e=>{const file=e.target.files?.[0];e.target.setCustomValidity(file && file.size>5*1024*1024?"Receipt must be 5 MB or smaller.":"");e.target.reportValidity();}}/><span className="mt-2 block text-xs font-normal text-slate-500">JPG, PNG or PDF · Up to 5 MB</span></Field>
    <button disabled={busy||!active.length} className="col-span-2 mt-1 rounded-lg bg-blue-600 p-3 text-sm font-semibold text-white hover:bg-blue-700 disabled:opacity-50">{busy?"Please wait…":"Save Expense"}</button>
   </form></section>
   <div className="min-w-0 space-y-5"><section className={panel}><div className="flex flex-wrap items-start justify-between gap-4"><Heading icon={<ChartNoAxesColumnIncreasing size={21}/>} title="Expense Overview" text="Spending by category for the selected period"/><div className="flex flex-wrap items-center gap-2"><label className="text-xs text-slate-500">From<input aria-label="Start date" type="date" value={from} max={to||undefined} onChange={e=>{setFrom(e.target.value);resetPage();}} className={`${input} mt-1`}/></label><label className="text-xs text-slate-500">To<input aria-label="End date" type="date" value={to} min={from||undefined} onChange={e=>{setTo(e.target.value);resetPage();}} className={`${input} mt-1`}/></label></div></div>
    <div className="mt-6 grid items-center gap-6 md:grid-cols-[220px_minmax(0,1fr)]"><div role="img" aria-label={`Expense breakdown. Total ${money(total)}. ${chart.map(c=>`${c.name}: ${money(c.value)}`).join(". ")}`} className="relative mx-auto flex h-48 w-48 items-center justify-center rounded-full" style={{background:total?`conic-gradient(${stops})`:"#e2e8f0"}}><div className="flex h-32 w-32 flex-col items-center justify-center rounded-full bg-white"><strong className="max-w-28 break-all text-center text-lg font-bold">{money(total)}</strong><span className="text-xs text-slate-500">Total</span></div></div><div className="max-h-64 space-y-3 overflow-y-auto pr-1">{chart.length?chart.map(c=><div key={c.name} className="grid grid-cols-[12px_minmax(0,1fr)_44px_90px] items-center gap-2 text-xs"><span className="h-2.5 w-2.5 rounded-full" style={{background:c.color}}/><span>{c.name}</span><span className="text-right text-slate-500">{total?(c.value/total*100).toFixed(1):0}%</span><strong className="text-right">{money(c.value)}</strong></div>):<p className="text-sm text-slate-500">No expenses in this period. Choose another date range or add an expense.</p>}</div></div>
   </section>
   <section className={panel}><Heading icon={<Receipt size={21}/>} title="Expense History" text="View and manage all recorded expenses"/><div className="my-5 flex flex-wrap gap-3"><div className="relative min-w-48 flex-1"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input aria-label="Search expenses" placeholder="Search expenses…" value={query} onChange={e=>{setQuery(e.target.value);resetPage();}} className={`${input} pl-9`}/></div><select aria-label="Filter by category" value={category} onChange={e=>{setCategory(e.target.value);resetPage();}} className={`${input} sm:max-w-56`}><option value="">All Categories</option>{categoryOptions.map(c=><option key={c}>{c}</option>)}</select></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{["Date","Category","Branch","Vendor / Description","Payment Method","Amount","Actions"].map(c=><th key={c} className="px-3 py-3 font-semibold">{c}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map(e=><tr key={e.id} className="hover:bg-slate-50"><td className="whitespace-nowrap px-3 py-4">{new Intl.DateTimeFormat("en-US",{timeZone:"UTC",month:"short",day:"2-digit",year:"numeric"}).format(new Date(`${e.expense_date}T00:00:00Z`))}</td><td className="px-3 py-4"><span className="rounded-md bg-blue-50 px-2 py-1 text-blue-700">{categoryName(e.category)}</span></td><td className="px-3 py-4">{branches.find(b=>b.id===e.location_id)?.name||"Unassigned"}</td><td className="max-w-64 break-words px-3 py-4"><p className="font-medium">{e.description}</p><p className="mt-1 text-slate-500">{[e.payee,e.reference].filter(Boolean).join(" · ")}</p></td><td className="px-3 py-4 capitalize">{e.payment_method?.replaceAll("_"," ")||"—"}</td><td className="whitespace-nowrap px-3 py-4 font-semibold">{money(Number(e.amount))}</td><td className="px-3 py-4">{e.has_receipt&&<a href={`/dashboard/expenses/${e.id}/receipt`} target="_blank" rel="noopener noreferrer" className="mr-2 inline-block text-blue-600 underline">View receipt</a>}<button type="button" disabled={busy} onClick={()=>remove(e)} aria-label={`Delete ${e.description}`} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600 disabled:opacity-50"><Trash2 size={15}/></button></td></tr>)}</tbody></table>{!rows.length&&<p className="py-12 text-center text-sm text-slate-500">No expenses match these filters.</p>}</div>
    <footer className="mt-4 flex items-center justify-between gap-3 text-xs text-slate-500"><span>Showing {filtered.length?(current-1)*10+1:0}–{Math.min(current*10,filtered.length)} of {filtered.length} expenses</span><div className="flex items-center gap-2"><button aria-label="Previous page" disabled={current===1} onClick={()=>setPage(current-1)} className="rounded-lg border p-2 disabled:opacity-30"><ChevronLeft size={15}/></button><span className="rounded-lg bg-blue-50 px-3 py-2 font-semibold text-blue-600">{current}</span><button aria-label="Next page" disabled={current===pages} onClick={()=>setPage(current+1)} className="rounded-lg border p-2 disabled:opacity-30"><ChevronRight size={15}/></button></div></footer>
   </section></div>
  </div>
 </main>;
}
function Field({title,required,wide,children}:{title:string;required?:boolean;wide?:boolean;children:ReactNode}){return <label className={`${wide?"col-span-2":""} block min-w-0 text-xs font-medium`}><span className="mb-1.5 block">{title}{required&&<span className="ml-1 text-red-500">*</span>}</span>{children}</label>;}
function Heading({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <div className="flex items-center gap-3"><span className="rounded-xl bg-blue-50 p-3 text-blue-600">{icon}</span><div><h2 className="font-bold">{title}</h2><p className="mt-0.5 text-xs text-slate-500">{text}</p></div></div>;}
function Metric({title,value,detail,icon,color}:{title:string;value:string;detail:string;icon:ReactNode;color:string}){return <div className={`${panel} flex items-center gap-4`}><span className={`rounded-xl p-4 ${color}`}>{icon}</span><div className="min-w-0"><p className="text-xs text-slate-500">{title}</p><strong className="mt-1 block break-words text-xl font-bold">{value}</strong><p className="mt-1 text-xs text-slate-400">{detail}</p></div></div>;}
