"use client";
import { formatUiText } from "@/lib/i18n/translations";
import { useLanguage } from "@/components/providers/language-provider";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { CalendarDays, ChartNoAxesColumnIncreasing, CircleDollarSign, Receipt, Search, Trash2, ChevronLeft, ChevronRight, Plus, SlidersHorizontal, Store, X, House, Zap, Users, Megaphone, Truck, Paperclip, ShoppingBag, Wrench, MonitorSmartphone, Landmark, FileText, Briefcase, Phone, Plane, Utensils, SprayCan, type LucideIcon } from "lucide-react";
import { createExpense, deleteExpense } from "./actions";
import { dateRangeError } from "@/lib/date-range";
import { CATEGORIES, categoryName, categoryTotals, money, sum, type Expense, type Branch } from "./expense-model";
const input="w-full min-w-0 rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100";
const panel="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm";
// A Home Screen app opens _blank links in a separate browser without this session; stay in the app there.
const openReceiptInApp=(event:React.MouseEvent<HTMLAnchorElement>)=>{if(matchMedia("(display-mode: standalone)").matches||(navigator as Navigator&{standalone?:boolean}).standalone){event.preventDefault();location.assign(event.currentTarget.href);}};
export default function ExpensesClient({expenses,branches,today,defaultBranchId}:{expenses:Expense[];branches:Branch[];today:string;defaultBranchId:string}) {
  const { t: translateText } = useLanguage();
 const form=useRef<HTMLFormElement>(null);
 const [branch,setBranch]=useState(defaultBranchId);const [from,setFrom]=useState(today.slice(0,7)+"-01");const [to,setTo]=useState(today);const [query,setQuery]=useState("");const [category,setCategory]=useState("");const [page,setPage]=useState(1);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
 const branchRows=expenses.filter(e=>!branch || (branch==="unassigned"?!e.location_id:e.location_id===branch));
 const period=branchRows.filter(e=>(!from||e.expense_date>=from)&&(!to||e.expense_date<=to));
 const filtered=period.filter(e=>(!category||categoryName(e.category)===category)&&[e.description,e.payee,e.reference,categoryName(e.category)].some(v=>v?.toLowerCase().includes(query.toLowerCase())));
 const pages=Math.max(1,Math.ceil(filtered.length/10));const current=Math.min(page,pages);const rows=filtered.slice((current-1)*10,current*10);const chart=categoryTotals(period);const total=sum(period);let angle=0;const stops=chart.map(c=>{const start=angle;angle+=total?c.value/total*360:0;return `${c.color} ${start}deg ${angle}deg`;}).join(",");
 const active=branches.filter(b=>b.is_active);const categoryOptions=Array.from(new Set([...CATEGORIES,...expenses.map(e=>categoryName(e.category))]));
 async function save(data:FormData){if(busy)return;setBusy(true);setError("");setMessage("");try{await createExpense(data);form.current?.reset();setMessage("Expense saved.");setSheet(null);}catch(e){setError(e instanceof Error?e.message:"Unable to save expense.");}finally{setBusy(false);}}
 async function remove(expense:Expense){if(busy||!window.confirm(translateText(`Delete ${expense.description} (${money(Number(expense.amount))})?`)))return;setBusy(true);setError("");try{const data=new FormData();data.set("expenseId",expense.id);await deleteExpense(data);setMessage("Expense deleted.");}catch(e){setError(e instanceof Error?e.message:"Unable to delete expense.");}finally{setBusy(false);}}
 function resetPage(){setPage(1);}
 // Phones: Filter opens a bottom sheet and Add Expense a centred popup.
 const [sheet,setSheet]=useState<"filter"|"add"|"overview"|null>(null);
 const [detail,setDetail]=useState<Expense|null>(null);
 function seeAll(){setQuery("");setCategory("");setFrom("");setTo("");setDateDraft(null);resetPage();}
 // Filter edits stay drafts (null = showing applied values) until Apply. Desktop dates and the phone sheet each keep one.
 const [dateDraft,setDateDraft]=useState<{from:string;to:string}|null>(null);const dateError=dateDraft?dateRangeError(dateDraft.from,dateDraft.to):"";
 const [sheetDraft,setSheetDraft]=useState<{branch:string;category:string;from:string;to:string}|null>(null);const draft=sheetDraft??{branch,category,from,to};const sheetError=dateRangeError(draft.from,draft.to);
 function applyDates(){if(!dateDraft||dateError)return;setFrom(dateDraft.from);setTo(dateDraft.to);setDateDraft(null);resetPage();}
 function applySheet(){if(sheetError)return;if(sheetDraft){setBranch(sheetDraft.branch);setCategory(sheetDraft.category);setFrom(sheetDraft.from);setTo(sheetDraft.to);resetPage();}setSheetDraft(null);setSheet(null);}
 function closeSheet(){setSheetDraft(null);setSheet(null);}
 useEffect(()=>{if(!sheet)return;const overflow=document.body.style.overflow;document.body.style.overflow="hidden";const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setSheet(null);};const wide=window.matchMedia("(min-width: 640px)");const onWide=()=>{if(wide.matches)setSheet(null);};window.addEventListener("keydown",onKey);wide.addEventListener("change",onWide);return()=>{document.body.style.overflow=overflow;window.removeEventListener("keydown",onKey);wide.removeEventListener("change",onWide);};},[sheet]);
 function rangeFor(kind:string):[string,string]{const d=new Date(`${today}T00:00:00Z`);const iso=(x:Date)=>x.toISOString().slice(0,10);let start=today,end=today;if(kind==="yesterday"){d.setUTCDate(d.getUTCDate()-1);start=end=iso(d);}else if(kind==="week"){const w=new Date(d);w.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));start=iso(w);}else if(kind==="month"){start=today.slice(0,7)+"-01";}else if(kind==="year"){start=today.slice(0,4)+"-01-01";}return [start,end];}
 return <main className="space-y-5 text-slate-900">
  <header className="flex flex-wrap items-center justify-between gap-4 max-sm:hidden"><div><h1 className="text-3xl font-bold tracking-tight">Expenses</h1><p className="mt-1 text-sm text-slate-500">Record and track business expenses</p></div><div className="flex flex-wrap items-end gap-3"><label className="text-xs font-semibold text-slate-500">Choose Branch<select aria-label="Filter expenses by branch" value={branch} onChange={e=>{setBranch(e.target.value);resetPage();}} className={`${input} mt-1`}><option value="">All branches</option>{branches.map(b=><option key={b.id} value={b.id} data-i18n-ignore="true">{b.name}{!b.is_active ? (translateText(" (inactive)")) : ("")}</option>)}<option value="unassigned">Unassigned</option></select></label></div></header>
  <div className="grid gap-4 max-lg:grid-cols-4 max-lg:gap-2 sm:grid-cols-2 xl:grid-cols-4"><Metric short="Today" title="Today's Expenses" value={money(sum(branchRows.filter(e=>e.expense_date===today)))} detail="Recorded today" icon={<CalendarDays/>} color="bg-blue-50 text-blue-600"/><Metric short="This Month" title="This Month" value={money(sum(branchRows.filter(e=>e.expense_date.startsWith(today.slice(0,7)))))} detail="Current calendar month" icon={<ChartNoAxesColumnIncreasing/>} color="bg-emerald-50 text-emerald-600"/><Metric short="Total" title="Total Expenses" value={money(sum(branchRows))} detail="Across all time" icon={<CircleDollarSign/>} color="bg-violet-50 text-violet-600"/><Metric short="Selected" title="Selected Period" value={money(total)} detail={`${period.length} expense records`} icon={<Receipt/>} color="bg-orange-50 text-orange-600"/></div>
  {(message||error)&&<p role={error?"alert":"status"} className={`rounded-xl p-3 text-sm ${error?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{error||message}</p>}
  <div className="grid items-start gap-5 xl:grid-cols-[360px_minmax(0,1fr)] 2xl:grid-cols-[400px_minmax(0,1fr)]">
   <div role={sheet==="add"?"dialog":undefined} aria-modal={sheet==="add"||undefined} aria-label="Add expense" data-sheet="center" className={`${sheet==="add"?"fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-3":"max-sm:hidden"} sm:contents`}>
   <section className={`${panel} relative max-sm:max-h-[90dvh] max-sm:w-full max-sm:overflow-y-auto`}>{sheet==="add"&&<button type="button" aria-label="Close add expense" onClick={()=>setSheet(null)} className="absolute right-3 top-3 grid h-11 w-11 place-items-center rounded-full bg-slate-100 text-slate-600 sm:hidden"><X size={20}/></button>}<Heading icon={<Receipt size={21}/>} title="Add Expense" text="Record a new business expense"/><form ref={form} action={save} className="mt-5 grid grid-cols-2 gap-4">
    <Field title="Branch" required wide><select name="locationId" required defaultValue={defaultBranchId} className={input}><option value="" disabled>Choose branch</option>{active.map(b=><option key={b.id} value={b.id} data-i18n-ignore="true">{b.name}</option>)}</select></Field>
    {!active.length&&<p className="col-span-2 text-sm text-amber-700">Activate a branch in Branch Settings before recording expenses.</p>}
    <Field title="Category" required wide><select name="category" required defaultValue="" className={input}><option value="" disabled>Select category</option>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></Field>
    <Field title="Description" required wide><input name="description" required maxLength={500} placeholder="e.g. Office supplies, Monthly rent" className={input}/></Field>
    <Field title="Amount ($)" required><input name="amount" type="number" min="0.01" max="999999999.99" step="0.01" required placeholder="0.00" className={input}/></Field>
    <Field title="Expense Date" required><input name="expenseDate" type="date" required defaultValue={today} className={input}/></Field>
    <Field title="Payment Method"><select name="paymentMethod" defaultValue="cash" className={input}><option value="cash">Cash</option><option value="bank_transfer">Bank Transfer</option><option value="card">Card</option><option value="other">Other</option></select></Field>
    <Field title="Vendor"><input name="payee" maxLength={200} placeholder="Who was paid?" className={input}/></Field>
    <Field title="Reference / Receipt No." wide><input name="reference" maxLength={200} placeholder="e.g. INV-001" className={input}/></Field>
    <Field title="Upload Receipt (optional)" wide><input name="receipt" type="file" accept="image/jpeg,image/png,application/pdf" className={`${input} border-dashed bg-slate-50 py-5`} onChange={e=>{const file=e.target.files?.[0];e.target.setCustomValidity(translateText(file && file.size>5*1024*1024?"Receipt must be 5 MB or smaller.":""));e.target.reportValidity();}}/><span className="mt-2 block text-xs font-normal text-slate-500">JPG, PNG or PDF · Up to 5 MB</span></Field>
    <button disabled={busy||!active.length} className="col-span-2 mt-1 rounded-lg bg-blue-600 p-3 text-sm font-semibold text-white hover:bg-blue-700 disabled:opacity-50">{busy?"Please wait…":"Save Expense"}</button>
   </form></section>
   </div>
   <div className="min-w-0 space-y-5"><div role={sheet==="overview"?"dialog":undefined} aria-modal={sheet==="overview"||undefined} aria-label="Expense overview" data-sheet="center" className={`${sheet==="overview"?"fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-3":"max-sm:hidden"} sm:contents`}><section className={`${panel} relative max-sm:max-h-[90dvh] max-sm:w-full max-sm:overflow-y-auto`}>{sheet==="overview"&&<button type="button" aria-label="Close expense overview" onClick={()=>setSheet(null)} className="absolute right-3 top-3 z-10 grid h-11 w-11 place-items-center rounded-full bg-slate-100 text-slate-600 sm:hidden"><X size={20}/></button>}<div className="flex flex-wrap items-start justify-between gap-4 max-sm:flex-col max-sm:items-start max-sm:pr-12"><Heading icon={<ChartNoAxesColumnIncreasing size={21}/>} title="Expense Overview" text="Spending by category for the selected period"/><label className="flex w-full min-w-0 items-center gap-1.5 sm:hidden"><Store size={16} className="shrink-0 text-blue-600"/><select aria-label="Filter expenses by branch" value={branch} onChange={e=>{setBranch(e.target.value);resetPage();}} className={`${input} py-2`}><option value="">All branches</option>{branches.map(b=><option key={b.id} value={b.id} data-i18n-ignore="true">{b.name}{!b.is_active ? (translateText(" (inactive)")) : ("")}</option>)}<option value="unassigned">Unassigned</option></select></label><div className="flex flex-wrap items-center gap-2 max-sm:hidden"><label className="text-xs text-slate-500">From<input aria-label="Start date" type="date" value={dateDraft?.from??from} max={(dateDraft?.to??to)||undefined} onChange={e=>setDateDraft({from:e.target.value,to:dateDraft?.to??to})} className={`${input} mt-1`}/></label><label className="text-xs text-slate-500">To<input aria-label="End date" type="date" value={dateDraft?.to??to} min={(dateDraft?.from??from)||undefined} onChange={e=>setDateDraft({from:dateDraft?.from??from,to:e.target.value})} className={`${input} mt-1`}/></label>{dateDraft&&<div className="flex items-center gap-2 self-end">{dateError&&<p role="alert" className="text-xs font-semibold text-red-600">{dateError}</p>}<button type="button" onClick={()=>setDateDraft(null)} className="h-10 rounded-xl border border-slate-200 px-3 text-xs font-semibold text-slate-600">Cancel</button><button type="button" onClick={applyDates} disabled={Boolean(dateError)} className="h-10 rounded-xl bg-blue-600 px-4 text-xs font-semibold text-white disabled:opacity-50">Apply dates</button></div>}</div></div>
    <div className="mt-6 grid items-center gap-6 md:grid-cols-[220px_minmax(0,1fr)]"><div role="img" aria-label={`Expense breakdown. Total ${money(total)}. ${chart.map(c=>`${c.name}: ${money(c.value)}`).join(". ")}`} className="relative mx-auto flex h-48 w-48 items-center justify-center rounded-full" style={{background:total?`conic-gradient(${stops})`:"#e2e8f0"}}><div className="flex h-32 w-32 flex-col items-center justify-center rounded-full bg-white"><strong className="max-w-28 break-all text-center text-lg font-bold">{money(total)}</strong><span className="text-xs text-slate-500">Total</span></div></div><div className="max-h-64 space-y-3 overflow-y-auto pr-1">{chart.length?chart.map(c=><div key={c.name} className="grid grid-cols-[12px_minmax(0,1fr)_44px_90px] items-center gap-2 text-xs"><span className="h-2.5 w-2.5 rounded-full" style={{background:c.color}}/><span>{c.name}</span><span className="text-right text-slate-500">{total?(c.value/total*100).toFixed(1):0}%</span><strong className="text-right">{money(c.value)}</strong></div>):<p className="text-sm text-slate-500">No expenses in this period. Choose another date range or add an expense.</p>}</div></div>
   </section></div>
   <section className={`${panel} max-lg:p-4`}><div className="max-lg:hidden"><Heading icon={<Receipt size={21}/>} title="Expense History" text="View and manage all recorded expenses"/></div><div className="flex items-center justify-between lg:hidden"><h2 className="text-lg font-bold">Expense History</h2><button type="button" onClick={seeAll} className="text-sm font-semibold text-blue-600">See all</button></div><div className="my-5 flex flex-wrap gap-3 max-lg:my-3 max-lg:flex-nowrap max-lg:gap-2"><div className="relative min-w-48 flex-1 max-lg:min-w-0"><Search size={16} className="absolute left-3 top-3 text-slate-400 max-lg:left-4 max-lg:top-3.5"/><input aria-label="Search expenses" placeholder="Search expenses…" value={query} onChange={e=>{setQuery(e.target.value);resetPage();}} className={`${input} pl-9 max-lg:h-11 max-lg:rounded-full max-lg:border-0 max-lg:bg-slate-100 max-lg:pl-11`}/></div><select aria-label="Filter by category" value={category} onChange={e=>{setCategory(e.target.value);resetPage();}} className={`${input} max-lg:hidden sm:max-w-56`}><option value="">All Categories</option>{categoryOptions.map(c=><option key={c}>{c}</option>)}</select><button type="button" aria-label="Filter expenses" onClick={()=>{setSheetDraft(null);setSheet("filter");}} className={`relative grid h-11 w-11 shrink-0 place-items-center rounded-full border lg:hidden ${category?"border-blue-200 bg-blue-50 text-blue-600":"border-slate-200 text-slate-700"}`}><SlidersHorizontal size={18}/>{category&&<span className="absolute right-1 top-1 h-2.5 w-2.5 rounded-full bg-blue-600"/>}</button></div>
    <div className="overflow-x-auto"><ul className="divide-y divide-slate-100 lg:hidden">{rows.map(e=><li key={e.id}><button type="button" onClick={()=>setDetail(e)} className="flex w-full items-center gap-3 py-3 text-left"><CategoryIcon name={categoryName(e.category)}/><span className="min-w-0 flex-1"><span className="block truncate font-bold" data-i18n-ignore="true">{e.description}</span><span className="block truncate text-xs text-slate-500">{categoryName(e.category)}</span><span className="block text-xs text-slate-400">{new Intl.DateTimeFormat("en-US",{timeZone:"UTC",month:"short",day:"2-digit",year:"numeric"}).format(new Date(`${e.expense_date}T00:00:00Z`))}</span></span><strong className="shrink-0 text-base">{money(Number(e.amount))}</strong><ChevronRight size={18} className="shrink-0 text-slate-300"/></button></li>)}</ul><table data-phone-layout="custom" className="max-lg:hidden w-full min-w-[850px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{["Date","Category","Branch","Vendor / Description","Payment Method","Amount","Actions"].map(c=><th key={c} className="px-3 py-3 font-semibold">{c}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map(e=><tr key={e.id} className="hover:bg-slate-50"><td className="whitespace-nowrap px-3 py-4">{new Intl.DateTimeFormat("en-US",{timeZone:"UTC",month:"short",day:"2-digit",year:"numeric"}).format(new Date(`${e.expense_date}T00:00:00Z`))}</td><td className="px-3 py-4"><span className="rounded-md bg-blue-50 px-2 py-1 text-blue-700">{categoryName(e.category)}</span></td><td className="px-3 py-4" data-i18n-ignore={Boolean(branches.find(b=>b.id===e.location_id)?.name)}>{branches.find(b=>b.id===e.location_id)?.name||"Unassigned"}</td><td className="max-w-64 break-words px-3 py-4"><p className="font-medium" data-i18n-ignore="true">{e.description}</p><p className="mt-1 text-slate-500" data-i18n-ignore="true">{[e.payee,e.reference].filter(Boolean).join(" · ")}</p></td><td className="px-3 py-4 capitalize">{e.payment_method?.replaceAll("_"," ")||"—"}</td><td className="whitespace-nowrap px-3 py-4 font-semibold">{money(Number(e.amount))}</td><td className="px-3 py-4">{e.has_receipt&&<a href={`/dashboard/expenses/${e.id}/receipt`} target="_blank" rel="noopener noreferrer" onClick={openReceiptInApp} className="mr-2 inline-block text-blue-600 underline">View receipt</a>}<button type="button" disabled={busy} onClick={()=>remove(e)} aria-label={formatUiText(translateText("Delete {0}"), [e.description])} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600 disabled:opacity-50" data-i18n-ignore-attributes="aria-label"><Trash2 size={15}/></button></td></tr>)}</tbody></table>{!rows.length&&<p className="py-12 text-center text-sm text-slate-500">No expenses match these filters.</p>}</div>
    <footer className="mt-4 flex items-center justify-between gap-3 text-xs text-slate-500"><span>Showing {filtered.length?(current-1)*10+1:0}–{Math.min(current*10,filtered.length)} of {filtered.length} expenses</span><div className="flex items-center gap-2"><button aria-label="Previous page" disabled={current===1} onClick={()=>setPage(current-1)} className="rounded-lg border p-2 disabled:opacity-30"><ChevronLeft size={15}/></button><span className="rounded-lg bg-blue-50 px-3 py-2 font-semibold text-blue-600">{current}</span><button aria-label="Next page" disabled={current===pages} onClick={()=>setPage(current+1)} className="rounded-lg border p-2 disabled:opacity-30"><ChevronRight size={15}/></button></div></footer>
   </section></div>
  </div>
  {!sheet&&!detail&&<div className="fixed bottom-[max(1rem,env(safe-area-inset-bottom))] right-4 z-40 flex items-center gap-3 sm:hidden"><button type="button" aria-label="Expense overview" onClick={()=>setSheet("overview")} className="grid h-12 w-12 place-items-center rounded-full border border-slate-200 bg-white text-blue-600 shadow-lg"><ChartNoAxesColumnIncreasing size={20}/></button>{active.length>0&&<button type="button" aria-label="Add expense" onClick={()=>setSheet("add")} className="grid h-14 w-14 place-items-center rounded-full bg-blue-600 text-white shadow-lg shadow-blue-600/30"><Plus size={26}/></button>}</div>}
  {detail&&<div role="dialog" aria-modal="true" aria-label={formatUiText(translateText("Expense {0}"), [detail.description])} data-sheet="center" className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" onClick={e=>{if(e.target===e.currentTarget)setDetail(null);}} data-i18n-ignore-attributes="aria-label"><section className="relative w-full max-w-sm rounded-2xl bg-white p-5 shadow-2xl"><button type="button" aria-label="Close expense details" onClick={()=>setDetail(null)} className="absolute right-3 top-3 grid h-10 w-10 place-items-center rounded-full bg-slate-100 text-slate-600"><X size={18}/></button><div className="flex items-center gap-3 pr-10"><CategoryIcon name={categoryName(detail.category)}/><div className="min-w-0"><h2 className="truncate font-bold" data-i18n-ignore="true">{detail.description}</h2><p className="text-sm text-slate-500">{categoryName(detail.category)}</p></div></div><p className="mt-4 text-2xl font-bold">{money(Number(detail.amount))}</p><dl className="mt-3 grid grid-cols-[110px_1fr] gap-y-1.5 text-sm"><dt className="text-slate-400">Date</dt><dd>{new Intl.DateTimeFormat("en-US",{timeZone:"UTC",month:"short",day:"2-digit",year:"numeric"}).format(new Date(`${detail.expense_date}T00:00:00Z`))}</dd><dt className="text-slate-400">Branch</dt><dd data-i18n-ignore={Boolean(branches.find(b=>b.id===detail.location_id)?.name)}>{branches.find(b=>b.id===detail.location_id)?.name||"Unassigned"}</dd><dt className="text-slate-400">Payment</dt><dd className="capitalize">{detail.payment_method?.replaceAll("_"," ")||"—"}</dd><dt className="text-slate-400">Vendor</dt><dd data-i18n-ignore="true">{detail.payee||"—"}</dd><dt className="text-slate-400">Reference</dt><dd data-i18n-ignore="true">{detail.reference||"—"}</dd></dl><div className="mt-5 flex gap-2">{detail.has_receipt&&<a href={`/dashboard/expenses/${detail.id}/receipt`} target="_blank" rel="noopener noreferrer" onClick={openReceiptInApp} className="flex-1 rounded-xl border border-slate-200 py-3 text-center text-sm font-semibold text-slate-700">View receipt</a>}<button type="button" disabled={busy} onClick={()=>{const target=detail;setDetail(null);void remove(target);}} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-red-50 py-3 text-sm font-semibold text-red-600 disabled:opacity-50"><Trash2 size={15}/>Delete</button></div></section></div>}
  {sheet==="filter"&&<div className="fixed inset-0 z-50 flex items-end bg-slate-950/40 sm:hidden"><button type="button" aria-label="Close filters" onClick={closeSheet} className="absolute inset-0"/><section role="dialog" aria-modal="true" data-sheet="bottom" aria-labelledby="expense-filter-title" className="relative max-h-[90dvh] w-full overflow-y-auto rounded-t-3xl bg-white px-5 pb-[max(1.25rem,env(safe-area-inset-bottom))] pt-3 shadow-2xl">
   <div className="mx-auto h-1.5 w-12 rounded-full bg-slate-200"/>
   <div className="mt-4 flex items-start justify-between gap-3"><div><h2 id="expense-filter-title" className="text-xl font-bold">Filter Expenses</h2><p className="mt-1 text-sm text-slate-500">Select branch and date range</p></div><button type="button" aria-label="Close filters" onClick={closeSheet} className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-slate-100 text-slate-600"><X size={20}/></button></div>
   <label className="mt-5 block text-sm font-semibold text-slate-600">Choose Branch<select aria-label="Filter expenses by branch" value={draft.branch} onChange={e=>setSheetDraft({...draft,branch:e.target.value})} className={`${input} mt-1`}><option value="">All branches</option>{branches.map(b=><option key={b.id} value={b.id} data-i18n-ignore="true">{b.name}{!b.is_active ? (translateText(" (inactive)")) : ("")}</option>)}<option value="unassigned">Unassigned</option></select></label>
   <label className="mt-5 block text-sm font-semibold text-slate-600">Category<select aria-label="Filter by category" value={draft.category} onChange={e=>setSheetDraft({...draft,category:e.target.value})} className={`${input} mt-1`}><option value="">All Categories</option>{categoryOptions.map(c=><option key={c}>{c}</option>)}</select></label>
   <p className="mt-5 text-sm font-semibold text-slate-600">Date Range</p>
   <div className="mt-2 flex flex-wrap gap-2">{[["today","Today"],["yesterday","Yesterday"],["week","This Week"],["month","This Month"],["year","This Year"]].map(([k,l])=>(()=>{const [s,e]=rangeFor(k);const on=draft.from===s&&draft.to===e;return <button key={k} type="button" aria-pressed={on} onClick={()=>setSheetDraft({...draft,from:s,to:e})} className={`rounded-full px-4 py-2 text-sm font-semibold transition ${on?"bg-blue-600 text-white":"bg-slate-100 text-slate-600 hover:bg-blue-50 hover:text-blue-700"}`}>{l}</button>;})())}</div>
   <div className="mt-5 grid grid-cols-[1fr_1fr] gap-3"><label className="min-w-0 text-sm font-semibold text-slate-600">From<input aria-label="Start date" type="date" value={draft.from} max={draft.to||undefined} onChange={e=>setSheetDraft({...draft,from:e.target.value})} className={`${input} mt-1`}/></label><label className="min-w-0 text-sm font-semibold text-slate-600">To<input aria-label="End date" type="date" value={draft.to} min={draft.from||undefined} onChange={e=>setSheetDraft({...draft,to:e.target.value})} className={`${input} mt-1`}/></label></div>
   {sheetError&&<p role="alert" className="mt-3 text-sm font-semibold text-red-600">{sheetError}</p>}<button type="button" onClick={applySheet} disabled={Boolean(sheetError)} className="mt-5 min-h-12 w-full rounded-xl bg-blue-600 font-semibold text-white disabled:opacity-50">Apply</button>
   <button type="button" onClick={()=>setSheetDraft({branch:defaultBranchId,category:"",from:today.slice(0,7)+"-01",to:today})} className="mt-3 min-h-12 w-full rounded-xl bg-slate-100 font-semibold text-slate-600">Reset</button>
  </section></div>}
 </main>;
}
function Field({title,required,wide,children}:{title:string;required?:boolean;wide?:boolean;children:ReactNode}){return <label className={`${wide?"col-span-2":""} block min-w-0 text-xs font-medium`}><span className="mb-1.5 block">{title}{required&&<span className="ml-1 text-red-500">*</span>}</span>{children}</label>;}
function Heading({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <div className="flex items-center gap-3"><span className="rounded-xl bg-blue-50 p-3 text-blue-600">{icon}</span><div><h2 className="font-bold">{title}</h2><p className="mt-0.5 text-xs text-slate-500">{text}</p></div></div>;}
function Metric({title,short,value,detail,icon,color}:{title:string;short:string;value:string;detail:string;icon:ReactNode;color:string}){return <div className={`${panel} flex min-w-0 items-center gap-4 max-lg:flex-col max-lg:gap-1.5 max-lg:rounded-2xl max-lg:p-2.5 max-lg:text-center`}><span className={`rounded-xl p-4 max-lg:p-2.5 max-lg:[&>svg]:h-5 max-lg:[&>svg]:w-5 ${color}`}>{icon}</span><div className="min-w-0"><p className="text-xs text-slate-500 max-lg:hidden">{title}</p><strong className="mt-1 block break-words text-xl font-bold max-lg:mt-0 max-lg:text-sm">{value}</strong><p className="hidden text-[11px] text-slate-500 max-lg:block">{short}</p><p className="mt-1 text-xs text-slate-400 max-lg:hidden">{detail}</p></div></div>;}
const CATEGORY_ICONS:Record<string,[LucideIcon,string]>={"Rent":[House,"bg-rose-50 text-rose-600"],"Utilities":[Zap,"bg-amber-50 text-amber-600"],"Staff / Payroll":[Users,"bg-violet-50 text-violet-600"],"Marketing & Advertising":[Megaphone,"bg-pink-50 text-pink-600"],"Delivery & Transport":[Truck,"bg-slate-100 text-slate-700"],"Office Supplies":[Paperclip,"bg-slate-100 text-slate-700"],"Packaging":[ShoppingBag,"bg-red-50 text-red-600"],"Repairs & Maintenance":[Wrench,"bg-blue-50 text-blue-600"],"Software & Subscriptions":[MonitorSmartphone,"bg-cyan-50 text-cyan-600"],"Bank & Payment Fees":[Landmark,"bg-emerald-50 text-emerald-600"],"Taxes & Government Fees":[FileText,"bg-orange-50 text-orange-600"],"Professional Services":[Briefcase,"bg-indigo-50 text-indigo-600"],"Phone & Communication":[Phone,"bg-teal-50 text-teal-600"],"Travel":[Plane,"bg-sky-50 text-sky-600"],"Meals & Entertainment":[Utensils,"bg-blue-50 text-blue-600"],"Cleaning & Supplies":[SprayCan,"bg-lime-50 text-lime-700"],"Equipment":[Wrench,"bg-blue-50 text-blue-600"]};
/** Category icon tile for the phone expense list. Unknown categories use a receipt. */
function CategoryIcon({name}:{name:string}){const [Icon,tone]=CATEGORY_ICONS[name]??[Receipt,"bg-slate-100 text-slate-600"];return <span className={`grid h-12 w-12 shrink-0 place-items-center rounded-xl ${tone}`}><Icon size={22}/></span>;}
