"use server";
import { revalidatePath } from "next/cache";
import { requirePermission } from "@/lib/auth/require-permission";
import { createClient } from "@/lib/supabase/server";
import { createAuditLog } from "@/lib/audit/create-audit-log";
function t(fd:FormData,k:string){const v=fd.get(k);return typeof v==="string"?v.trim():""}
export async function createTransfer(fd:FormData){const business=await requirePermission("transfers.manage"); const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) throw new Error("Login required."); const source=t(fd,"sourceLocationId"),dest=t(fd,"destinationLocationId"),product=t(fd,"productId"),qty=Number(t(fd,"quantity")); if(!source||!dest||source===dest||!product||!Number.isInteger(qty)||qty<=0) throw new Error("Complete the transfer form."); const number=`TR-${Date.now().toString(36).toUpperCase()}`; const {data:tr,error}=await supabase.from("stock_transfers").insert({business_id:business.id,transfer_number:number,source_location_id:source,destination_location_id:dest,note:t(fd,"note")||null,created_by:user.id}).select("id").single(); if(error) throw new Error(error.message); const {error:itemError}=await supabase.from("stock_transfer_items").insert({transfer_id:tr.id,business_id:business.id,product_id:product,quantity:qty}); if(itemError) throw new Error(itemError.message); await createAuditLog({action:"create",entityType:"inventory",entityId:tr.id,description:`Created stock transfer ${number}`,metadata:{source,destination:dest,product,quantity:qty}}); revalidatePath("/dashboard/stock-transfers");}
export async function sendTransfer(fd:FormData){const business=await requirePermission("transfers.manage"); const id=t(fd,"transferId"); const supabase=await createClient(); const {error}=await supabase.rpc("send_stock_transfer",{p_business_id:business.id,p_transfer_id:id}); if(error) throw new Error(error.message); await createAuditLog({action:"update",entityType:"inventory",entityId:id,description:"Sent stock transfer"}); revalidatePath("/dashboard/stock-transfers");}
export async function receiveTransfer(fd:FormData){const business=await requirePermission("transfers.manage"); const id=t(fd,"transferId"); const supabase=await createClient(); const {error}=await supabase.rpc("receive_stock_transfer",{p_business_id:business.id,p_transfer_id:id}); if(error) throw new Error(error.message); await createAuditLog({action:"update",entityType:"inventory",entityId:id,description:"Received stock transfer"}); revalidatePath("/dashboard/stock-transfers"); revalidatePath("/dashboard/inventory");}

export async function addTransferItem(fd:FormData){const business=await requirePermission("transfers.manage"); const transferId=t(fd,"transferId"),product=t(fd,"productId"),qty=Number(t(fd,"quantity")); if(!transferId||!product||!Number.isInteger(qty)||qty<=0) throw new Error("Choose a product and quantity."); const supabase=await createClient(); const {data:transfer}=await supabase.from("stock_transfers").select("id").eq("id",transferId).eq("business_id",business.id).eq("status","draft").maybeSingle(); if(!transfer) throw new Error("Draft transfer not found."); const {error}=await supabase.from("stock_transfer_items").upsert({transfer_id:transferId,business_id:business.id,product_id:product,quantity:qty},{onConflict:"transfer_id,product_id"}); if(error) throw new Error(error.message); await createAuditLog({action:"update",entityType:"inventory",entityId:transferId,description:"Added item to stock transfer",metadata:{product,quantity:qty}}); revalidatePath("/dashboard/stock-transfers");}
