// Template column names only; no business records or credentials.
export const importColumns: Record<string, string[]> = {
  "branch_pos_settings": ["business_id","location_id","currency","currency_format","pos_tax_rate","pos_point_value","pos_dual_currency_enabled","pos_usd_khr_rate","loyalty_enabled","loyalty_spend_per_point","loyalty_minimum_order","updated_at"],
  "branch_role_permissions": ["business_id","location_id","role","permission","enabled","updated_at","updated_by"],
  "branch_notification_role_settings": ["business_id","location_id","notification_type","target_roles","updated_at","updated_by"],
  "businesses": ["id","name","slug","owner_id","phone","email","address","logo_url","product_mode","is_active","created_at","updated_at","disabled_at","scheduled_deletion_at","max_staff","subscription_started_at","subscription_expires_at","subscription_months","disabled_reason","business_code","last_extension_months","subscription_logs","archived_at","released_slug","subscription_status","trial_started_at","trial_expires_at","expired_at","deletion_scheduled_at","trial_block_reason","subscription_plan_key","subscription_user_limit","subscription_team_enabled","free_url_changes_per_month","free_business_mode_changes_per_month","subscription_monthly_price","subscription_discount_percent","subscription_cycle_value","subscription_branch_limit","subscription_base_plan_key"],
  "business_locations": ["id","business_id","name","code","address","phone","is_default","is_active","created_at","updated_at","city","state_region","timezone","opening_hours","notes","manager_user_id","plan_disable_pending","plan_disabled_at"],
  "business_storefronts": ["business_id","business_type","is_published","accept_online_orders","template_key","display_name","description","logo_url","banner_url","primary_color","phone","address","currency","allow_pickup","allow_delivery","allow_dine_in","minimum_order","estimated_minutes","created_at","updated_at","delivery_fee","checkout_message","accept_cod","accept_khqr","khqr_image_url","khqr_account_name","khqr_instructions","allow_scheduled_orders","min_schedule_lead_minutes","max_schedule_days","enable_coupons","loyalty_enabled","loyalty_spend_per_point","loyalty_minimum_order","social_links","pos_tax_rate","pos_point_value","pos_dual_currency_enabled","pos_usd_khr_rate","fulfillment_location_id","currency_format"],
  "business_receipt_settings": ["business_id","paper_size","header_text","footer_text","logo_url","show_logo","show_phone","show_address","show_cashier","show_customer","show_discount","show_payment","show_loyalty","show_store_qr","store_qr_label","updated_at","receipt_template","return_policy","website_url","show_order_number","show_fulfillment","show_notes","show_invoice_barcode","font_size","density","receipt_alignment","receipt_copies","shipping_label_size","shipping_show_sender","shipping_show_phone","shipping_show_order_number","shipping_show_cod","shipping_show_item_count","shipping_show_barcode","barcode_label_size","barcode_show_name","barcode_show_price","barcode_show_sku","barcode_show_variant","barcode_template","barcode_show_barcode","barcode_show_image","barcode_show_store_name","barcode_show_custom_text","barcode_custom_text","receipt_logo_url","receipt_qr_url","show_receipt_qr"],
  "business_customer_settings": ["business_id","email_enabled","birthday_enabled","created_at","updated_at"],
  "business_delivery_zones": ["id","business_id","name","fee","minimum_order","is_active","sort_order","created_at","updated_at"],
  "business_tables": ["id","business_id","name","is_active","created_at","updated_at"],
  "products": ["id","owner_id","category_id","name","sku","description","image_url","cost_price","selling_price","stock_quantity","low_stock_quantity","is_active","created_at","updated_at","size","color","business_id","product_type","is_online","online_sort_order","variant_group_id","barcode","style_name","brand_name","low_stock_threshold","variant_image_url","bundle_stock_mode","is_pos"],
  "product_variants": ["id","product_id","size","color","sku","barcode","price","stock_quantity","is_active","created_at","updated_at"],
  "categories": ["id","owner_id","name","description","created_at","business_id","is_online","online_sort_order","branch_ids"],
  "product_location_stock": ["business_id","location_id","product_id","quantity","low_stock_threshold","updated_at"],
  "product_option_groups": ["id","business_id","product_id","name","selection_type","is_required","min_selections","max_selections","sort_order","created_at","updated_at"],
  "product_options": ["id","business_id","product_id","group_id","name","price_adjustment","is_default","is_active","sort_order","created_at","updated_at"],
  "bundle_items": ["id","business_id","bundle_product_id","component_product_id","quantity","created_at","updated_at","selected_options"],
  "inventory_movements": ["id","owner_id","product_id","order_id","movement_type","quantity","stock_before","stock_after","note","created_at","return_id","business_id"],
  "stock_adjustments": ["id","business_id","product_id","adjustment_type","quantity_delta","stock_before","stock_after","reason","reference","created_by","created_at","location_id"],
  "stock_transfers": ["id","business_id","transfer_number","source_location_id","destination_location_id","status","note","created_by","sent_by","received_by","sent_at","received_at","created_at","updated_at"],
  "stock_transfer_items": ["id","transfer_id","business_id","product_id","quantity","created_at"],
  "orders": ["id","owner_id","order_number","subtotal","discount","total","payment_method","amount_paid","change_amount","status","created_at","customer_id","updated_at","remaining_balance","delivery_fee","business_id","order_source","fulfillment_type","online_status","guest_name","guest_phone","guest_address","customer_note","table_id","table_name","payment_status","payment_reference","delivery_zone_id","delivery_zone_name","requested_for","coupon_id","coupon_code","coupon_discount","loyalty_points_earned","location_id","register_shift_id","credit_amount","archived_at","archived_by","pos_request_id","pos_request_hash","pos_checkout","staff_user_id","staff_name"],
  "order_items": ["id","order_id","owner_id","product_id","product_name","sku","quantity","unit_price","cost_price","subtotal","created_at","variant_label","selected_options"],
  "returns": ["id","owner_id","order_id","return_number","reason","refund_amount","created_at","business_id","status","return_type","source","refund_method","restock_status","import_product_name","import_quantity","location_id"],
  "return_items": ["id","owner_id","return_id","order_item_id","product_id","product_name","quantity","unit_price","subtotal","created_at"],
  "tenh_pos_holds": ["id","business_id","created_by","label","draft","version","order_id","created_at","updated_at","location_id"],
  "tenh_pos_points_used": ["order_id","business_id","customer_id","points","restored_at"],
  "customers": ["id","owner_id","name","phone","email","address","note","created_at","updated_at","business_id","loyalty_points","lifetime_loyalty_points","birthday","location_id"],
  "customer_credit_accounts": ["business_id","customer_id","credit_limit","balance","notes","updated_at","payment_due_date"],
  "customer_credit_ledger": ["id","business_id","customer_id","order_id","entry_type","amount","balance_after","note","reference","created_by","created_at"],
  "customer_loyalty_transactions": ["id","business_id","customer_id","order_id","transaction_type","points","note","created_at"],
  "business_coupons": ["id","business_id","code","name","discount_type","discount_value","minimum_order","max_discount","starts_at","ends_at","usage_limit","per_customer_limit","usage_count","is_active","created_at","updated_at","location_id"],
  "coupon_redemptions": ["id","business_id","coupon_id","order_id","customer_id","guest_phone","discount_amount","created_at"],
  "suppliers": ["id","owner_id","name","contact_person","phone","email","address","notes","is_active","created_at","updated_at","business_id","location_id"],
  "purchases": ["id","owner_id","supplier_id","purchase_number","supplier_name","reference_number","purchase_date","status","subtotal","total","notes","created_at","updated_at","cancellation_reason","cancelled_at","business_id","location_id"],
  "purchase_items": ["id","owner_id","purchase_id","product_id","product_name","quantity","unit_cost","subtotal","created_at"],
  "purchase_orders": ["id","business_id","supplier_id","po_number","supplier_name","reference_number","status","order_date","expected_date","notes","subtotal","total","created_by","created_at","updated_at","location_id"],
  "purchase_order_items": ["id","business_id","purchase_order_id","product_id","product_name","sku","ordered_quantity","received_quantity","unit_cost","created_at","updated_at"],
  "expenses": ["id","owner_id","category","description","amount","expense_date","created_at","updated_at","business_id","location_id","payee","payment_method","reference","metadata","recurrence_rule","next_due_date"],
  "cash_register_shifts": ["id","business_id","location_id","opened_by","closed_by","status","opening_cash","closing_cash","expected_cash","variance","opening_note","closing_note","opened_at","closed_at","created_at","register_summary"],
  "cash_movements": ["id","business_id","shift_id","location_id","created_by","movement_type","amount","reason","reference","created_at"],
  "audit_logs": ["id","user_id","action","entity_type","entity_id","description","metadata","created_at","business_id","ip_address","user_agent","location_id"],
  "business_activity_history": ["id","business_id","action","title","description","previous_values","new_values","metadata","reason","created_by","created_at"],
};
importColumns.branch_product_details=[...importColumns.products,'location_id','branch_archived'];
importColumns.branch_bundle_recipes=[...importColumns.bundle_items,'location_id'];
importColumns.branch_receipt_settings=[...importColumns.business_receipt_settings,'location_id'];
importColumns.branch_customer_settings=[...importColumns.business_customer_settings,'location_id'];
importColumns.business_receipt_settings.push('location_id');
importColumns.business_customer_settings.push('location_id');
